// GENERATED by @edgedb/generate v0.5.3

import * as $ from '../reflection.mjs';
import * as _ from '../imports.mjs';
const AccessKind = $.makeType(_.spec, '998b88fc-083a-584b-85bb-372ade248f66', _.syntax.literal);

const AccessPolicyAction = $.makeType(_.spec, 'd8c466cc-109e-587c-aff8-42e50705b5b0', _.syntax.literal);

const Cardinality = $.makeType(_.spec, '94abc2f6-2e3e-55fc-8e97-b44ba70a3950', _.syntax.literal);

const MigrationGeneratedBy = $.makeType(_.spec, '8fcfde20-139b-5c17-93b9-9a49512b83dc', _.syntax.literal);

const OperatorKind = $.makeType(_.spec, 'e48403f0-7017-5bf5-ab92-22825d9f1090', _.syntax.literal);

const ParameterKind = $.makeType(_.spec, '8037d84a-de95-5e63-ab76-727112419261', _.syntax.literal);

const RewriteKind = $.makeType(_.spec, 'a06f04aa-88b7-5d9a-b520-b8139fd64d0c', _.syntax.literal);

const SourceDeleteAction = $.makeType(_.spec, '1c938388-8739-57a7-8095-cc173226ad8e', _.syntax.literal);

const TargetDeleteAction = $.makeType(_.spec, '6b925c92-5e48-5e6d-96f2-4125d9119b66', _.syntax.literal);

const TriggerKind = $.makeType(_.spec, '3c6fa29f-8481-59c9-a9bf-ac30ab50be32', _.syntax.literal);

const TriggerScope = $.makeType(_.spec, '20998fe7-4392-5673-96b5-5f1cd736b5df', _.syntax.literal);

const TriggerTiming = $.makeType(_.spec, 'a2c7e6ae-370c-53a7-842c-21e238faf3ee', _.syntax.literal);

const TypeModifier = $.makeType(_.spec, '67722d75-1145-54b6-af26-94602de09d51', _.syntax.literal);

const Volatility = $.makeType(_.spec, 'de5b90f2-6e49-5543-991b-28a156c7867f', _.syntax.literal);

const $Object_32faaa35947553cf88fce68ecf1be4d9 = $.makeType(_.spec, '32faaa35-9475-53cf-88fc-e68ecf1be4d9', _.syntax.literal);

const Object_32faaa35947553cf88fce68ecf1be4d9 = _.syntax.$PathNode($.$toSet($Object_32faaa35947553cf88fce68ecf1be4d9, $.Cardinality.Many), null);

const $SubclassableObject = $.makeType(_.spec, '145b7b6f-8fa4-5b14-bcd3-5d6d10dc25da', _.syntax.literal);

const SubclassableObject = _.syntax.$PathNode($.$toSet($SubclassableObject, $.Cardinality.Many), null);

const $InheritingObject = $.makeType(_.spec, '825a1378-6b30-5f15-82f1-1c92e57691f2', _.syntax.literal);

const InheritingObject = _.syntax.$PathNode($.$toSet($InheritingObject, $.Cardinality.Many), null);

const $AnnotationSubject = $.makeType(_.spec, '970b2d83-85d8-5a46-a4e8-337d28abc12e', _.syntax.literal);

const AnnotationSubject = _.syntax.$PathNode($.$toSet($AnnotationSubject, $.Cardinality.Many), null);

const $AccessPolicy = $.makeType(_.spec, 'a8462073-0539-5640-9d9d-2db251c0b350', _.syntax.literal);

const AccessPolicy = _.syntax.$PathNode($.$toSet($AccessPolicy, $.Cardinality.Many), null);

const $Alias = $.makeType(_.spec, '4388400b-e01d-582c-b1da-8161814835a6', _.syntax.literal);

const Alias = _.syntax.$PathNode($.$toSet($Alias, $.Cardinality.Many), null);

const $Annotation = $.makeType(_.spec, '273b8735-318f-53f6-9297-6f20162c9105', _.syntax.literal);

const Annotation = _.syntax.$PathNode($.$toSet($Annotation, $.Cardinality.Many), null);

const $Type = $.makeType(_.spec, '8e652319-e551-5b5c-a7bd-9591f0ef5303', _.syntax.literal);

const Type = _.syntax.$PathNode($.$toSet($Type, $.Cardinality.Many), null);

const $PrimitiveType = $.makeType(_.spec, 'da26fa09-3541-5cba-b93f-d5ba58d25589', _.syntax.literal);

const PrimitiveType = _.syntax.$PathNode($.$toSet($PrimitiveType, $.Cardinality.Many), null);

const $CollectionType = $.makeType(_.spec, 'e3a7ccf7-4a20-5151-80b3-5156c9373889', _.syntax.literal);

const CollectionType = _.syntax.$PathNode($.$toSet($CollectionType, $.Cardinality.Many), null);

const $Array = $.makeType(_.spec, '283cc7a9-7bf6-5eda-a323-b4e5173f2927', _.syntax.literal);

const Array = _.syntax.$PathNode($.$toSet($Array, $.Cardinality.Many), null);

const $ArrayExprAlias = $.makeType(_.spec, '2e55d7f5-18ed-54b4-ade0-ba404dd482d3', _.syntax.literal);

const ArrayExprAlias = _.syntax.$PathNode($.$toSet($ArrayExprAlias, $.Cardinality.Many), null);

const $CallableObject = $.makeType(_.spec, '800f2df9-dd86-5681-9e3c-b529af481a9d', _.syntax.literal);

const CallableObject = _.syntax.$PathNode($.$toSet($CallableObject, $.Cardinality.Many), null);

const $VolatilitySubject = $.makeType(_.spec, 'ed8e20ca-f2dc-5626-bccb-05ef9ed65791', _.syntax.literal);

const VolatilitySubject = _.syntax.$PathNode($.$toSet($VolatilitySubject, $.Cardinality.Many), null);

const $Cast = $.makeType(_.spec, '2b25c5a4-5ad4-5c4b-b545-574ccac3fd7f', _.syntax.literal);

const Cast = _.syntax.$PathNode($.$toSet($Cast, $.Cardinality.Many), null);

const $ConsistencySubject = $.makeType(_.spec, '883ec593-7428-5707-af16-d446e5d8ed28', _.syntax.literal);

const ConsistencySubject = _.syntax.$PathNode($.$toSet($ConsistencySubject, $.Cardinality.Many), null);

const $Constraint = $.makeType(_.spec, '9346c403-6ee6-50b6-81b2-a35551cfab2f', _.syntax.literal);

const Constraint = _.syntax.$PathNode($.$toSet($Constraint, $.Cardinality.Many), null);

const $Delta = $.makeType(_.spec, 'c974be74-46d8-5848-b2a9-be5eda14f73e', _.syntax.literal);

const Delta = _.syntax.$PathNode($.$toSet($Delta, $.Cardinality.Many), null);

const $Extension = $.makeType(_.spec, 'b9c53751-8d28-5077-b1db-a03ea59557ed', _.syntax.literal);

const Extension = _.syntax.$PathNode($.$toSet($Extension, $.Cardinality.Many), null);

const $Function = $.makeType(_.spec, '3a60f555-7c03-5287-b4c9-f078692a89ef', _.syntax.literal);

const Function = _.syntax.$PathNode($.$toSet($Function, $.Cardinality.Many), null);

const $FutureBehavior = $.makeType(_.spec, '003feed0-dc7d-564e-abb5-93a42ba99d64', _.syntax.literal);

const FutureBehavior = _.syntax.$PathNode($.$toSet($FutureBehavior, $.Cardinality.Many), null);

const $Global = $.makeType(_.spec, 'e1294378-bb3d-57e0-81d2-6a19ea088231', _.syntax.literal);

const Global = _.syntax.$PathNode($.$toSet($Global, $.Cardinality.Many), null);

const $Index = $.makeType(_.spec, 'decfa7fb-1f66-5986-be86-fc9b6c268a97', _.syntax.literal);

const Index = _.syntax.$PathNode($.$toSet($Index, $.Cardinality.Many), null);

const $Pointer = $.makeType(_.spec, '57e1c6b1-ce76-5b5b-943f-f01f1e6a16a3', _.syntax.literal);

const Pointer = _.syntax.$PathNode($.$toSet($Pointer, $.Cardinality.Many), null);

const $Source = $.makeType(_.spec, '0368bb5e-ae06-5c00-9316-15095185b828', _.syntax.literal);

const Source = _.syntax.$PathNode($.$toSet($Source, $.Cardinality.Many), null);

const $Link = $.makeType(_.spec, '98fe77cc-128e-58fe-b87a-1251c3288548', _.syntax.literal);

const Link = _.syntax.$PathNode($.$toSet($Link, $.Cardinality.Many), null);

const $Migration = $.makeType(_.spec, '31f74b3a-d9b1-5e35-a746-057f44c58e76', _.syntax.literal);

const Migration = _.syntax.$PathNode($.$toSet($Migration, $.Cardinality.Many), null);

const $Module = $.makeType(_.spec, '7106039a-ed86-5868-8227-3e2fc5e3e5ec', _.syntax.literal);

const Module = _.syntax.$PathNode($.$toSet($Module, $.Cardinality.Many), null);

const $MultiRange = $.makeType(_.spec, '800c4a49-db9d-5a39-9cf2-aa213b858616', _.syntax.literal);

const MultiRange = _.syntax.$PathNode($.$toSet($MultiRange, $.Cardinality.Many), null);

const $MultiRangeExprAlias = $.makeType(_.spec, 'a92ef6fd-611e-5b00-8115-cc0ebb5f0be5', _.syntax.literal);

const MultiRangeExprAlias = _.syntax.$PathNode($.$toSet($MultiRangeExprAlias, $.Cardinality.Many), null);

const $ObjectType = $.makeType(_.spec, '2662a1b4-4f3f-5875-b6eb-ce52101a90a3', _.syntax.literal);

const ObjectType = _.syntax.$PathNode($.$toSet($ObjectType, $.Cardinality.Many), null);

const $Operator = $.makeType(_.spec, 'e37bd85e-5e2f-5daa-9dd9-d21d419032be', _.syntax.literal);

const Operator = _.syntax.$PathNode($.$toSet($Operator, $.Cardinality.Many), null);

const $Parameter = $.makeType(_.spec, '87f7d583-3e3c-507e-9fbb-4bf3b9e5aa24', _.syntax.literal);

const Parameter = _.syntax.$PathNode($.$toSet($Parameter, $.Cardinality.Many), null);

const $Property = $.makeType(_.spec, 'a57f48ff-3bb9-5693-a2e1-bf328a2ddbfc', _.syntax.literal);

const Property = _.syntax.$PathNode($.$toSet($Property, $.Cardinality.Many), null);

const $PseudoType = $.makeType(_.spec, '0875f8c3-7033-5cc4-af04-2b6d80e289e0', _.syntax.literal);

const PseudoType = _.syntax.$PathNode($.$toSet($PseudoType, $.Cardinality.Many), null);

const $Range = $.makeType(_.spec, 'cced31f8-8167-59d7-b269-c49ae88a0ac1', _.syntax.literal);

const Range = _.syntax.$PathNode($.$toSet($Range, $.Cardinality.Many), null);

const $RangeExprAlias = $.makeType(_.spec, 'bc63491c-2a88-5353-b5f0-6f2188a4f65d', _.syntax.literal);

const RangeExprAlias = _.syntax.$PathNode($.$toSet($RangeExprAlias, $.Cardinality.Many), null);

const $Rewrite = $.makeType(_.spec, 'd60198c8-ad58-5c4c-b3b6-d520c19f5cef', _.syntax.literal);

const Rewrite = _.syntax.$PathNode($.$toSet($Rewrite, $.Cardinality.Many), null);

const $ScalarType = $.makeType(_.spec, 'd055dd47-3eb9-5a31-9d8f-5e7053bbe11e', _.syntax.literal);

const ScalarType = _.syntax.$PathNode($.$toSet($ScalarType, $.Cardinality.Many), null);

const $Trigger = $.makeType(_.spec, '2b738231-1ef7-59d0-a04c-dae012181a02', _.syntax.literal);

const Trigger = _.syntax.$PathNode($.$toSet($Trigger, $.Cardinality.Many), null);

const $Tuple = $.makeType(_.spec, 'd88b4a0c-9561-56f4-b0a9-7b24027b4de8', _.syntax.literal);

const Tuple = _.syntax.$PathNode($.$toSet($Tuple, $.Cardinality.Many), null);

const $TupleElement = $.makeType(_.spec, '9cc04b0b-11e0-5670-a8a1-441a323e12fb', _.syntax.literal);

const TupleElement = _.syntax.$PathNode($.$toSet($TupleElement, $.Cardinality.Many), null);

const $TupleExprAlias = $.makeType(_.spec, 'b7744aa3-50fc-54e0-ae51-20d78737e25b', _.syntax.literal);

const TupleExprAlias = _.syntax.$PathNode($.$toSet($TupleExprAlias, $.Cardinality.Many), null);

export {
	AccessKind,
	AccessPolicyAction,
	Cardinality,
	MigrationGeneratedBy,
	OperatorKind,
	ParameterKind,
	RewriteKind,
	SourceDeleteAction,
	TargetDeleteAction,
	TriggerKind,
	TriggerScope,
	TriggerTiming,
	TypeModifier,
	Volatility,
	$Object_32faaa35947553cf88fce68ecf1be4d9,
	Object_32faaa35947553cf88fce68ecf1be4d9,
	$SubclassableObject,
	SubclassableObject,
	$InheritingObject,
	InheritingObject,
	$AnnotationSubject,
	AnnotationSubject,
	$AccessPolicy,
	AccessPolicy,
	$Alias,
	Alias,
	$Annotation,
	Annotation,
	$Type,
	Type,
	$PrimitiveType,
	PrimitiveType,
	$CollectionType,
	CollectionType,
	$Array,
	Array,
	$ArrayExprAlias,
	ArrayExprAlias,
	$CallableObject,
	CallableObject,
	$VolatilitySubject,
	VolatilitySubject,
	$Cast,
	Cast,
	$ConsistencySubject,
	ConsistencySubject,
	$Constraint,
	Constraint,
	$Delta,
	Delta,
	$Extension,
	Extension,
	$Function,
	Function,
	$FutureBehavior,
	FutureBehavior,
	$Global,
	Global,
	$Index,
	Index,
	$Pointer,
	Pointer,
	$Source,
	Source,
	$Link,
	Link,
	$Migration,
	Migration,
	$Module,
	Module,
	$MultiRange,
	MultiRange,
	$MultiRangeExprAlias,
	MultiRangeExprAlias,
	$ObjectType,
	ObjectType,
	$Operator,
	Operator,
	$Parameter,
	Parameter,
	$Property,
	Property,
	$PseudoType,
	PseudoType,
	$Range,
	Range,
	$RangeExprAlias,
	RangeExprAlias,
	$Rewrite,
	Rewrite,
	$ScalarType,
	ScalarType,
	$Trigger,
	Trigger,
	$Tuple,
	Tuple,
	$TupleElement,
	TupleElement,
	$TupleExprAlias,
	TupleExprAlias
};

const __defaultExports = {
	AccessKind: AccessKind,
	AccessPolicyAction: AccessPolicyAction,
	Cardinality: Cardinality,
	MigrationGeneratedBy: MigrationGeneratedBy,
	OperatorKind: OperatorKind,
	ParameterKind: ParameterKind,
	RewriteKind: RewriteKind,
	SourceDeleteAction: SourceDeleteAction,
	TargetDeleteAction: TargetDeleteAction,
	TriggerKind: TriggerKind,
	TriggerScope: TriggerScope,
	TriggerTiming: TriggerTiming,
	TypeModifier: TypeModifier,
	Volatility: Volatility,
	Object: Object_32faaa35947553cf88fce68ecf1be4d9,
	SubclassableObject: SubclassableObject,
	InheritingObject: InheritingObject,
	AnnotationSubject: AnnotationSubject,
	AccessPolicy: AccessPolicy,
	Alias: Alias,
	Annotation: Annotation,
	Type: Type,
	PrimitiveType: PrimitiveType,
	CollectionType: CollectionType,
	Array: Array,
	ArrayExprAlias: ArrayExprAlias,
	CallableObject: CallableObject,
	VolatilitySubject: VolatilitySubject,
	Cast: Cast,
	ConsistencySubject: ConsistencySubject,
	Constraint: Constraint,
	Delta: Delta,
	Extension: Extension,
	Function: Function,
	FutureBehavior: FutureBehavior,
	Global: Global,
	Index: Index,
	Pointer: Pointer,
	Source: Source,
	Link: Link,
	Migration: Migration,
	Module: Module,
	MultiRange: MultiRange,
	MultiRangeExprAlias: MultiRangeExprAlias,
	ObjectType: ObjectType,
	Operator: Operator,
	Parameter: Parameter,
	Property: Property,
	PseudoType: PseudoType,
	Range: Range,
	RangeExprAlias: RangeExprAlias,
	Rewrite: Rewrite,
	ScalarType: ScalarType,
	Trigger: Trigger,
	Tuple: Tuple,
	TupleElement: TupleElement,
	TupleExprAlias: TupleExprAlias
};
export default __defaultExports;
