// GENERATED by @edgedb/generate v0.5.3

import * as $ from '../reflection.mjs';
import * as _ from '../imports.mjs';
import _module__enc from './std/enc.mjs';

const Endian = $.makeType(_.spec, 'e4a1d11b-227e-5744-a0c9-31f9cd756e7b', _.syntax.literal);

const JsonEmpty = $.makeType(_.spec, '584feb89-c83d-561d-aa78-24e6d779f044', _.syntax.literal);

const bigint = $.makeType(_.spec, '00000000-0000-0000-0000-000000000110', _.syntax.literal);

const bool = $.makeType(_.spec, '00000000-0000-0000-0000-000000000109', _.syntax.literal);

const bytes = $.makeType(_.spec, '00000000-0000-0000-0000-000000000102', _.syntax.literal);

const datetime = $.makeType(_.spec, '00000000-0000-0000-0000-00000000010a', _.syntax.literal);

const decimal = $.makeType(_.spec, '00000000-0000-0000-0000-000000000108', _.syntax.literal);

const duration = $.makeType(_.spec, '00000000-0000-0000-0000-00000000010e', _.syntax.literal);

const float32 = $.makeType(_.spec, '00000000-0000-0000-0000-000000000106', _.syntax.literal);

const float64 = $.makeType(_.spec, '00000000-0000-0000-0000-000000000107', _.syntax.literal);

const int16 = $.makeType(_.spec, '00000000-0000-0000-0000-000000000103', _.syntax.literal);

const int32 = $.makeType(_.spec, '00000000-0000-0000-0000-000000000104', _.syntax.literal);

const int64 = $.makeType(_.spec, '00000000-0000-0000-0000-000000000105', _.syntax.literal);

const json = $.makeType(_.spec, '00000000-0000-0000-0000-00000000010f', _.syntax.literal);

const $sequence = $.makeType(_.spec, 'fd1c52ea-74a9-541b-88e2-378d1edb02fd', _.syntax.literal);

const str = $.makeType(_.spec, '00000000-0000-0000-0000-000000000101', _.syntax.literal);

const uuid = $.makeType(_.spec, '00000000-0000-0000-0000-000000000100', _.syntax.literal);

const number = $.makeType(_.spec, '00000000-0000-0000-0000-0000000001ff', _.syntax.literal);

const $BaseObject = $.makeType(_.spec, '0d14e49f-d9f9-51f0-b8f4-c432982cbac2', _.syntax.literal);

const BaseObject = _.syntax.$PathNode($.$toSet($BaseObject, $.Cardinality.Many), null);

const $Object_8ce8c71ee4fa5f73840c22d7eaa58588 = $.makeType(_.spec, '8ce8c71e-e4fa-5f73-840c-22d7eaa58588', _.syntax.literal);

const Object_8ce8c71ee4fa5f73840c22d7eaa58588 = _.syntax.$PathNode($.$toSet($Object_8ce8c71ee4fa5f73840c22d7eaa58588, $.Cardinality.Many), null);

const $FreeObject = $.makeType(_.spec, '3b741934-07ef-5b95-b7d6-cdc864fd2ae8', _.syntax.literal);

const FreeObject = _.syntax.$PathNode($.$toSet($FreeObject, $.Cardinality.One), null);

function assert_single(...args) {
	const {
		returnType,
		cardinality,
		args: positionalArgs,
		namedArgs
	} = _.syntax.$resolveOverload('std::assert_single', args, _.spec, [
		{
			args: [{ typeId: '00000000-0000-0000-0000-000000000001', optional: false, setoftype: true, variadic: false }],
			namedArgs: { message: { typeId: '00000000-0000-0000-0000-000000000101', optional: true, setoftype: false, variadic: false } },
			returnTypeId: '00000000-0000-0000-0000-000000000001',
			returnTypemod: 'OptionalType',
			preservesOptionality: true
		}
	]);
	return _.syntax.$expressionify({
		__kind__: $.ExpressionKind.Function,
		__element__: returnType,
		__cardinality__: cardinality,
		__name__: 'std::assert_single',
		__args__: positionalArgs,
		__namedargs__: namedArgs
	});
}

function assert_exists(...args) {
	const {
		returnType,
		cardinality,
		args: positionalArgs,
		namedArgs
	} = _.syntax.$resolveOverload('std::assert_exists', args, _.spec, [
		{
			args: [{ typeId: '00000000-0000-0000-0000-000000000001', optional: false, setoftype: true, variadic: false }],
			namedArgs: { message: { typeId: '00000000-0000-0000-0000-000000000101', optional: true, setoftype: false, variadic: false } },
			returnTypeId: '00000000-0000-0000-0000-000000000001',
			returnTypemod: 'SetOfType'
		}
	]);
	return _.syntax.$expressionify({
		__kind__: $.ExpressionKind.Function,
		__element__: returnType,
		__cardinality__: cardinality,
		__name__: 'std::assert_exists',
		__args__: positionalArgs,
		__namedargs__: namedArgs
	});
}

function assert_distinct(...args) {
	const {
		returnType,
		cardinality,
		args: positionalArgs,
		namedArgs
	} = _.syntax.$resolveOverload('std::assert_distinct', args, _.spec, [
		{
			args: [{ typeId: '00000000-0000-0000-0000-000000000001', optional: false, setoftype: true, variadic: false }],
			namedArgs: { message: { typeId: '00000000-0000-0000-0000-000000000101', optional: true, setoftype: false, variadic: false } },
			returnTypeId: '00000000-0000-0000-0000-000000000001',
			returnTypemod: 'SetOfType',
			preservesOptionality: true
		}
	]);
	return _.syntax.$expressionify({
		__kind__: $.ExpressionKind.Function,
		__element__: returnType,
		__cardinality__: cardinality,
		__name__: 'std::assert_distinct',
		__args__: positionalArgs,
		__namedargs__: namedArgs
	});
}

function assert(...args) {
	const {
		returnType,
		cardinality,
		args: positionalArgs,
		namedArgs
	} = _.syntax.$resolveOverload('std::assert', args, _.spec, [
		{
			args: [{ typeId: '00000000-0000-0000-0000-000000000109', optional: false, setoftype: false, variadic: false }],
			namedArgs: { message: { typeId: '00000000-0000-0000-0000-000000000101', optional: true, setoftype: false, variadic: false } },
			returnTypeId: '00000000-0000-0000-0000-000000000109'
		}
	]);
	return _.syntax.$expressionify({
		__kind__: $.ExpressionKind.Function,
		__element__: returnType,
		__cardinality__: cardinality,
		__name__: 'std::assert',
		__args__: positionalArgs,
		__namedargs__: namedArgs
	});
}

function len(...args) {
	const {
		returnType,
		cardinality,
		args: positionalArgs,
		namedArgs
	} = _.syntax.$resolveOverload('std::len', args, _.spec, [
		{
			args: [{ typeId: '00000000-0000-0000-0000-000000000101', optional: false, setoftype: false, variadic: false }],
			returnTypeId: '00000000-0000-0000-0000-0000000001ff'
		},
		{
			args: [{ typeId: '00000000-0000-0000-0000-000000000102', optional: false, setoftype: false, variadic: false }],
			returnTypeId: '00000000-0000-0000-0000-0000000001ff'
		},
		{
			args: [{ typeId: 'a6f5468c-c2a6-5852-8f73-57484b1c6831', optional: false, setoftype: false, variadic: false }],
			returnTypeId: '00000000-0000-0000-0000-0000000001ff'
		}
	]);
	return _.syntax.$expressionify({
		__kind__: $.ExpressionKind.Function,
		__element__: returnType,
		__cardinality__: cardinality,
		__name__: 'std::len',
		__args__: positionalArgs,
		__namedargs__: namedArgs
	});
}

function sum(...args) {
	const {
		returnType,
		cardinality,
		args: positionalArgs,
		namedArgs
	} = _.syntax.$resolveOverload('std::sum', args, _.spec, [
		{
			args: [{ typeId: '00000000-0000-0000-0000-000000000110', optional: false, setoftype: true, variadic: false }],
			returnTypeId: '00000000-0000-0000-0000-000000000110'
		},
		{
			args: [{ typeId: '00000000-0000-0000-0000-0000000001ff', optional: false, setoftype: true, variadic: false }],
			returnTypeId: '00000000-0000-0000-0000-0000000001ff'
		},
		{
			args: [{ typeId: '00000000-0000-0000-0000-000000000108', optional: false, setoftype: true, variadic: false }],
			returnTypeId: '00000000-0000-0000-0000-000000000108'
		}
	]);
	return _.syntax.$expressionify({
		__kind__: $.ExpressionKind.Function,
		__element__: returnType,
		__cardinality__: cardinality,
		__name__: 'std::sum',
		__args__: positionalArgs,
		__namedargs__: namedArgs
	});
}

function count(...args) {
	const {
		returnType,
		cardinality,
		args: positionalArgs,
		namedArgs
	} = _.syntax.$resolveOverload('std::count', args, _.spec, [
		{
			args: [{ typeId: '00000000-0000-0000-0000-000000000001', optional: false, setoftype: true, variadic: false }],
			returnTypeId: '00000000-0000-0000-0000-0000000001ff'
		}
	]);
	return _.syntax.$expressionify({
		__kind__: $.ExpressionKind.Function,
		__element__: returnType,
		__cardinality__: cardinality,
		__name__: 'std::count',
		__args__: positionalArgs,
		__namedargs__: namedArgs
	});
}

function random(...args) {
	const {
		returnType,
		cardinality,
		args: positionalArgs,
		namedArgs
	} = _.syntax.$resolveOverload('std::random', args, _.spec, [{ args: [], returnTypeId: '00000000-0000-0000-0000-0000000001ff' }]);
	return _.syntax.$expressionify({
		__kind__: $.ExpressionKind.Function,
		__element__: returnType,
		__cardinality__: cardinality,
		__name__: 'std::random',
		__args__: positionalArgs,
		__namedargs__: namedArgs
	});
}

function min(...args) {
	const {
		returnType,
		cardinality,
		args: positionalArgs,
		namedArgs
	} = _.syntax.$resolveOverload('std::min', args, _.spec, [
		{
			args: [{ typeId: '04976545-1176-5536-8673-c9f7d18d581b', optional: false, setoftype: true, variadic: false }],
			returnTypeId: '04976545-1176-5536-8673-c9f7d18d581b',
			returnTypemod: 'OptionalType',
			preservesOptionality: true
		},
		{
			args: [{ typeId: '48896eaf-b8af-5f80-9073-0884475d6ee5', optional: false, setoftype: true, variadic: false }],
			returnTypeId: '48896eaf-b8af-5f80-9073-0884475d6ee5',
			returnTypemod: 'OptionalType',
			preservesOptionality: true
		},
		{
			args: [{ typeId: '00000000-0000-0000-0000-000000000101', optional: false, setoftype: true, variadic: false }],
			returnTypeId: '00000000-0000-0000-0000-000000000101',
			returnTypemod: 'OptionalType',
			preservesOptionality: true
		},
		{
			args: [{ typeId: '00000000-0000-0000-0000-00000000010a', optional: false, setoftype: true, variadic: false }],
			returnTypeId: '00000000-0000-0000-0000-00000000010a',
			returnTypemod: 'OptionalType',
			preservesOptionality: true
		},
		{
			args: [{ typeId: '00000000-0000-0000-0000-00000000010e', optional: false, setoftype: true, variadic: false }],
			returnTypeId: '00000000-0000-0000-0000-00000000010e',
			returnTypemod: 'OptionalType',
			preservesOptionality: true
		},
		{
			args: [{ typeId: '00000000-0000-0000-0000-00000000010c', optional: false, setoftype: true, variadic: false }],
			returnTypeId: '00000000-0000-0000-0000-00000000010c',
			returnTypemod: 'OptionalType',
			preservesOptionality: true
		},
		{
			args: [{ typeId: '00000000-0000-0000-0000-00000000010d', optional: false, setoftype: true, variadic: false }],
			returnTypeId: '00000000-0000-0000-0000-00000000010d',
			returnTypemod: 'OptionalType',
			preservesOptionality: true
		},
		{
			args: [{ typeId: '00000000-0000-0000-0000-000000000112', optional: false, setoftype: true, variadic: false }],
			returnTypeId: '00000000-0000-0000-0000-000000000112',
			returnTypemod: 'OptionalType',
			preservesOptionality: true
		},
		{
			args: [{ typeId: '3a39c464-a115-5b5e-8968-fb30b2c6a7a1', optional: false, setoftype: true, variadic: false }],
			returnTypeId: '3a39c464-a115-5b5e-8968-fb30b2c6a7a1',
			returnTypemod: 'OptionalType',
			preservesOptionality: true
		},
		{
			args: [{ typeId: '80d4b62c-e31c-51c6-b994-afaae5b6eff6', optional: false, setoftype: true, variadic: false }],
			returnTypeId: '80d4b62c-e31c-51c6-b994-afaae5b6eff6',
			returnTypemod: 'OptionalType',
			preservesOptionality: true
		},
		{
			args: [{ typeId: 'd9d5e4a4-d545-5a03-a9da-571d8807619f', optional: false, setoftype: true, variadic: false }],
			returnTypeId: 'd9d5e4a4-d545-5a03-a9da-571d8807619f',
			returnTypemod: 'OptionalType',
			preservesOptionality: true
		},
		{
			args: [{ typeId: '2417884d-4995-5a45-8c61-614adab347a7', optional: false, setoftype: true, variadic: false }],
			returnTypeId: '2417884d-4995-5a45-8c61-614adab347a7',
			returnTypemod: 'OptionalType',
			preservesOptionality: true
		},
		{
			args: [{ typeId: 'fd652c7f-67e3-516f-b508-c8e6f227311e', optional: false, setoftype: true, variadic: false }],
			returnTypeId: 'fd652c7f-67e3-516f-b508-c8e6f227311e',
			returnTypemod: 'OptionalType',
			preservesOptionality: true
		},
		{
			args: [{ typeId: '00000000-0000-0000-0000-00000000010b', optional: false, setoftype: true, variadic: false }],
			returnTypeId: '00000000-0000-0000-0000-00000000010b',
			returnTypemod: 'OptionalType',
			preservesOptionality: true
		},
		{
			args: [{ typeId: '00000000-0000-0000-0000-000000000111', optional: false, setoftype: true, variadic: false }],
			returnTypeId: '00000000-0000-0000-0000-000000000111',
			returnTypemod: 'OptionalType',
			preservesOptionality: true
		},
		{
			args: [{ typeId: '00000000-0000-0000-0000-000000000001', optional: false, setoftype: true, variadic: false }],
			returnTypeId: '00000000-0000-0000-0000-000000000001',
			returnTypemod: 'OptionalType',
			preservesOptionality: true
		}
	]);
	return _.syntax.$expressionify({
		__kind__: $.ExpressionKind.Function,
		__element__: returnType,
		__cardinality__: cardinality,
		__name__: 'std::min',
		__args__: positionalArgs,
		__namedargs__: namedArgs
	});
}

function max(...args) {
	const {
		returnType,
		cardinality,
		args: positionalArgs,
		namedArgs
	} = _.syntax.$resolveOverload('std::max', args, _.spec, [
		{
			args: [{ typeId: '04976545-1176-5536-8673-c9f7d18d581b', optional: false, setoftype: true, variadic: false }],
			returnTypeId: '04976545-1176-5536-8673-c9f7d18d581b',
			returnTypemod: 'OptionalType',
			preservesOptionality: true
		},
		{
			args: [{ typeId: '48896eaf-b8af-5f80-9073-0884475d6ee5', optional: false, setoftype: true, variadic: false }],
			returnTypeId: '48896eaf-b8af-5f80-9073-0884475d6ee5',
			returnTypemod: 'OptionalType',
			preservesOptionality: true
		},
		{
			args: [{ typeId: '00000000-0000-0000-0000-000000000101', optional: false, setoftype: true, variadic: false }],
			returnTypeId: '00000000-0000-0000-0000-000000000101',
			returnTypemod: 'OptionalType',
			preservesOptionality: true
		},
		{
			args: [{ typeId: '00000000-0000-0000-0000-00000000010a', optional: false, setoftype: true, variadic: false }],
			returnTypeId: '00000000-0000-0000-0000-00000000010a',
			returnTypemod: 'OptionalType',
			preservesOptionality: true
		},
		{
			args: [{ typeId: '00000000-0000-0000-0000-00000000010e', optional: false, setoftype: true, variadic: false }],
			returnTypeId: '00000000-0000-0000-0000-00000000010e',
			returnTypemod: 'OptionalType',
			preservesOptionality: true
		},
		{
			args: [{ typeId: '00000000-0000-0000-0000-00000000010c', optional: false, setoftype: true, variadic: false }],
			returnTypeId: '00000000-0000-0000-0000-00000000010c',
			returnTypemod: 'OptionalType',
			preservesOptionality: true
		},
		{
			args: [{ typeId: '00000000-0000-0000-0000-00000000010d', optional: false, setoftype: true, variadic: false }],
			returnTypeId: '00000000-0000-0000-0000-00000000010d',
			returnTypemod: 'OptionalType',
			preservesOptionality: true
		},
		{
			args: [{ typeId: '00000000-0000-0000-0000-000000000112', optional: false, setoftype: true, variadic: false }],
			returnTypeId: '00000000-0000-0000-0000-000000000112',
			returnTypemod: 'OptionalType',
			preservesOptionality: true
		},
		{
			args: [{ typeId: '3a39c464-a115-5b5e-8968-fb30b2c6a7a1', optional: false, setoftype: true, variadic: false }],
			returnTypeId: '3a39c464-a115-5b5e-8968-fb30b2c6a7a1',
			returnTypemod: 'OptionalType',
			preservesOptionality: true
		},
		{
			args: [{ typeId: '80d4b62c-e31c-51c6-b994-afaae5b6eff6', optional: false, setoftype: true, variadic: false }],
			returnTypeId: '80d4b62c-e31c-51c6-b994-afaae5b6eff6',
			returnTypemod: 'OptionalType',
			preservesOptionality: true
		},
		{
			args: [{ typeId: 'd9d5e4a4-d545-5a03-a9da-571d8807619f', optional: false, setoftype: true, variadic: false }],
			returnTypeId: 'd9d5e4a4-d545-5a03-a9da-571d8807619f',
			returnTypemod: 'OptionalType',
			preservesOptionality: true
		},
		{
			args: [{ typeId: '2417884d-4995-5a45-8c61-614adab347a7', optional: false, setoftype: true, variadic: false }],
			returnTypeId: '2417884d-4995-5a45-8c61-614adab347a7',
			returnTypemod: 'OptionalType',
			preservesOptionality: true
		},
		{
			args: [{ typeId: 'fd652c7f-67e3-516f-b508-c8e6f227311e', optional: false, setoftype: true, variadic: false }],
			returnTypeId: 'fd652c7f-67e3-516f-b508-c8e6f227311e',
			returnTypemod: 'OptionalType',
			preservesOptionality: true
		},
		{
			args: [{ typeId: '00000000-0000-0000-0000-00000000010b', optional: false, setoftype: true, variadic: false }],
			returnTypeId: '00000000-0000-0000-0000-00000000010b',
			returnTypemod: 'OptionalType',
			preservesOptionality: true
		},
		{
			args: [{ typeId: '00000000-0000-0000-0000-000000000111', optional: false, setoftype: true, variadic: false }],
			returnTypeId: '00000000-0000-0000-0000-000000000111',
			returnTypemod: 'OptionalType',
			preservesOptionality: true
		},
		{
			args: [{ typeId: '00000000-0000-0000-0000-000000000001', optional: false, setoftype: true, variadic: false }],
			returnTypeId: '00000000-0000-0000-0000-000000000001',
			returnTypemod: 'OptionalType',
			preservesOptionality: true
		}
	]);
	return _.syntax.$expressionify({
		__kind__: $.ExpressionKind.Function,
		__element__: returnType,
		__cardinality__: cardinality,
		__name__: 'std::max',
		__args__: positionalArgs,
		__namedargs__: namedArgs
	});
}

function all(...args) {
	const {
		returnType,
		cardinality,
		args: positionalArgs,
		namedArgs
	} = _.syntax.$resolveOverload('std::all', args, _.spec, [
		{
			args: [{ typeId: '00000000-0000-0000-0000-000000000109', optional: false, setoftype: true, variadic: false }],
			returnTypeId: '00000000-0000-0000-0000-000000000109'
		}
	]);
	return _.syntax.$expressionify({
		__kind__: $.ExpressionKind.Function,
		__element__: returnType,
		__cardinality__: cardinality,
		__name__: 'std::all',
		__args__: positionalArgs,
		__namedargs__: namedArgs
	});
}

function any(...args) {
	const {
		returnType,
		cardinality,
		args: positionalArgs,
		namedArgs
	} = _.syntax.$resolveOverload('std::any', args, _.spec, [
		{
			args: [{ typeId: '00000000-0000-0000-0000-000000000109', optional: false, setoftype: true, variadic: false }],
			returnTypeId: '00000000-0000-0000-0000-000000000109'
		}
	]);
	return _.syntax.$expressionify({
		__kind__: $.ExpressionKind.Function,
		__element__: returnType,
		__cardinality__: cardinality,
		__name__: 'std::any',
		__args__: positionalArgs,
		__namedargs__: namedArgs
	});
}

function enumerate(...args) {
	const {
		returnType,
		cardinality,
		args: positionalArgs,
		namedArgs
	} = _.syntax.$resolveOverload('std::enumerate', args, _.spec, [
		{
			args: [{ typeId: '00000000-0000-0000-0000-000000000001', optional: false, setoftype: true, variadic: false }],
			returnTypeId: 'e34cf562-ee0c-58d3-a1ee-ff9fbb35bfc3',
			returnTypemod: 'SetOfType',
			preservesOptionality: true
		}
	]);
	return _.syntax.$expressionify({
		__kind__: $.ExpressionKind.Function,
		__element__: returnType,
		__cardinality__: cardinality,
		__name__: 'std::enumerate',
		__args__: positionalArgs,
		__namedargs__: namedArgs
	});
}

function round(...args) {
	const {
		returnType,
		cardinality,
		args: positionalArgs,
		namedArgs
	} = _.syntax.$resolveOverload('std::round', args, _.spec, [
		{
			args: [{ typeId: '00000000-0000-0000-0000-0000000001ff', optional: false, setoftype: false, variadic: false }],
			returnTypeId: '00000000-0000-0000-0000-0000000001ff'
		},
		{
			args: [{ typeId: '00000000-0000-0000-0000-000000000110', optional: false, setoftype: false, variadic: false }],
			returnTypeId: '00000000-0000-0000-0000-000000000110'
		},
		{
			args: [{ typeId: '00000000-0000-0000-0000-000000000108', optional: false, setoftype: false, variadic: false }],
			returnTypeId: '00000000-0000-0000-0000-000000000108'
		},
		{
			args: [
				{ typeId: '00000000-0000-0000-0000-000000000108', optional: false, setoftype: false, variadic: false },
				{ typeId: '00000000-0000-0000-0000-0000000001ff', optional: false, setoftype: false, variadic: false }
			],
			returnTypeId: '00000000-0000-0000-0000-000000000108'
		}
	]);
	return _.syntax.$expressionify({
		__kind__: $.ExpressionKind.Function,
		__element__: returnType,
		__cardinality__: cardinality,
		__name__: 'std::round',
		__args__: positionalArgs,
		__namedargs__: namedArgs
	});
}

function contains(...args) {
	const {
		returnType,
		cardinality,
		args: positionalArgs,
		namedArgs
	} = _.syntax.$resolveOverload('std::contains', args, _.spec, [
		{
			args: [
				{ typeId: '00000000-0000-0000-0000-000000000101', optional: false, setoftype: false, variadic: false },
				{ typeId: '00000000-0000-0000-0000-000000000101', optional: false, setoftype: false, variadic: false }
			],
			returnTypeId: '00000000-0000-0000-0000-000000000109'
		},
		{
			args: [
				{ typeId: '00000000-0000-0000-0000-000000000102', optional: false, setoftype: false, variadic: false },
				{ typeId: '00000000-0000-0000-0000-000000000102', optional: false, setoftype: false, variadic: false }
			],
			returnTypeId: '00000000-0000-0000-0000-000000000109'
		},
		{
			args: [
				{ typeId: '00000000-0000-0000-0000-00000000010f', optional: false, setoftype: false, variadic: false },
				{ typeId: '00000000-0000-0000-0000-00000000010f', optional: false, setoftype: false, variadic: false }
			],
			returnTypeId: '00000000-0000-0000-0000-000000000109'
		},
		{
			args: [
				{ typeId: '49748e47-8d91-5269-9a34-2e8ca194e0f2', optional: false, setoftype: false, variadic: false },
				{ typeId: '49748e47-8d91-5269-9a34-2e8ca194e0f2', optional: false, setoftype: false, variadic: false }
			],
			returnTypeId: '00000000-0000-0000-0000-000000000109'
		},
		{
			args: [
				{ typeId: '49748e47-8d91-5269-9a34-2e8ca194e0f2', optional: false, setoftype: false, variadic: false },
				{ typeId: '581b0325-a044-58d4-aa37-3a85ea671313', optional: false, setoftype: false, variadic: false }
			],
			returnTypeId: '00000000-0000-0000-0000-000000000109'
		},
		{
			args: [
				{ typeId: 'c3231f27-c8a1-5a0c-9830-c71206020eac', optional: false, setoftype: false, variadic: false },
				{ typeId: 'c3231f27-c8a1-5a0c-9830-c71206020eac', optional: false, setoftype: false, variadic: false }
			],
			returnTypeId: '00000000-0000-0000-0000-000000000109'
		},
		{
			args: [
				{ typeId: 'c3231f27-c8a1-5a0c-9830-c71206020eac', optional: false, setoftype: false, variadic: false },
				{ typeId: '49748e47-8d91-5269-9a34-2e8ca194e0f2', optional: false, setoftype: false, variadic: false }
			],
			returnTypeId: '00000000-0000-0000-0000-000000000109'
		},
		{
			args: [
				{ typeId: 'c3231f27-c8a1-5a0c-9830-c71206020eac', optional: false, setoftype: false, variadic: false },
				{ typeId: '581b0325-a044-58d4-aa37-3a85ea671313', optional: false, setoftype: false, variadic: false }
			],
			returnTypeId: '00000000-0000-0000-0000-000000000109'
		},
		{
			args: [
				{ typeId: '1e76d7c5-b67c-542c-bc8f-238b93ff1726', optional: false, setoftype: false, variadic: false },
				{ typeId: '00000000-0000-0000-0000-00000000010c', optional: false, setoftype: false, variadic: false }
			],
			returnTypeId: '00000000-0000-0000-0000-000000000109'
		},
		{
			args: [
				{ typeId: 'e294f13d-34ee-529f-b7f8-7c3e2fd17e6e', optional: false, setoftype: false, variadic: false },
				{ typeId: '00000000-0000-0000-0000-00000000010c', optional: false, setoftype: false, variadic: false }
			],
			returnTypeId: '00000000-0000-0000-0000-000000000109'
		},
		{
			args: [
				{ typeId: 'a6f5468c-c2a6-5852-8f73-57484b1c6831', optional: false, setoftype: false, variadic: false },
				{ typeId: '00000000-0000-0000-0000-000000000001', optional: false, setoftype: false, variadic: false }
			],
			returnTypeId: '00000000-0000-0000-0000-000000000109'
		}
	]);
	return _.syntax.$expressionify({
		__kind__: $.ExpressionKind.Function,
		__element__: returnType,
		__cardinality__: cardinality,
		__name__: 'std::contains',
		__args__: positionalArgs,
		__namedargs__: namedArgs
	});
}

function array_get(...args) {
	const {
		returnType,
		cardinality,
		args: positionalArgs,
		namedArgs
	} = _.syntax.$resolveOverload('std::array_get', args, _.spec, [
		{
			args: [
				{ typeId: 'a6f5468c-c2a6-5852-8f73-57484b1c6831', optional: false, setoftype: false, variadic: false },
				{ typeId: '00000000-0000-0000-0000-0000000001ff', optional: false, setoftype: false, variadic: false }
			],
			namedArgs: { default: { typeId: '00000000-0000-0000-0000-000000000001', optional: true, setoftype: false, variadic: false } },
			returnTypeId: '00000000-0000-0000-0000-000000000001',
			returnTypemod: 'OptionalType'
		}
	]);
	return _.syntax.$expressionify({
		__kind__: $.ExpressionKind.Function,
		__element__: returnType,
		__cardinality__: cardinality,
		__name__: 'std::array_get',
		__args__: positionalArgs,
		__namedargs__: namedArgs
	});
}

function find(...args) {
	const {
		returnType,
		cardinality,
		args: positionalArgs,
		namedArgs
	} = _.syntax.$resolveOverload('std::find', args, _.spec, [
		{
			args: [
				{ typeId: '00000000-0000-0000-0000-000000000101', optional: false, setoftype: false, variadic: false },
				{ typeId: '00000000-0000-0000-0000-000000000101', optional: false, setoftype: false, variadic: false }
			],
			returnTypeId: '00000000-0000-0000-0000-0000000001ff'
		},
		{
			args: [
				{ typeId: '00000000-0000-0000-0000-000000000102', optional: false, setoftype: false, variadic: false },
				{ typeId: '00000000-0000-0000-0000-000000000102', optional: false, setoftype: false, variadic: false }
			],
			returnTypeId: '00000000-0000-0000-0000-0000000001ff'
		},
		{
			args: [
				{ typeId: 'a6f5468c-c2a6-5852-8f73-57484b1c6831', optional: false, setoftype: false, variadic: false },
				{ typeId: '00000000-0000-0000-0000-000000000001', optional: false, setoftype: false, variadic: false },
				{ typeId: '00000000-0000-0000-0000-0000000001ff', optional: true, setoftype: false, variadic: false }
			],
			returnTypeId: '00000000-0000-0000-0000-0000000001ff'
		}
	]);
	return _.syntax.$expressionify({
		__kind__: $.ExpressionKind.Function,
		__element__: returnType,
		__cardinality__: cardinality,
		__name__: 'std::find',
		__args__: positionalArgs,
		__namedargs__: namedArgs
	});
}

function bit_and(...args) {
	const {
		returnType,
		cardinality,
		args: positionalArgs,
		namedArgs
	} = _.syntax.$resolveOverload('std::bit_and', args, _.spec, [
		{
			args: [
				{ typeId: '00000000-0000-0000-0000-0000000001ff', optional: false, setoftype: false, variadic: false },
				{ typeId: '00000000-0000-0000-0000-0000000001ff', optional: false, setoftype: false, variadic: false }
			],
			returnTypeId: '00000000-0000-0000-0000-0000000001ff'
		}
	]);
	return _.syntax.$expressionify({
		__kind__: $.ExpressionKind.Function,
		__element__: returnType,
		__cardinality__: cardinality,
		__name__: 'std::bit_and',
		__args__: positionalArgs,
		__namedargs__: namedArgs
	});
}

function bit_or(...args) {
	const {
		returnType,
		cardinality,
		args: positionalArgs,
		namedArgs
	} = _.syntax.$resolveOverload('std::bit_or', args, _.spec, [
		{
			args: [
				{ typeId: '00000000-0000-0000-0000-0000000001ff', optional: false, setoftype: false, variadic: false },
				{ typeId: '00000000-0000-0000-0000-0000000001ff', optional: false, setoftype: false, variadic: false }
			],
			returnTypeId: '00000000-0000-0000-0000-0000000001ff'
		}
	]);
	return _.syntax.$expressionify({
		__kind__: $.ExpressionKind.Function,
		__element__: returnType,
		__cardinality__: cardinality,
		__name__: 'std::bit_or',
		__args__: positionalArgs,
		__namedargs__: namedArgs
	});
}

function bit_xor(...args) {
	const {
		returnType,
		cardinality,
		args: positionalArgs,
		namedArgs
	} = _.syntax.$resolveOverload('std::bit_xor', args, _.spec, [
		{
			args: [
				{ typeId: '00000000-0000-0000-0000-0000000001ff', optional: false, setoftype: false, variadic: false },
				{ typeId: '00000000-0000-0000-0000-0000000001ff', optional: false, setoftype: false, variadic: false }
			],
			returnTypeId: '00000000-0000-0000-0000-0000000001ff'
		}
	]);
	return _.syntax.$expressionify({
		__kind__: $.ExpressionKind.Function,
		__element__: returnType,
		__cardinality__: cardinality,
		__name__: 'std::bit_xor',
		__args__: positionalArgs,
		__namedargs__: namedArgs
	});
}

function bit_not(...args) {
	const {
		returnType,
		cardinality,
		args: positionalArgs,
		namedArgs
	} = _.syntax.$resolveOverload('std::bit_not', args, _.spec, [
		{
			args: [{ typeId: '00000000-0000-0000-0000-0000000001ff', optional: false, setoftype: false, variadic: false }],
			returnTypeId: '00000000-0000-0000-0000-0000000001ff'
		}
	]);
	return _.syntax.$expressionify({
		__kind__: $.ExpressionKind.Function,
		__element__: returnType,
		__cardinality__: cardinality,
		__name__: 'std::bit_not',
		__args__: positionalArgs,
		__namedargs__: namedArgs
	});
}

function bit_rshift(...args) {
	const {
		returnType,
		cardinality,
		args: positionalArgs,
		namedArgs
	} = _.syntax.$resolveOverload('std::bit_rshift', args, _.spec, [
		{
			args: [
				{ typeId: '00000000-0000-0000-0000-0000000001ff', optional: false, setoftype: false, variadic: false },
				{ typeId: '00000000-0000-0000-0000-0000000001ff', optional: false, setoftype: false, variadic: false }
			],
			returnTypeId: '00000000-0000-0000-0000-0000000001ff'
		}
	]);
	return _.syntax.$expressionify({
		__kind__: $.ExpressionKind.Function,
		__element__: returnType,
		__cardinality__: cardinality,
		__name__: 'std::bit_rshift',
		__args__: positionalArgs,
		__namedargs__: namedArgs
	});
}

function bit_lshift(...args) {
	const {
		returnType,
		cardinality,
		args: positionalArgs,
		namedArgs
	} = _.syntax.$resolveOverload('std::bit_lshift', args, _.spec, [
		{
			args: [
				{ typeId: '00000000-0000-0000-0000-0000000001ff', optional: false, setoftype: false, variadic: false },
				{ typeId: '00000000-0000-0000-0000-0000000001ff', optional: false, setoftype: false, variadic: false }
			],
			returnTypeId: '00000000-0000-0000-0000-0000000001ff'
		}
	]);
	return _.syntax.$expressionify({
		__kind__: $.ExpressionKind.Function,
		__element__: returnType,
		__cardinality__: cardinality,
		__name__: 'std::bit_lshift',
		__args__: positionalArgs,
		__namedargs__: namedArgs
	});
}

function array_agg(...args) {
	const {
		returnType,
		cardinality,
		args: positionalArgs,
		namedArgs
	} = _.syntax.$resolveOverload('std::array_agg', args, _.spec, [
		{
			args: [{ typeId: '00000000-0000-0000-0000-000000000001', optional: false, setoftype: true, variadic: false }],
			returnTypeId: 'a6f5468c-c2a6-5852-8f73-57484b1c6831'
		}
	]);
	return _.syntax.$expressionify({
		__kind__: $.ExpressionKind.Function,
		__element__: returnType,
		__cardinality__: cardinality,
		__name__: 'std::array_agg',
		__args__: positionalArgs,
		__namedargs__: namedArgs
	});
}

function array_unpack(...args) {
	const {
		returnType,
		cardinality,
		args: positionalArgs,
		namedArgs
	} = _.syntax.$resolveOverload('std::array_unpack', args, _.spec, [
		{
			args: [{ typeId: 'a6f5468c-c2a6-5852-8f73-57484b1c6831', optional: false, setoftype: false, variadic: false }],
			returnTypeId: '00000000-0000-0000-0000-000000000001',
			returnTypemod: 'SetOfType'
		}
	]);
	return _.syntax.$expressionify({
		__kind__: $.ExpressionKind.Function,
		__element__: returnType,
		__cardinality__: cardinality,
		__name__: 'std::array_unpack',
		__args__: positionalArgs,
		__namedargs__: namedArgs
	});
}

function array_fill(...args) {
	const {
		returnType,
		cardinality,
		args: positionalArgs,
		namedArgs
	} = _.syntax.$resolveOverload('std::array_fill', args, _.spec, [
		{
			args: [
				{ typeId: '00000000-0000-0000-0000-000000000001', optional: false, setoftype: false, variadic: false },
				{ typeId: '00000000-0000-0000-0000-0000000001ff', optional: false, setoftype: false, variadic: false }
			],
			returnTypeId: 'a6f5468c-c2a6-5852-8f73-57484b1c6831'
		}
	]);
	return _.syntax.$expressionify({
		__kind__: $.ExpressionKind.Function,
		__element__: returnType,
		__cardinality__: cardinality,
		__name__: 'std::array_fill',
		__args__: positionalArgs,
		__namedargs__: namedArgs
	});
}

function array_replace(...args) {
	const {
		returnType,
		cardinality,
		args: positionalArgs,
		namedArgs
	} = _.syntax.$resolveOverload('std::array_replace', args, _.spec, [
		{
			args: [
				{ typeId: 'a6f5468c-c2a6-5852-8f73-57484b1c6831', optional: false, setoftype: false, variadic: false },
				{ typeId: '00000000-0000-0000-0000-000000000001', optional: false, setoftype: false, variadic: false },
				{ typeId: '00000000-0000-0000-0000-000000000001', optional: false, setoftype: false, variadic: false }
			],
			returnTypeId: 'a6f5468c-c2a6-5852-8f73-57484b1c6831'
		}
	]);
	return _.syntax.$expressionify({
		__kind__: $.ExpressionKind.Function,
		__element__: returnType,
		__cardinality__: cardinality,
		__name__: 'std::array_replace',
		__args__: positionalArgs,
		__namedargs__: namedArgs
	});
}

function array_join(...args) {
	const {
		returnType,
		cardinality,
		args: positionalArgs,
		namedArgs
	} = _.syntax.$resolveOverload('std::array_join', args, _.spec, [
		{
			args: [
				{ typeId: 'bb221d39-09f1-507e-8851-62075bb61823', optional: false, setoftype: false, variadic: false },
				{ typeId: '00000000-0000-0000-0000-000000000101', optional: false, setoftype: false, variadic: false }
			],
			returnTypeId: '00000000-0000-0000-0000-000000000101'
		},
		{
			args: [
				{ typeId: '48aa45ef-4d93-5fbd-bfb5-81bf67b49eab', optional: false, setoftype: false, variadic: false },
				{ typeId: '00000000-0000-0000-0000-000000000102', optional: false, setoftype: false, variadic: false }
			],
			returnTypeId: '00000000-0000-0000-0000-000000000102'
		}
	]);
	return _.syntax.$expressionify({
		__kind__: $.ExpressionKind.Function,
		__element__: returnType,
		__cardinality__: cardinality,
		__name__: 'std::array_join',
		__args__: positionalArgs,
		__namedargs__: namedArgs
	});
}

function bytes_get_bit(...args) {
	const {
		returnType,
		cardinality,
		args: positionalArgs,
		namedArgs
	} = _.syntax.$resolveOverload('std::bytes_get_bit', args, _.spec, [
		{
			args: [
				{ typeId: '00000000-0000-0000-0000-000000000102', optional: false, setoftype: false, variadic: false },
				{ typeId: '00000000-0000-0000-0000-0000000001ff', optional: false, setoftype: false, variadic: false }
			],
			returnTypeId: '00000000-0000-0000-0000-0000000001ff'
		}
	]);
	return _.syntax.$expressionify({
		__kind__: $.ExpressionKind.Function,
		__element__: returnType,
		__cardinality__: cardinality,
		__name__: 'std::bytes_get_bit',
		__args__: positionalArgs,
		__namedargs__: namedArgs
	});
}

function datetime_current(...args) {
	const {
		returnType,
		cardinality,
		args: positionalArgs,
		namedArgs
	} = _.syntax.$resolveOverload('std::datetime_current', args, _.spec, [{ args: [], returnTypeId: '00000000-0000-0000-0000-00000000010a' }]);
	return _.syntax.$expressionify({
		__kind__: $.ExpressionKind.Function,
		__element__: returnType,
		__cardinality__: cardinality,
		__name__: 'std::datetime_current',
		__args__: positionalArgs,
		__namedargs__: namedArgs
	});
}

function datetime_of_transaction(...args) {
	const {
		returnType,
		cardinality,
		args: positionalArgs,
		namedArgs
	} = _.syntax.$resolveOverload('std::datetime_of_transaction', args, _.spec, [{ args: [], returnTypeId: '00000000-0000-0000-0000-00000000010a' }]);
	return _.syntax.$expressionify({
		__kind__: $.ExpressionKind.Function,
		__element__: returnType,
		__cardinality__: cardinality,
		__name__: 'std::datetime_of_transaction',
		__args__: positionalArgs,
		__namedargs__: namedArgs
	});
}

function datetime_of_statement(...args) {
	const {
		returnType,
		cardinality,
		args: positionalArgs,
		namedArgs
	} = _.syntax.$resolveOverload('std::datetime_of_statement', args, _.spec, [{ args: [], returnTypeId: '00000000-0000-0000-0000-00000000010a' }]);
	return _.syntax.$expressionify({
		__kind__: $.ExpressionKind.Function,
		__element__: returnType,
		__cardinality__: cardinality,
		__name__: 'std::datetime_of_statement',
		__args__: positionalArgs,
		__namedargs__: namedArgs
	});
}

function datetime_get(...args) {
	const {
		returnType,
		cardinality,
		args: positionalArgs,
		namedArgs
	} = _.syntax.$resolveOverload('std::datetime_get', args, _.spec, [
		{
			args: [
				{ typeId: '00000000-0000-0000-0000-00000000010a', optional: false, setoftype: false, variadic: false },
				{ typeId: '00000000-0000-0000-0000-000000000101', optional: false, setoftype: false, variadic: false }
			],
			returnTypeId: '00000000-0000-0000-0000-0000000001ff'
		},
		{
			args: [
				{ typeId: '00000000-0000-0000-0000-00000000010b', optional: false, setoftype: false, variadic: false },
				{ typeId: '00000000-0000-0000-0000-000000000101', optional: false, setoftype: false, variadic: false }
			],
			returnTypeId: '00000000-0000-0000-0000-0000000001ff'
		}
	]);
	return _.syntax.$expressionify({
		__kind__: $.ExpressionKind.Function,
		__element__: returnType,
		__cardinality__: cardinality,
		__name__: 'std::datetime_get',
		__args__: positionalArgs,
		__namedargs__: namedArgs
	});
}

function datetime_truncate(...args) {
	const {
		returnType,
		cardinality,
		args: positionalArgs,
		namedArgs
	} = _.syntax.$resolveOverload('std::datetime_truncate', args, _.spec, [
		{
			args: [
				{ typeId: '00000000-0000-0000-0000-00000000010a', optional: false, setoftype: false, variadic: false },
				{ typeId: '00000000-0000-0000-0000-000000000101', optional: false, setoftype: false, variadic: false }
			],
			returnTypeId: '00000000-0000-0000-0000-00000000010a'
		}
	]);
	return _.syntax.$expressionify({
		__kind__: $.ExpressionKind.Function,
		__element__: returnType,
		__cardinality__: cardinality,
		__name__: 'std::datetime_truncate',
		__args__: positionalArgs,
		__namedargs__: namedArgs
	});
}

function duration_get(...args) {
	const {
		returnType,
		cardinality,
		args: positionalArgs,
		namedArgs
	} = _.syntax.$resolveOverload('std::duration_get', args, _.spec, [
		{
			args: [
				{ typeId: '00000000-0000-0000-0000-00000000010e', optional: false, setoftype: false, variadic: false },
				{ typeId: '00000000-0000-0000-0000-000000000101', optional: false, setoftype: false, variadic: false }
			],
			returnTypeId: '00000000-0000-0000-0000-0000000001ff'
		},
		{
			args: [
				{ typeId: '00000000-0000-0000-0000-000000000112', optional: false, setoftype: false, variadic: false },
				{ typeId: '00000000-0000-0000-0000-000000000101', optional: false, setoftype: false, variadic: false }
			],
			returnTypeId: '00000000-0000-0000-0000-0000000001ff'
		},
		{
			args: [
				{ typeId: '00000000-0000-0000-0000-000000000111', optional: false, setoftype: false, variadic: false },
				{ typeId: '00000000-0000-0000-0000-000000000101', optional: false, setoftype: false, variadic: false }
			],
			returnTypeId: '00000000-0000-0000-0000-0000000001ff'
		}
	]);
	return _.syntax.$expressionify({
		__kind__: $.ExpressionKind.Function,
		__element__: returnType,
		__cardinality__: cardinality,
		__name__: 'std::duration_get',
		__args__: positionalArgs,
		__namedargs__: namedArgs
	});
}

function duration_truncate(...args) {
	const {
		returnType,
		cardinality,
		args: positionalArgs,
		namedArgs
	} = _.syntax.$resolveOverload('std::duration_truncate', args, _.spec, [
		{
			args: [
				{ typeId: '00000000-0000-0000-0000-00000000010e', optional: false, setoftype: false, variadic: false },
				{ typeId: '00000000-0000-0000-0000-000000000101', optional: false, setoftype: false, variadic: false }
			],
			returnTypeId: '00000000-0000-0000-0000-00000000010e'
		},
		{
			args: [
				{ typeId: '00000000-0000-0000-0000-000000000112', optional: false, setoftype: false, variadic: false },
				{ typeId: '00000000-0000-0000-0000-000000000101', optional: false, setoftype: false, variadic: false }
			],
			returnTypeId: '00000000-0000-0000-0000-000000000112'
		},
		{
			args: [
				{ typeId: '00000000-0000-0000-0000-000000000111', optional: false, setoftype: false, variadic: false },
				{ typeId: '00000000-0000-0000-0000-000000000101', optional: false, setoftype: false, variadic: false }
			],
			returnTypeId: '00000000-0000-0000-0000-000000000111'
		}
	]);
	return _.syntax.$expressionify({
		__kind__: $.ExpressionKind.Function,
		__element__: returnType,
		__cardinality__: cardinality,
		__name__: 'std::duration_truncate',
		__args__: positionalArgs,
		__namedargs__: namedArgs
	});
}

function duration_to_seconds(...args) {
	const {
		returnType,
		cardinality,
		args: positionalArgs,
		namedArgs
	} = _.syntax.$resolveOverload('std::duration_to_seconds', args, _.spec, [
		{
			args: [{ typeId: '00000000-0000-0000-0000-00000000010e', optional: false, setoftype: false, variadic: false }],
			returnTypeId: '00000000-0000-0000-0000-000000000108'
		}
	]);
	return _.syntax.$expressionify({
		__kind__: $.ExpressionKind.Function,
		__element__: returnType,
		__cardinality__: cardinality,
		__name__: 'std::duration_to_seconds',
		__args__: positionalArgs,
		__namedargs__: namedArgs
	});
}

function json_typeof(...args) {
	const {
		returnType,
		cardinality,
		args: positionalArgs,
		namedArgs
	} = _.syntax.$resolveOverload('std::json_typeof', args, _.spec, [
		{
			args: [{ typeId: '00000000-0000-0000-0000-00000000010f', optional: false, setoftype: false, variadic: false }],
			returnTypeId: '00000000-0000-0000-0000-000000000101'
		}
	]);
	return _.syntax.$expressionify({
		__kind__: $.ExpressionKind.Function,
		__element__: returnType,
		__cardinality__: cardinality,
		__name__: 'std::json_typeof',
		__args__: positionalArgs,
		__namedargs__: namedArgs
	});
}

function json_array_unpack(...args) {
	const {
		returnType,
		cardinality,
		args: positionalArgs,
		namedArgs
	} = _.syntax.$resolveOverload('std::json_array_unpack', args, _.spec, [
		{
			args: [{ typeId: '00000000-0000-0000-0000-00000000010f', optional: false, setoftype: false, variadic: false }],
			returnTypeId: '00000000-0000-0000-0000-00000000010f',
			returnTypemod: 'SetOfType'
		}
	]);
	return _.syntax.$expressionify({
		__kind__: $.ExpressionKind.Function,
		__element__: returnType,
		__cardinality__: cardinality,
		__name__: 'std::json_array_unpack',
		__args__: positionalArgs,
		__namedargs__: namedArgs
	});
}

function json_object_unpack(...args) {
	const {
		returnType,
		cardinality,
		args: positionalArgs,
		namedArgs
	} = _.syntax.$resolveOverload('std::json_object_unpack', args, _.spec, [
		{
			args: [{ typeId: '00000000-0000-0000-0000-00000000010f', optional: false, setoftype: false, variadic: false }],
			returnTypeId: '416fe1a6-d62c-5481-80cd-2102a37b3415',
			returnTypemod: 'SetOfType'
		}
	]);
	return _.syntax.$expressionify({
		__kind__: $.ExpressionKind.Function,
		__element__: returnType,
		__cardinality__: cardinality,
		__name__: 'std::json_object_unpack',
		__args__: positionalArgs,
		__namedargs__: namedArgs
	});
}

function json_object_pack(...args) {
	const {
		returnType,
		cardinality,
		args: positionalArgs,
		namedArgs
	} = _.syntax.$resolveOverload('std::json_object_pack', args, _.spec, [
		{
			args: [{ typeId: '416fe1a6-d62c-5481-80cd-2102a37b3415', optional: false, setoftype: true, variadic: false }],
			returnTypeId: '00000000-0000-0000-0000-00000000010f'
		}
	]);
	return _.syntax.$expressionify({
		__kind__: $.ExpressionKind.Function,
		__element__: returnType,
		__cardinality__: cardinality,
		__name__: 'std::json_object_pack',
		__args__: positionalArgs,
		__namedargs__: namedArgs
	});
}

function json_get(...args) {
	const {
		returnType,
		cardinality,
		args: positionalArgs,
		namedArgs
	} = _.syntax.$resolveOverload('std::json_get', args, _.spec, [
		{
			args: [
				{ typeId: '00000000-0000-0000-0000-00000000010f', optional: false, setoftype: false, variadic: false },
				{ typeId: '00000000-0000-0000-0000-000000000101', optional: false, setoftype: false, variadic: true }
			],
			namedArgs: { default: { typeId: '00000000-0000-0000-0000-00000000010f', optional: true, setoftype: false, variadic: false } },
			returnTypeId: '00000000-0000-0000-0000-00000000010f',
			returnTypemod: 'OptionalType'
		}
	]);
	return _.syntax.$expressionify({
		__kind__: $.ExpressionKind.Function,
		__element__: returnType,
		__cardinality__: cardinality,
		__name__: 'std::json_get',
		__args__: positionalArgs,
		__namedargs__: namedArgs
	});
}

function json_set(...args) {
	const {
		returnType,
		cardinality,
		args: positionalArgs,
		namedArgs
	} = _.syntax.$resolveOverload('std::json_set', args, _.spec, [
		{
			args: [
				{ typeId: '00000000-0000-0000-0000-00000000010f', optional: false, setoftype: false, variadic: false },
				{ typeId: '00000000-0000-0000-0000-000000000101', optional: false, setoftype: false, variadic: true }
			],
			namedArgs: {
				value: { typeId: '00000000-0000-0000-0000-00000000010f', optional: true, setoftype: false, variadic: false },
				create_if_missing: { typeId: '00000000-0000-0000-0000-000000000109', optional: true, setoftype: false, variadic: false },
				empty_treatment: { typeId: '584feb89-c83d-561d-aa78-24e6d779f044', optional: true, setoftype: false, variadic: false }
			},
			returnTypeId: '00000000-0000-0000-0000-00000000010f',
			returnTypemod: 'OptionalType'
		}
	]);
	return _.syntax.$expressionify({
		__kind__: $.ExpressionKind.Function,
		__element__: returnType,
		__cardinality__: cardinality,
		__name__: 'std::json_set',
		__args__: positionalArgs,
		__namedargs__: namedArgs
	});
}

function range_unpack(...args) {
	const {
		returnType,
		cardinality,
		args: positionalArgs,
		namedArgs
	} = _.syntax.$resolveOverload('std::range_unpack', args, _.spec, [
		{
			args: [{ typeId: '356c02b7-20fa-5d27-90fc-aa628dd37c5e', optional: false, setoftype: false, variadic: false }],
			returnTypeId: '00000000-0000-0000-0000-0000000001ff',
			returnTypemod: 'SetOfType'
		},
		{
			args: [{ typeId: '38b58945-dfd2-572c-bf7e-8cadf204a2ec', optional: false, setoftype: false, variadic: false }],
			returnTypeId: '00000000-0000-0000-0000-0000000001ff',
			returnTypemod: 'SetOfType'
		},
		{
			args: [{ typeId: '1e76d7c5-b67c-542c-bc8f-238b93ff1726', optional: false, setoftype: false, variadic: false }],
			returnTypeId: '00000000-0000-0000-0000-00000000010c',
			returnTypemod: 'SetOfType'
		},
		{
			args: [
				{ typeId: '38b58945-dfd2-572c-bf7e-8cadf204a2ec', optional: false, setoftype: false, variadic: false },
				{ typeId: '00000000-0000-0000-0000-0000000001ff', optional: false, setoftype: false, variadic: false }
			],
			returnTypeId: '00000000-0000-0000-0000-0000000001ff',
			returnTypemod: 'SetOfType'
		},
		{
			args: [
				{ typeId: '356c02b7-20fa-5d27-90fc-aa628dd37c5e', optional: false, setoftype: false, variadic: false },
				{ typeId: '00000000-0000-0000-0000-0000000001ff', optional: false, setoftype: false, variadic: false }
			],
			returnTypeId: '00000000-0000-0000-0000-0000000001ff',
			returnTypemod: 'SetOfType'
		},
		{
			args: [
				{ typeId: 'ef0fdfe1-43f9-5954-b804-56e9b7015ffc', optional: false, setoftype: false, variadic: false },
				{ typeId: '00000000-0000-0000-0000-0000000001ff', optional: false, setoftype: false, variadic: false }
			],
			returnTypeId: '00000000-0000-0000-0000-0000000001ff',
			returnTypemod: 'SetOfType'
		},
		{
			args: [
				{ typeId: 'b2f8ab6d-ebca-517d-9f16-086423c5bb9c', optional: false, setoftype: false, variadic: false },
				{ typeId: '00000000-0000-0000-0000-0000000001ff', optional: false, setoftype: false, variadic: false }
			],
			returnTypeId: '00000000-0000-0000-0000-0000000001ff',
			returnTypemod: 'SetOfType'
		},
		{
			args: [
				{ typeId: '10674aaf-8d88-5593-abe9-f7d82be5162b', optional: false, setoftype: false, variadic: false },
				{ typeId: '00000000-0000-0000-0000-00000000010e', optional: false, setoftype: false, variadic: false }
			],
			returnTypeId: '00000000-0000-0000-0000-00000000010a',
			returnTypemod: 'SetOfType'
		},
		{
			args: [
				{ typeId: '1e76d7c5-b67c-542c-bc8f-238b93ff1726', optional: false, setoftype: false, variadic: false },
				{ typeId: '00000000-0000-0000-0000-000000000112', optional: false, setoftype: false, variadic: false }
			],
			returnTypeId: '00000000-0000-0000-0000-00000000010c',
			returnTypemod: 'SetOfType'
		},
		{
			args: [
				{ typeId: 'c61dd200-697a-5b70-9ff0-6c623a700c14', optional: false, setoftype: false, variadic: false },
				{ typeId: '00000000-0000-0000-0000-000000000108', optional: false, setoftype: false, variadic: false }
			],
			returnTypeId: '00000000-0000-0000-0000-000000000108',
			returnTypemod: 'SetOfType'
		},
		{
			args: [
				{ typeId: 'c4441320-c6b5-5f6a-95e4-0dd4aad4e49f', optional: false, setoftype: false, variadic: false },
				{ typeId: '00000000-0000-0000-0000-000000000111', optional: false, setoftype: false, variadic: false }
			],
			returnTypeId: '00000000-0000-0000-0000-00000000010b',
			returnTypemod: 'SetOfType'
		}
	]);
	return _.syntax.$expressionify({
		__kind__: $.ExpressionKind.Function,
		__element__: returnType,
		__cardinality__: cardinality,
		__name__: 'std::range_unpack',
		__args__: positionalArgs,
		__namedargs__: namedArgs
	});
}

function re_match(...args) {
	const {
		returnType,
		cardinality,
		args: positionalArgs,
		namedArgs
	} = _.syntax.$resolveOverload('std::re_match', args, _.spec, [
		{
			args: [
				{ typeId: '00000000-0000-0000-0000-000000000101', optional: false, setoftype: false, variadic: false },
				{ typeId: '00000000-0000-0000-0000-000000000101', optional: false, setoftype: false, variadic: false }
			],
			returnTypeId: 'bb221d39-09f1-507e-8851-62075bb61823'
		}
	]);
	return _.syntax.$expressionify({
		__kind__: $.ExpressionKind.Function,
		__element__: returnType,
		__cardinality__: cardinality,
		__name__: 'std::re_match',
		__args__: positionalArgs,
		__namedargs__: namedArgs
	});
}

function re_match_all(...args) {
	const {
		returnType,
		cardinality,
		args: positionalArgs,
		namedArgs
	} = _.syntax.$resolveOverload('std::re_match_all', args, _.spec, [
		{
			args: [
				{ typeId: '00000000-0000-0000-0000-000000000101', optional: false, setoftype: false, variadic: false },
				{ typeId: '00000000-0000-0000-0000-000000000101', optional: false, setoftype: false, variadic: false }
			],
			returnTypeId: 'bb221d39-09f1-507e-8851-62075bb61823',
			returnTypemod: 'SetOfType'
		}
	]);
	return _.syntax.$expressionify({
		__kind__: $.ExpressionKind.Function,
		__element__: returnType,
		__cardinality__: cardinality,
		__name__: 'std::re_match_all',
		__args__: positionalArgs,
		__namedargs__: namedArgs
	});
}

function re_test(...args) {
	const {
		returnType,
		cardinality,
		args: positionalArgs,
		namedArgs
	} = _.syntax.$resolveOverload('std::re_test', args, _.spec, [
		{
			args: [
				{ typeId: '00000000-0000-0000-0000-000000000101', optional: false, setoftype: false, variadic: false },
				{ typeId: '00000000-0000-0000-0000-000000000101', optional: false, setoftype: false, variadic: false }
			],
			returnTypeId: '00000000-0000-0000-0000-000000000109'
		}
	]);
	return _.syntax.$expressionify({
		__kind__: $.ExpressionKind.Function,
		__element__: returnType,
		__cardinality__: cardinality,
		__name__: 'std::re_test',
		__args__: positionalArgs,
		__namedargs__: namedArgs
	});
}

function re_replace(...args) {
	const {
		returnType,
		cardinality,
		args: positionalArgs,
		namedArgs
	} = _.syntax.$resolveOverload('std::re_replace', args, _.spec, [
		{
			args: [
				{ typeId: '00000000-0000-0000-0000-000000000101', optional: false, setoftype: false, variadic: false },
				{ typeId: '00000000-0000-0000-0000-000000000101', optional: false, setoftype: false, variadic: false },
				{ typeId: '00000000-0000-0000-0000-000000000101', optional: false, setoftype: false, variadic: false }
			],
			namedArgs: { flags: { typeId: '00000000-0000-0000-0000-000000000101', optional: true, setoftype: false, variadic: false } },
			returnTypeId: '00000000-0000-0000-0000-000000000101'
		}
	]);
	return _.syntax.$expressionify({
		__kind__: $.ExpressionKind.Function,
		__element__: returnType,
		__cardinality__: cardinality,
		__name__: 'std::re_replace',
		__args__: positionalArgs,
		__namedargs__: namedArgs
	});
}

function str_repeat(...args) {
	const {
		returnType,
		cardinality,
		args: positionalArgs,
		namedArgs
	} = _.syntax.$resolveOverload('std::str_repeat', args, _.spec, [
		{
			args: [
				{ typeId: '00000000-0000-0000-0000-000000000101', optional: false, setoftype: false, variadic: false },
				{ typeId: '00000000-0000-0000-0000-0000000001ff', optional: false, setoftype: false, variadic: false }
			],
			returnTypeId: '00000000-0000-0000-0000-000000000101'
		}
	]);
	return _.syntax.$expressionify({
		__kind__: $.ExpressionKind.Function,
		__element__: returnType,
		__cardinality__: cardinality,
		__name__: 'std::str_repeat',
		__args__: positionalArgs,
		__namedargs__: namedArgs
	});
}

function str_lower(...args) {
	const {
		returnType,
		cardinality,
		args: positionalArgs,
		namedArgs
	} = _.syntax.$resolveOverload('std::str_lower', args, _.spec, [
		{
			args: [{ typeId: '00000000-0000-0000-0000-000000000101', optional: false, setoftype: false, variadic: false }],
			returnTypeId: '00000000-0000-0000-0000-000000000101'
		}
	]);
	return _.syntax.$expressionify({
		__kind__: $.ExpressionKind.Function,
		__element__: returnType,
		__cardinality__: cardinality,
		__name__: 'std::str_lower',
		__args__: positionalArgs,
		__namedargs__: namedArgs
	});
}

function str_upper(...args) {
	const {
		returnType,
		cardinality,
		args: positionalArgs,
		namedArgs
	} = _.syntax.$resolveOverload('std::str_upper', args, _.spec, [
		{
			args: [{ typeId: '00000000-0000-0000-0000-000000000101', optional: false, setoftype: false, variadic: false }],
			returnTypeId: '00000000-0000-0000-0000-000000000101'
		}
	]);
	return _.syntax.$expressionify({
		__kind__: $.ExpressionKind.Function,
		__element__: returnType,
		__cardinality__: cardinality,
		__name__: 'std::str_upper',
		__args__: positionalArgs,
		__namedargs__: namedArgs
	});
}

function str_title(...args) {
	const {
		returnType,
		cardinality,
		args: positionalArgs,
		namedArgs
	} = _.syntax.$resolveOverload('std::str_title', args, _.spec, [
		{
			args: [{ typeId: '00000000-0000-0000-0000-000000000101', optional: false, setoftype: false, variadic: false }],
			returnTypeId: '00000000-0000-0000-0000-000000000101'
		}
	]);
	return _.syntax.$expressionify({
		__kind__: $.ExpressionKind.Function,
		__element__: returnType,
		__cardinality__: cardinality,
		__name__: 'std::str_title',
		__args__: positionalArgs,
		__namedargs__: namedArgs
	});
}

function str_pad_start(...args) {
	const {
		returnType,
		cardinality,
		args: positionalArgs,
		namedArgs
	} = _.syntax.$resolveOverload('std::str_pad_start', args, _.spec, [
		{
			args: [
				{ typeId: '00000000-0000-0000-0000-000000000101', optional: false, setoftype: false, variadic: false },
				{ typeId: '00000000-0000-0000-0000-0000000001ff', optional: false, setoftype: false, variadic: false },
				{ typeId: '00000000-0000-0000-0000-000000000101', optional: true, setoftype: false, variadic: false }
			],
			returnTypeId: '00000000-0000-0000-0000-000000000101'
		}
	]);
	return _.syntax.$expressionify({
		__kind__: $.ExpressionKind.Function,
		__element__: returnType,
		__cardinality__: cardinality,
		__name__: 'std::str_pad_start',
		__args__: positionalArgs,
		__namedargs__: namedArgs
	});
}

function str_lpad(...args) {
	const {
		returnType,
		cardinality,
		args: positionalArgs,
		namedArgs
	} = _.syntax.$resolveOverload('std::str_lpad', args, _.spec, [
		{
			args: [
				{ typeId: '00000000-0000-0000-0000-000000000101', optional: false, setoftype: false, variadic: false },
				{ typeId: '00000000-0000-0000-0000-0000000001ff', optional: false, setoftype: false, variadic: false },
				{ typeId: '00000000-0000-0000-0000-000000000101', optional: true, setoftype: false, variadic: false }
			],
			returnTypeId: '00000000-0000-0000-0000-000000000101'
		}
	]);
	return _.syntax.$expressionify({
		__kind__: $.ExpressionKind.Function,
		__element__: returnType,
		__cardinality__: cardinality,
		__name__: 'std::str_lpad',
		__args__: positionalArgs,
		__namedargs__: namedArgs
	});
}

function str_pad_end(...args) {
	const {
		returnType,
		cardinality,
		args: positionalArgs,
		namedArgs
	} = _.syntax.$resolveOverload('std::str_pad_end', args, _.spec, [
		{
			args: [
				{ typeId: '00000000-0000-0000-0000-000000000101', optional: false, setoftype: false, variadic: false },
				{ typeId: '00000000-0000-0000-0000-0000000001ff', optional: false, setoftype: false, variadic: false },
				{ typeId: '00000000-0000-0000-0000-000000000101', optional: true, setoftype: false, variadic: false }
			],
			returnTypeId: '00000000-0000-0000-0000-000000000101'
		}
	]);
	return _.syntax.$expressionify({
		__kind__: $.ExpressionKind.Function,
		__element__: returnType,
		__cardinality__: cardinality,
		__name__: 'std::str_pad_end',
		__args__: positionalArgs,
		__namedargs__: namedArgs
	});
}

function str_rpad(...args) {
	const {
		returnType,
		cardinality,
		args: positionalArgs,
		namedArgs
	} = _.syntax.$resolveOverload('std::str_rpad', args, _.spec, [
		{
			args: [
				{ typeId: '00000000-0000-0000-0000-000000000101', optional: false, setoftype: false, variadic: false },
				{ typeId: '00000000-0000-0000-0000-0000000001ff', optional: false, setoftype: false, variadic: false },
				{ typeId: '00000000-0000-0000-0000-000000000101', optional: true, setoftype: false, variadic: false }
			],
			returnTypeId: '00000000-0000-0000-0000-000000000101'
		}
	]);
	return _.syntax.$expressionify({
		__kind__: $.ExpressionKind.Function,
		__element__: returnType,
		__cardinality__: cardinality,
		__name__: 'std::str_rpad',
		__args__: positionalArgs,
		__namedargs__: namedArgs
	});
}

function str_trim_start(...args) {
	const {
		returnType,
		cardinality,
		args: positionalArgs,
		namedArgs
	} = _.syntax.$resolveOverload('std::str_trim_start', args, _.spec, [
		{
			args: [
				{ typeId: '00000000-0000-0000-0000-000000000101', optional: false, setoftype: false, variadic: false },
				{ typeId: '00000000-0000-0000-0000-000000000101', optional: true, setoftype: false, variadic: false }
			],
			returnTypeId: '00000000-0000-0000-0000-000000000101'
		}
	]);
	return _.syntax.$expressionify({
		__kind__: $.ExpressionKind.Function,
		__element__: returnType,
		__cardinality__: cardinality,
		__name__: 'std::str_trim_start',
		__args__: positionalArgs,
		__namedargs__: namedArgs
	});
}

function str_ltrim(...args) {
	const {
		returnType,
		cardinality,
		args: positionalArgs,
		namedArgs
	} = _.syntax.$resolveOverload('std::str_ltrim', args, _.spec, [
		{
			args: [
				{ typeId: '00000000-0000-0000-0000-000000000101', optional: false, setoftype: false, variadic: false },
				{ typeId: '00000000-0000-0000-0000-000000000101', optional: true, setoftype: false, variadic: false }
			],
			returnTypeId: '00000000-0000-0000-0000-000000000101'
		}
	]);
	return _.syntax.$expressionify({
		__kind__: $.ExpressionKind.Function,
		__element__: returnType,
		__cardinality__: cardinality,
		__name__: 'std::str_ltrim',
		__args__: positionalArgs,
		__namedargs__: namedArgs
	});
}

function str_trim_end(...args) {
	const {
		returnType,
		cardinality,
		args: positionalArgs,
		namedArgs
	} = _.syntax.$resolveOverload('std::str_trim_end', args, _.spec, [
		{
			args: [
				{ typeId: '00000000-0000-0000-0000-000000000101', optional: false, setoftype: false, variadic: false },
				{ typeId: '00000000-0000-0000-0000-000000000101', optional: true, setoftype: false, variadic: false }
			],
			returnTypeId: '00000000-0000-0000-0000-000000000101'
		}
	]);
	return _.syntax.$expressionify({
		__kind__: $.ExpressionKind.Function,
		__element__: returnType,
		__cardinality__: cardinality,
		__name__: 'std::str_trim_end',
		__args__: positionalArgs,
		__namedargs__: namedArgs
	});
}

function str_rtrim(...args) {
	const {
		returnType,
		cardinality,
		args: positionalArgs,
		namedArgs
	} = _.syntax.$resolveOverload('std::str_rtrim', args, _.spec, [
		{
			args: [
				{ typeId: '00000000-0000-0000-0000-000000000101', optional: false, setoftype: false, variadic: false },
				{ typeId: '00000000-0000-0000-0000-000000000101', optional: true, setoftype: false, variadic: false }
			],
			returnTypeId: '00000000-0000-0000-0000-000000000101'
		}
	]);
	return _.syntax.$expressionify({
		__kind__: $.ExpressionKind.Function,
		__element__: returnType,
		__cardinality__: cardinality,
		__name__: 'std::str_rtrim',
		__args__: positionalArgs,
		__namedargs__: namedArgs
	});
}

function str_trim(...args) {
	const {
		returnType,
		cardinality,
		args: positionalArgs,
		namedArgs
	} = _.syntax.$resolveOverload('std::str_trim', args, _.spec, [
		{
			args: [
				{ typeId: '00000000-0000-0000-0000-000000000101', optional: false, setoftype: false, variadic: false },
				{ typeId: '00000000-0000-0000-0000-000000000101', optional: true, setoftype: false, variadic: false }
			],
			returnTypeId: '00000000-0000-0000-0000-000000000101'
		}
	]);
	return _.syntax.$expressionify({
		__kind__: $.ExpressionKind.Function,
		__element__: returnType,
		__cardinality__: cardinality,
		__name__: 'std::str_trim',
		__args__: positionalArgs,
		__namedargs__: namedArgs
	});
}

function str_split(...args) {
	const {
		returnType,
		cardinality,
		args: positionalArgs,
		namedArgs
	} = _.syntax.$resolveOverload('std::str_split', args, _.spec, [
		{
			args: [
				{ typeId: '00000000-0000-0000-0000-000000000101', optional: false, setoftype: false, variadic: false },
				{ typeId: '00000000-0000-0000-0000-000000000101', optional: false, setoftype: false, variadic: false }
			],
			returnTypeId: 'bb221d39-09f1-507e-8851-62075bb61823'
		}
	]);
	return _.syntax.$expressionify({
		__kind__: $.ExpressionKind.Function,
		__element__: returnType,
		__cardinality__: cardinality,
		__name__: 'std::str_split',
		__args__: positionalArgs,
		__namedargs__: namedArgs
	});
}

function str_replace(...args) {
	const {
		returnType,
		cardinality,
		args: positionalArgs,
		namedArgs
	} = _.syntax.$resolveOverload('std::str_replace', args, _.spec, [
		{
			args: [
				{ typeId: '00000000-0000-0000-0000-000000000101', optional: false, setoftype: false, variadic: false },
				{ typeId: '00000000-0000-0000-0000-000000000101', optional: false, setoftype: false, variadic: false },
				{ typeId: '00000000-0000-0000-0000-000000000101', optional: false, setoftype: false, variadic: false }
			],
			returnTypeId: '00000000-0000-0000-0000-000000000101'
		}
	]);
	return _.syntax.$expressionify({
		__kind__: $.ExpressionKind.Function,
		__element__: returnType,
		__cardinality__: cardinality,
		__name__: 'std::str_replace',
		__args__: positionalArgs,
		__namedargs__: namedArgs
	});
}

function str_reverse(...args) {
	const {
		returnType,
		cardinality,
		args: positionalArgs,
		namedArgs
	} = _.syntax.$resolveOverload('std::str_reverse', args, _.spec, [
		{
			args: [{ typeId: '00000000-0000-0000-0000-000000000101', optional: false, setoftype: false, variadic: false }],
			returnTypeId: '00000000-0000-0000-0000-000000000101'
		}
	]);
	return _.syntax.$expressionify({
		__kind__: $.ExpressionKind.Function,
		__element__: returnType,
		__cardinality__: cardinality,
		__name__: 'std::str_reverse',
		__args__: positionalArgs,
		__namedargs__: namedArgs
	});
}

function uuid_generate_v1mc(...args) {
	const {
		returnType,
		cardinality,
		args: positionalArgs,
		namedArgs
	} = _.syntax.$resolveOverload('std::uuid_generate_v1mc', args, _.spec, [{ args: [], returnTypeId: '00000000-0000-0000-0000-000000000100' }]);
	return _.syntax.$expressionify({
		__kind__: $.ExpressionKind.Function,
		__element__: returnType,
		__cardinality__: cardinality,
		__name__: 'std::uuid_generate_v1mc',
		__args__: positionalArgs,
		__namedargs__: namedArgs
	});
}

function uuid_generate_v4(...args) {
	const {
		returnType,
		cardinality,
		args: positionalArgs,
		namedArgs
	} = _.syntax.$resolveOverload('std::uuid_generate_v4', args, _.spec, [{ args: [], returnTypeId: '00000000-0000-0000-0000-000000000100' }]);
	return _.syntax.$expressionify({
		__kind__: $.ExpressionKind.Function,
		__element__: returnType,
		__cardinality__: cardinality,
		__name__: 'std::uuid_generate_v4',
		__args__: positionalArgs,
		__namedargs__: namedArgs
	});
}

const range = _.syntax.$range;

function multirange(...args) {
	const {
		returnType,
		cardinality,
		args: positionalArgs,
		namedArgs
	} = _.syntax.$resolveOverload('std::multirange', args, _.spec, [
		{
			args: [{ typeId: '3ed001c4-98e8-53a8-b2d1-0cad168d926c', optional: false, setoftype: false, variadic: false }],
			returnTypeId: 'c3231f27-c8a1-5a0c-9830-c71206020eac'
		}
	]);
	return _.syntax.$expressionify({
		__kind__: $.ExpressionKind.Function,
		__element__: returnType,
		__cardinality__: cardinality,
		__name__: 'std::multirange',
		__args__: positionalArgs,
		__namedargs__: namedArgs
	});
}

function range_is_empty(...args) {
	const {
		returnType,
		cardinality,
		args: positionalArgs,
		namedArgs
	} = _.syntax.$resolveOverload('std::range_is_empty', args, _.spec, [
		{
			args: [{ typeId: '49748e47-8d91-5269-9a34-2e8ca194e0f2', optional: false, setoftype: false, variadic: false }],
			returnTypeId: '00000000-0000-0000-0000-000000000109'
		},
		{
			args: [{ typeId: 'c3231f27-c8a1-5a0c-9830-c71206020eac', optional: false, setoftype: false, variadic: false }],
			returnTypeId: '00000000-0000-0000-0000-000000000109'
		}
	]);
	return _.syntax.$expressionify({
		__kind__: $.ExpressionKind.Function,
		__element__: returnType,
		__cardinality__: cardinality,
		__name__: 'std::range_is_empty',
		__args__: positionalArgs,
		__namedargs__: namedArgs
	});
}

function strictly_above(...args) {
	const {
		returnType,
		cardinality,
		args: positionalArgs,
		namedArgs
	} = _.syntax.$resolveOverload('std::strictly_above', args, _.spec, [
		{
			args: [
				{ typeId: '49748e47-8d91-5269-9a34-2e8ca194e0f2', optional: false, setoftype: false, variadic: false },
				{ typeId: '49748e47-8d91-5269-9a34-2e8ca194e0f2', optional: false, setoftype: false, variadic: false }
			],
			returnTypeId: '00000000-0000-0000-0000-000000000109'
		},
		{
			args: [
				{ typeId: 'c3231f27-c8a1-5a0c-9830-c71206020eac', optional: false, setoftype: false, variadic: false },
				{ typeId: 'c3231f27-c8a1-5a0c-9830-c71206020eac', optional: false, setoftype: false, variadic: false }
			],
			returnTypeId: '00000000-0000-0000-0000-000000000109'
		}
	]);
	return _.syntax.$expressionify({
		__kind__: $.ExpressionKind.Function,
		__element__: returnType,
		__cardinality__: cardinality,
		__name__: 'std::strictly_above',
		__args__: positionalArgs,
		__namedargs__: namedArgs
	});
}

function range_get_upper(...args) {
	const {
		returnType,
		cardinality,
		args: positionalArgs,
		namedArgs
	} = _.syntax.$resolveOverload('std::range_get_upper', args, _.spec, [
		{
			args: [{ typeId: '49748e47-8d91-5269-9a34-2e8ca194e0f2', optional: false, setoftype: false, variadic: false }],
			returnTypeId: '581b0325-a044-58d4-aa37-3a85ea671313',
			returnTypemod: 'OptionalType'
		},
		{
			args: [{ typeId: 'c3231f27-c8a1-5a0c-9830-c71206020eac', optional: false, setoftype: false, variadic: false }],
			returnTypeId: '581b0325-a044-58d4-aa37-3a85ea671313',
			returnTypemod: 'OptionalType'
		}
	]);
	return _.syntax.$expressionify({
		__kind__: $.ExpressionKind.Function,
		__element__: returnType,
		__cardinality__: cardinality,
		__name__: 'std::range_get_upper',
		__args__: positionalArgs,
		__namedargs__: namedArgs
	});
}

function range_get_lower(...args) {
	const {
		returnType,
		cardinality,
		args: positionalArgs,
		namedArgs
	} = _.syntax.$resolveOverload('std::range_get_lower', args, _.spec, [
		{
			args: [{ typeId: '49748e47-8d91-5269-9a34-2e8ca194e0f2', optional: false, setoftype: false, variadic: false }],
			returnTypeId: '581b0325-a044-58d4-aa37-3a85ea671313',
			returnTypemod: 'OptionalType'
		},
		{
			args: [{ typeId: 'c3231f27-c8a1-5a0c-9830-c71206020eac', optional: false, setoftype: false, variadic: false }],
			returnTypeId: '581b0325-a044-58d4-aa37-3a85ea671313',
			returnTypemod: 'OptionalType'
		}
	]);
	return _.syntax.$expressionify({
		__kind__: $.ExpressionKind.Function,
		__element__: returnType,
		__cardinality__: cardinality,
		__name__: 'std::range_get_lower',
		__args__: positionalArgs,
		__namedargs__: namedArgs
	});
}

function range_is_inclusive_upper(...args) {
	const {
		returnType,
		cardinality,
		args: positionalArgs,
		namedArgs
	} = _.syntax.$resolveOverload('std::range_is_inclusive_upper', args, _.spec, [
		{
			args: [{ typeId: '49748e47-8d91-5269-9a34-2e8ca194e0f2', optional: false, setoftype: false, variadic: false }],
			returnTypeId: '00000000-0000-0000-0000-000000000109'
		},
		{
			args: [{ typeId: 'c3231f27-c8a1-5a0c-9830-c71206020eac', optional: false, setoftype: false, variadic: false }],
			returnTypeId: '00000000-0000-0000-0000-000000000109'
		}
	]);
	return _.syntax.$expressionify({
		__kind__: $.ExpressionKind.Function,
		__element__: returnType,
		__cardinality__: cardinality,
		__name__: 'std::range_is_inclusive_upper',
		__args__: positionalArgs,
		__namedargs__: namedArgs
	});
}

function range_is_inclusive_lower(...args) {
	const {
		returnType,
		cardinality,
		args: positionalArgs,
		namedArgs
	} = _.syntax.$resolveOverload('std::range_is_inclusive_lower', args, _.spec, [
		{
			args: [{ typeId: '49748e47-8d91-5269-9a34-2e8ca194e0f2', optional: false, setoftype: false, variadic: false }],
			returnTypeId: '00000000-0000-0000-0000-000000000109'
		},
		{
			args: [{ typeId: 'c3231f27-c8a1-5a0c-9830-c71206020eac', optional: false, setoftype: false, variadic: false }],
			returnTypeId: '00000000-0000-0000-0000-000000000109'
		}
	]);
	return _.syntax.$expressionify({
		__kind__: $.ExpressionKind.Function,
		__element__: returnType,
		__cardinality__: cardinality,
		__name__: 'std::range_is_inclusive_lower',
		__args__: positionalArgs,
		__namedargs__: namedArgs
	});
}

function overlaps(...args) {
	const {
		returnType,
		cardinality,
		args: positionalArgs,
		namedArgs
	} = _.syntax.$resolveOverload('std::overlaps', args, _.spec, [
		{
			args: [
				{ typeId: '49748e47-8d91-5269-9a34-2e8ca194e0f2', optional: false, setoftype: false, variadic: false },
				{ typeId: '49748e47-8d91-5269-9a34-2e8ca194e0f2', optional: false, setoftype: false, variadic: false }
			],
			returnTypeId: '00000000-0000-0000-0000-000000000109'
		},
		{
			args: [
				{ typeId: 'c3231f27-c8a1-5a0c-9830-c71206020eac', optional: false, setoftype: false, variadic: false },
				{ typeId: 'c3231f27-c8a1-5a0c-9830-c71206020eac', optional: false, setoftype: false, variadic: false }
			],
			returnTypeId: '00000000-0000-0000-0000-000000000109'
		}
	]);
	return _.syntax.$expressionify({
		__kind__: $.ExpressionKind.Function,
		__element__: returnType,
		__cardinality__: cardinality,
		__name__: 'std::overlaps',
		__args__: positionalArgs,
		__namedargs__: namedArgs
	});
}

function multirange_unpack(...args) {
	const {
		returnType,
		cardinality,
		args: positionalArgs,
		namedArgs
	} = _.syntax.$resolveOverload('std::multirange_unpack', args, _.spec, [
		{
			args: [{ typeId: 'a36a494d-f2c1-5886-8e17-b0c8ba9337ff', optional: false, setoftype: false, variadic: false }],
			returnTypeId: '38b58945-dfd2-572c-bf7e-8cadf204a2ec',
			returnTypemod: 'SetOfType'
		},
		{
			args: [{ typeId: 'da3c9da3-1b79-53d0-ae36-82026533939b', optional: false, setoftype: false, variadic: false }],
			returnTypeId: '356c02b7-20fa-5d27-90fc-aa628dd37c5e',
			returnTypemod: 'SetOfType'
		},
		{
			args: [{ typeId: '18b39277-efe3-582c-8bdc-b18f4ed46e09', optional: false, setoftype: false, variadic: false }],
			returnTypeId: 'ef0fdfe1-43f9-5954-b804-56e9b7015ffc',
			returnTypemod: 'SetOfType'
		},
		{
			args: [{ typeId: '75f5b5c7-f201-56a8-9fd0-bd139e69fdbe', optional: false, setoftype: false, variadic: false }],
			returnTypeId: 'b2f8ab6d-ebca-517d-9f16-086423c5bb9c',
			returnTypemod: 'SetOfType'
		},
		{
			args: [{ typeId: '80da35c5-4ed6-5799-8eea-1c5923a3f8d3', optional: false, setoftype: false, variadic: false }],
			returnTypeId: 'c61dd200-697a-5b70-9ff0-6c623a700c14',
			returnTypemod: 'SetOfType'
		},
		{
			args: [{ typeId: '58da8bd4-709a-50bc-b0b4-a1918b7dc2ba', optional: false, setoftype: false, variadic: false }],
			returnTypeId: '10674aaf-8d88-5593-abe9-f7d82be5162b',
			returnTypemod: 'SetOfType'
		},
		{
			args: [{ typeId: '1990bea3-4cb3-5881-9641-8727f5d2af59', optional: false, setoftype: false, variadic: false }],
			returnTypeId: 'c4441320-c6b5-5f6a-95e4-0dd4aad4e49f',
			returnTypemod: 'SetOfType'
		},
		{
			args: [{ typeId: 'e294f13d-34ee-529f-b7f8-7c3e2fd17e6e', optional: false, setoftype: false, variadic: false }],
			returnTypeId: '1e76d7c5-b67c-542c-bc8f-238b93ff1726',
			returnTypemod: 'SetOfType'
		}
	]);
	return _.syntax.$expressionify({
		__kind__: $.ExpressionKind.Function,
		__element__: returnType,
		__cardinality__: cardinality,
		__name__: 'std::multirange_unpack',
		__args__: positionalArgs,
		__namedargs__: namedArgs
	});
}

function strictly_below(...args) {
	const {
		returnType,
		cardinality,
		args: positionalArgs,
		namedArgs
	} = _.syntax.$resolveOverload('std::strictly_below', args, _.spec, [
		{
			args: [
				{ typeId: '49748e47-8d91-5269-9a34-2e8ca194e0f2', optional: false, setoftype: false, variadic: false },
				{ typeId: '49748e47-8d91-5269-9a34-2e8ca194e0f2', optional: false, setoftype: false, variadic: false }
			],
			returnTypeId: '00000000-0000-0000-0000-000000000109'
		},
		{
			args: [
				{ typeId: 'c3231f27-c8a1-5a0c-9830-c71206020eac', optional: false, setoftype: false, variadic: false },
				{ typeId: 'c3231f27-c8a1-5a0c-9830-c71206020eac', optional: false, setoftype: false, variadic: false }
			],
			returnTypeId: '00000000-0000-0000-0000-000000000109'
		}
	]);
	return _.syntax.$expressionify({
		__kind__: $.ExpressionKind.Function,
		__element__: returnType,
		__cardinality__: cardinality,
		__name__: 'std::strictly_below',
		__args__: positionalArgs,
		__namedargs__: namedArgs
	});
}

function bounded_above(...args) {
	const {
		returnType,
		cardinality,
		args: positionalArgs,
		namedArgs
	} = _.syntax.$resolveOverload('std::bounded_above', args, _.spec, [
		{
			args: [
				{ typeId: '49748e47-8d91-5269-9a34-2e8ca194e0f2', optional: false, setoftype: false, variadic: false },
				{ typeId: '49748e47-8d91-5269-9a34-2e8ca194e0f2', optional: false, setoftype: false, variadic: false }
			],
			returnTypeId: '00000000-0000-0000-0000-000000000109'
		},
		{
			args: [
				{ typeId: 'c3231f27-c8a1-5a0c-9830-c71206020eac', optional: false, setoftype: false, variadic: false },
				{ typeId: 'c3231f27-c8a1-5a0c-9830-c71206020eac', optional: false, setoftype: false, variadic: false }
			],
			returnTypeId: '00000000-0000-0000-0000-000000000109'
		}
	]);
	return _.syntax.$expressionify({
		__kind__: $.ExpressionKind.Function,
		__element__: returnType,
		__cardinality__: cardinality,
		__name__: 'std::bounded_above',
		__args__: positionalArgs,
		__namedargs__: namedArgs
	});
}

function bounded_below(...args) {
	const {
		returnType,
		cardinality,
		args: positionalArgs,
		namedArgs
	} = _.syntax.$resolveOverload('std::bounded_below', args, _.spec, [
		{
			args: [
				{ typeId: '49748e47-8d91-5269-9a34-2e8ca194e0f2', optional: false, setoftype: false, variadic: false },
				{ typeId: '49748e47-8d91-5269-9a34-2e8ca194e0f2', optional: false, setoftype: false, variadic: false }
			],
			returnTypeId: '00000000-0000-0000-0000-000000000109'
		},
		{
			args: [
				{ typeId: 'c3231f27-c8a1-5a0c-9830-c71206020eac', optional: false, setoftype: false, variadic: false },
				{ typeId: 'c3231f27-c8a1-5a0c-9830-c71206020eac', optional: false, setoftype: false, variadic: false }
			],
			returnTypeId: '00000000-0000-0000-0000-000000000109'
		}
	]);
	return _.syntax.$expressionify({
		__kind__: $.ExpressionKind.Function,
		__element__: returnType,
		__cardinality__: cardinality,
		__name__: 'std::bounded_below',
		__args__: positionalArgs,
		__namedargs__: namedArgs
	});
}

function adjacent(...args) {
	const {
		returnType,
		cardinality,
		args: positionalArgs,
		namedArgs
	} = _.syntax.$resolveOverload('std::adjacent', args, _.spec, [
		{
			args: [
				{ typeId: '49748e47-8d91-5269-9a34-2e8ca194e0f2', optional: false, setoftype: false, variadic: false },
				{ typeId: '49748e47-8d91-5269-9a34-2e8ca194e0f2', optional: false, setoftype: false, variadic: false }
			],
			returnTypeId: '00000000-0000-0000-0000-000000000109'
		},
		{
			args: [
				{ typeId: 'c3231f27-c8a1-5a0c-9830-c71206020eac', optional: false, setoftype: false, variadic: false },
				{ typeId: 'c3231f27-c8a1-5a0c-9830-c71206020eac', optional: false, setoftype: false, variadic: false }
			],
			returnTypeId: '00000000-0000-0000-0000-000000000109'
		}
	]);
	return _.syntax.$expressionify({
		__kind__: $.ExpressionKind.Function,
		__element__: returnType,
		__cardinality__: cardinality,
		__name__: 'std::adjacent',
		__args__: positionalArgs,
		__namedargs__: namedArgs
	});
}

function to_str(...args) {
	const {
		returnType,
		cardinality,
		args: positionalArgs,
		namedArgs
	} = _.syntax.$resolveOverload('std::to_str', args, _.spec, [
		{
			args: [{ typeId: '00000000-0000-0000-0000-000000000102', optional: false, setoftype: false, variadic: false }],
			returnTypeId: '00000000-0000-0000-0000-000000000101'
		},
		{
			args: [
				{ typeId: '00000000-0000-0000-0000-00000000010a', optional: false, setoftype: false, variadic: false },
				{ typeId: '00000000-0000-0000-0000-000000000101', optional: true, setoftype: false, variadic: false }
			],
			returnTypeId: '00000000-0000-0000-0000-000000000101'
		},
		{
			args: [
				{ typeId: '00000000-0000-0000-0000-00000000010e', optional: false, setoftype: false, variadic: false },
				{ typeId: '00000000-0000-0000-0000-000000000101', optional: true, setoftype: false, variadic: false }
			],
			returnTypeId: '00000000-0000-0000-0000-000000000101'
		},
		{
			args: [
				{ typeId: '00000000-0000-0000-0000-0000000001ff', optional: false, setoftype: false, variadic: false },
				{ typeId: '00000000-0000-0000-0000-000000000101', optional: true, setoftype: false, variadic: false }
			],
			returnTypeId: '00000000-0000-0000-0000-000000000101'
		},
		{
			args: [
				{ typeId: '00000000-0000-0000-0000-000000000110', optional: false, setoftype: false, variadic: false },
				{ typeId: '00000000-0000-0000-0000-000000000101', optional: true, setoftype: false, variadic: false }
			],
			returnTypeId: '00000000-0000-0000-0000-000000000101'
		},
		{
			args: [
				{ typeId: 'bb221d39-09f1-507e-8851-62075bb61823', optional: false, setoftype: false, variadic: false },
				{ typeId: '00000000-0000-0000-0000-000000000101', optional: false, setoftype: false, variadic: false }
			],
			returnTypeId: '00000000-0000-0000-0000-000000000101'
		},
		{
			args: [
				{ typeId: '00000000-0000-0000-0000-00000000010f', optional: false, setoftype: false, variadic: false },
				{ typeId: '00000000-0000-0000-0000-000000000101', optional: true, setoftype: false, variadic: false }
			],
			returnTypeId: '00000000-0000-0000-0000-000000000101'
		},
		{
			args: [
				{ typeId: '00000000-0000-0000-0000-00000000010c', optional: false, setoftype: false, variadic: false },
				{ typeId: '00000000-0000-0000-0000-000000000101', optional: true, setoftype: false, variadic: false }
			],
			returnTypeId: '00000000-0000-0000-0000-000000000101'
		},
		{
			args: [
				{ typeId: '00000000-0000-0000-0000-00000000010d', optional: false, setoftype: false, variadic: false },
				{ typeId: '00000000-0000-0000-0000-000000000101', optional: true, setoftype: false, variadic: false }
			],
			returnTypeId: '00000000-0000-0000-0000-000000000101'
		},
		{
			args: [
				{ typeId: '00000000-0000-0000-0000-000000000108', optional: false, setoftype: false, variadic: false },
				{ typeId: '00000000-0000-0000-0000-000000000101', optional: true, setoftype: false, variadic: false }
			],
			returnTypeId: '00000000-0000-0000-0000-000000000101'
		},
		{
			args: [
				{ typeId: '00000000-0000-0000-0000-00000000010b', optional: false, setoftype: false, variadic: false },
				{ typeId: '00000000-0000-0000-0000-000000000101', optional: true, setoftype: false, variadic: false }
			],
			returnTypeId: '00000000-0000-0000-0000-000000000101'
		},
		{
			args: [
				{ typeId: '00000000-0000-0000-0000-000000000111', optional: false, setoftype: false, variadic: false },
				{ typeId: '00000000-0000-0000-0000-000000000101', optional: true, setoftype: false, variadic: false }
			],
			returnTypeId: '00000000-0000-0000-0000-000000000101'
		}
	]);
	return _.syntax.$expressionify({
		__kind__: $.ExpressionKind.Function,
		__element__: returnType,
		__cardinality__: cardinality,
		__name__: 'std::to_str',
		__args__: positionalArgs,
		__namedargs__: namedArgs
	});
}

function to_bytes(...args) {
	const {
		returnType,
		cardinality,
		args: positionalArgs,
		namedArgs
	} = _.syntax.$resolveOverload('std::to_bytes', args, _.spec, [
		{
			args: [{ typeId: '00000000-0000-0000-0000-000000000101', optional: false, setoftype: false, variadic: false }],
			returnTypeId: '00000000-0000-0000-0000-000000000102'
		},
		{
			args: [{ typeId: '00000000-0000-0000-0000-000000000100', optional: false, setoftype: false, variadic: false }],
			returnTypeId: '00000000-0000-0000-0000-000000000102'
		},
		{
			args: [
				{ typeId: '00000000-0000-0000-0000-0000000001ff', optional: false, setoftype: false, variadic: false },
				{ typeId: 'e4a1d11b-227e-5744-a0c9-31f9cd756e7b', optional: false, setoftype: false, variadic: false }
			],
			returnTypeId: '00000000-0000-0000-0000-000000000102'
		}
	]);
	return _.syntax.$expressionify({
		__kind__: $.ExpressionKind.Function,
		__element__: returnType,
		__cardinality__: cardinality,
		__name__: 'std::to_bytes',
		__args__: positionalArgs,
		__namedargs__: namedArgs
	});
}

function to_json(...args) {
	const {
		returnType,
		cardinality,
		args: positionalArgs,
		namedArgs
	} = _.syntax.$resolveOverload('std::to_json', args, _.spec, [
		{
			args: [{ typeId: '00000000-0000-0000-0000-000000000101', optional: false, setoftype: false, variadic: false }],
			returnTypeId: '00000000-0000-0000-0000-00000000010f'
		}
	]);
	return _.syntax.$expressionify({
		__kind__: $.ExpressionKind.Function,
		__element__: returnType,
		__cardinality__: cardinality,
		__name__: 'std::to_json',
		__args__: positionalArgs,
		__namedargs__: namedArgs
	});
}

function to_datetime(...args) {
	const {
		returnType,
		cardinality,
		args: positionalArgs,
		namedArgs
	} = _.syntax.$resolveOverload('std::to_datetime', args, _.spec, [
		{
			args: [{ typeId: '00000000-0000-0000-0000-0000000001ff', optional: false, setoftype: false, variadic: false }],
			returnTypeId: '00000000-0000-0000-0000-00000000010a'
		},
		{
			args: [
				{ typeId: '00000000-0000-0000-0000-000000000101', optional: false, setoftype: false, variadic: false },
				{ typeId: '00000000-0000-0000-0000-000000000101', optional: true, setoftype: false, variadic: false }
			],
			returnTypeId: '00000000-0000-0000-0000-00000000010a'
		},
		{
			args: [
				{ typeId: '00000000-0000-0000-0000-0000000001ff', optional: false, setoftype: false, variadic: false },
				{ typeId: '00000000-0000-0000-0000-0000000001ff', optional: false, setoftype: false, variadic: false },
				{ typeId: '00000000-0000-0000-0000-0000000001ff', optional: false, setoftype: false, variadic: false },
				{ typeId: '00000000-0000-0000-0000-0000000001ff', optional: false, setoftype: false, variadic: false },
				{ typeId: '00000000-0000-0000-0000-0000000001ff', optional: false, setoftype: false, variadic: false },
				{ typeId: '00000000-0000-0000-0000-0000000001ff', optional: false, setoftype: false, variadic: false },
				{ typeId: '00000000-0000-0000-0000-000000000101', optional: false, setoftype: false, variadic: false }
			],
			returnTypeId: '00000000-0000-0000-0000-00000000010a'
		},
		{
			args: [{ typeId: '00000000-0000-0000-0000-000000000108', optional: false, setoftype: false, variadic: false }],
			returnTypeId: '00000000-0000-0000-0000-00000000010a'
		},
		{
			args: [
				{ typeId: '00000000-0000-0000-0000-00000000010b', optional: false, setoftype: false, variadic: false },
				{ typeId: '00000000-0000-0000-0000-000000000101', optional: false, setoftype: false, variadic: false }
			],
			returnTypeId: '00000000-0000-0000-0000-00000000010a'
		}
	]);
	return _.syntax.$expressionify({
		__kind__: $.ExpressionKind.Function,
		__element__: returnType,
		__cardinality__: cardinality,
		__name__: 'std::to_datetime',
		__args__: positionalArgs,
		__namedargs__: namedArgs
	});
}

function to_duration(...args) {
	const {
		returnType,
		cardinality,
		args: positionalArgs,
		namedArgs
	} = _.syntax.$resolveOverload('std::to_duration', args, _.spec, [
		{
			args: [],
			namedArgs: {
				hours: { typeId: '00000000-0000-0000-0000-0000000001ff', optional: true, setoftype: false, variadic: false },
				minutes: { typeId: '00000000-0000-0000-0000-0000000001ff', optional: true, setoftype: false, variadic: false },
				seconds: { typeId: '00000000-0000-0000-0000-0000000001ff', optional: true, setoftype: false, variadic: false },
				microseconds: { typeId: '00000000-0000-0000-0000-0000000001ff', optional: true, setoftype: false, variadic: false }
			},
			returnTypeId: '00000000-0000-0000-0000-00000000010e'
		}
	]);
	return _.syntax.$expressionify({
		__kind__: $.ExpressionKind.Function,
		__element__: returnType,
		__cardinality__: cardinality,
		__name__: 'std::to_duration',
		__args__: positionalArgs,
		__namedargs__: namedArgs
	});
}

function to_bigint(...args) {
	const {
		returnType,
		cardinality,
		args: positionalArgs,
		namedArgs
	} = _.syntax.$resolveOverload('std::to_bigint', args, _.spec, [
		{
			args: [
				{ typeId: '00000000-0000-0000-0000-000000000101', optional: false, setoftype: false, variadic: false },
				{ typeId: '00000000-0000-0000-0000-000000000101', optional: true, setoftype: false, variadic: false }
			],
			returnTypeId: '00000000-0000-0000-0000-000000000110'
		}
	]);
	return _.syntax.$expressionify({
		__kind__: $.ExpressionKind.Function,
		__element__: returnType,
		__cardinality__: cardinality,
		__name__: 'std::to_bigint',
		__args__: positionalArgs,
		__namedargs__: namedArgs
	});
}

function to_decimal(...args) {
	const {
		returnType,
		cardinality,
		args: positionalArgs,
		namedArgs
	} = _.syntax.$resolveOverload('std::to_decimal', args, _.spec, [
		{
			args: [
				{ typeId: '00000000-0000-0000-0000-000000000101', optional: false, setoftype: false, variadic: false },
				{ typeId: '00000000-0000-0000-0000-000000000101', optional: true, setoftype: false, variadic: false }
			],
			returnTypeId: '00000000-0000-0000-0000-000000000108'
		}
	]);
	return _.syntax.$expressionify({
		__kind__: $.ExpressionKind.Function,
		__element__: returnType,
		__cardinality__: cardinality,
		__name__: 'std::to_decimal',
		__args__: positionalArgs,
		__namedargs__: namedArgs
	});
}

function to_int64(...args) {
	const {
		returnType,
		cardinality,
		args: positionalArgs,
		namedArgs
	} = _.syntax.$resolveOverload('std::to_int64', args, _.spec, [
		{
			args: [
				{ typeId: '00000000-0000-0000-0000-000000000101', optional: false, setoftype: false, variadic: false },
				{ typeId: '00000000-0000-0000-0000-000000000101', optional: true, setoftype: false, variadic: false }
			],
			returnTypeId: '00000000-0000-0000-0000-0000000001ff'
		},
		{
			args: [
				{ typeId: '00000000-0000-0000-0000-000000000102', optional: false, setoftype: false, variadic: false },
				{ typeId: 'e4a1d11b-227e-5744-a0c9-31f9cd756e7b', optional: false, setoftype: false, variadic: false }
			],
			returnTypeId: '00000000-0000-0000-0000-0000000001ff'
		}
	]);
	return _.syntax.$expressionify({
		__kind__: $.ExpressionKind.Function,
		__element__: returnType,
		__cardinality__: cardinality,
		__name__: 'std::to_int64',
		__args__: positionalArgs,
		__namedargs__: namedArgs
	});
}

function to_int32(...args) {
	const {
		returnType,
		cardinality,
		args: positionalArgs,
		namedArgs
	} = _.syntax.$resolveOverload('std::to_int32', args, _.spec, [
		{
			args: [
				{ typeId: '00000000-0000-0000-0000-000000000101', optional: false, setoftype: false, variadic: false },
				{ typeId: '00000000-0000-0000-0000-000000000101', optional: true, setoftype: false, variadic: false }
			],
			returnTypeId: '00000000-0000-0000-0000-0000000001ff'
		},
		{
			args: [
				{ typeId: '00000000-0000-0000-0000-000000000102', optional: false, setoftype: false, variadic: false },
				{ typeId: 'e4a1d11b-227e-5744-a0c9-31f9cd756e7b', optional: false, setoftype: false, variadic: false }
			],
			returnTypeId: '00000000-0000-0000-0000-0000000001ff'
		}
	]);
	return _.syntax.$expressionify({
		__kind__: $.ExpressionKind.Function,
		__element__: returnType,
		__cardinality__: cardinality,
		__name__: 'std::to_int32',
		__args__: positionalArgs,
		__namedargs__: namedArgs
	});
}

function to_int16(...args) {
	const {
		returnType,
		cardinality,
		args: positionalArgs,
		namedArgs
	} = _.syntax.$resolveOverload('std::to_int16', args, _.spec, [
		{
			args: [
				{ typeId: '00000000-0000-0000-0000-000000000101', optional: false, setoftype: false, variadic: false },
				{ typeId: '00000000-0000-0000-0000-000000000101', optional: true, setoftype: false, variadic: false }
			],
			returnTypeId: '00000000-0000-0000-0000-0000000001ff'
		},
		{
			args: [
				{ typeId: '00000000-0000-0000-0000-000000000102', optional: false, setoftype: false, variadic: false },
				{ typeId: 'e4a1d11b-227e-5744-a0c9-31f9cd756e7b', optional: false, setoftype: false, variadic: false }
			],
			returnTypeId: '00000000-0000-0000-0000-0000000001ff'
		}
	]);
	return _.syntax.$expressionify({
		__kind__: $.ExpressionKind.Function,
		__element__: returnType,
		__cardinality__: cardinality,
		__name__: 'std::to_int16',
		__args__: positionalArgs,
		__namedargs__: namedArgs
	});
}

function to_float64(...args) {
	const {
		returnType,
		cardinality,
		args: positionalArgs,
		namedArgs
	} = _.syntax.$resolveOverload('std::to_float64', args, _.spec, [
		{
			args: [
				{ typeId: '00000000-0000-0000-0000-000000000101', optional: false, setoftype: false, variadic: false },
				{ typeId: '00000000-0000-0000-0000-000000000101', optional: true, setoftype: false, variadic: false }
			],
			returnTypeId: '00000000-0000-0000-0000-0000000001ff'
		}
	]);
	return _.syntax.$expressionify({
		__kind__: $.ExpressionKind.Function,
		__element__: returnType,
		__cardinality__: cardinality,
		__name__: 'std::to_float64',
		__args__: positionalArgs,
		__namedargs__: namedArgs
	});
}

function to_float32(...args) {
	const {
		returnType,
		cardinality,
		args: positionalArgs,
		namedArgs
	} = _.syntax.$resolveOverload('std::to_float32', args, _.spec, [
		{
			args: [
				{ typeId: '00000000-0000-0000-0000-000000000101', optional: false, setoftype: false, variadic: false },
				{ typeId: '00000000-0000-0000-0000-000000000101', optional: true, setoftype: false, variadic: false }
			],
			returnTypeId: '00000000-0000-0000-0000-0000000001ff'
		}
	]);
	return _.syntax.$expressionify({
		__kind__: $.ExpressionKind.Function,
		__element__: returnType,
		__cardinality__: cardinality,
		__name__: 'std::to_float32',
		__args__: positionalArgs,
		__namedargs__: namedArgs
	});
}

function to_uuid(...args) {
	const {
		returnType,
		cardinality,
		args: positionalArgs,
		namedArgs
	} = _.syntax.$resolveOverload('std::to_uuid', args, _.spec, [
		{
			args: [{ typeId: '00000000-0000-0000-0000-000000000102', optional: false, setoftype: false, variadic: false }],
			returnTypeId: '00000000-0000-0000-0000-000000000100'
		}
	]);
	return _.syntax.$expressionify({
		__kind__: $.ExpressionKind.Function,
		__element__: returnType,
		__cardinality__: cardinality,
		__name__: 'std::to_uuid',
		__args__: positionalArgs,
		__namedargs__: namedArgs
	});
}

function sequence_reset(...args) {
	const {
		returnType,
		cardinality,
		args: positionalArgs,
		namedArgs
	} = _.syntax.$resolveOverload('std::sequence_reset', args, _.spec, [
		{
			args: [{ typeId: 'd055dd47-3eb9-5a31-9d8f-5e7053bbe11e', optional: false, setoftype: false, variadic: false }],
			returnTypeId: '00000000-0000-0000-0000-0000000001ff'
		},
		{
			args: [
				{ typeId: 'd055dd47-3eb9-5a31-9d8f-5e7053bbe11e', optional: false, setoftype: false, variadic: false },
				{ typeId: '00000000-0000-0000-0000-0000000001ff', optional: false, setoftype: false, variadic: false }
			],
			returnTypeId: '00000000-0000-0000-0000-0000000001ff'
		}
	]);
	return _.syntax.$expressionify({
		__kind__: $.ExpressionKind.Function,
		__element__: returnType,
		__cardinality__: cardinality,
		__name__: 'std::sequence_reset',
		__args__: positionalArgs,
		__namedargs__: namedArgs
	});
}

function sequence_next(...args) {
	const {
		returnType,
		cardinality,
		args: positionalArgs,
		namedArgs
	} = _.syntax.$resolveOverload('std::sequence_next', args, _.spec, [
		{
			args: [{ typeId: 'd055dd47-3eb9-5a31-9d8f-5e7053bbe11e', optional: false, setoftype: false, variadic: false }],
			returnTypeId: '00000000-0000-0000-0000-0000000001ff'
		}
	]);
	return _.syntax.$expressionify({
		__kind__: $.ExpressionKind.Function,
		__element__: returnType,
		__cardinality__: cardinality,
		__name__: 'std::sequence_next',
		__args__: positionalArgs,
		__namedargs__: namedArgs
	});
}

export {
	Endian,
	JsonEmpty,
	bigint,
	bool,
	bytes,
	datetime,
	decimal,
	duration,
	float32,
	float64,
	int16,
	int32,
	int64,
	json,
	$sequence,
	str,
	uuid,
	number,
	$BaseObject,
	BaseObject,
	$Object_8ce8c71ee4fa5f73840c22d7eaa58588,
	Object_8ce8c71ee4fa5f73840c22d7eaa58588,
	$FreeObject,
	FreeObject
};

const __defaultExports = {
	Endian: Endian,
	JsonEmpty: JsonEmpty,
	bigint: bigint,
	bool: bool,
	bytes: bytes,
	datetime: datetime,
	decimal: decimal,
	duration: duration,
	float32: float32,
	float64: float64,
	int16: int16,
	int32: int32,
	int64: int64,
	json: json,
	str: str,
	uuid: uuid,
	BaseObject: BaseObject,
	Object: Object_8ce8c71ee4fa5f73840c22d7eaa58588,
	FreeObject: FreeObject,
	assert_single: assert_single,
	assert_exists: assert_exists,
	assert_distinct: assert_distinct,
	assert: assert,
	len: len,
	sum: sum,
	count: count,
	random: random,
	min: min,
	max: max,
	all: all,
	any: any,
	enumerate: enumerate,
	round: round,
	contains: contains,
	array_get: array_get,
	find: find,
	bit_and: bit_and,
	bit_or: bit_or,
	bit_xor: bit_xor,
	bit_not: bit_not,
	bit_rshift: bit_rshift,
	bit_lshift: bit_lshift,
	array_agg: array_agg,
	array_unpack: array_unpack,
	array_fill: array_fill,
	array_replace: array_replace,
	array_join: array_join,
	bytes_get_bit: bytes_get_bit,
	datetime_current: datetime_current,
	datetime_of_transaction: datetime_of_transaction,
	datetime_of_statement: datetime_of_statement,
	datetime_get: datetime_get,
	datetime_truncate: datetime_truncate,
	duration_get: duration_get,
	duration_truncate: duration_truncate,
	duration_to_seconds: duration_to_seconds,
	json_typeof: json_typeof,
	json_array_unpack: json_array_unpack,
	json_object_unpack: json_object_unpack,
	json_object_pack: json_object_pack,
	json_get: json_get,
	json_set: json_set,
	range_unpack: range_unpack,
	re_match: re_match,
	re_match_all: re_match_all,
	re_test: re_test,
	re_replace: re_replace,
	str_repeat: str_repeat,
	str_lower: str_lower,
	str_upper: str_upper,
	str_title: str_title,
	str_pad_start: str_pad_start,
	str_lpad: str_lpad,
	str_pad_end: str_pad_end,
	str_rpad: str_rpad,
	str_trim_start: str_trim_start,
	str_ltrim: str_ltrim,
	str_trim_end: str_trim_end,
	str_rtrim: str_rtrim,
	str_trim: str_trim,
	str_split: str_split,
	str_replace: str_replace,
	str_reverse: str_reverse,
	uuid_generate_v1mc: uuid_generate_v1mc,
	uuid_generate_v4: uuid_generate_v4,
	range: range,
	multirange: multirange,
	range_is_empty: range_is_empty,
	strictly_above: strictly_above,
	range_get_upper: range_get_upper,
	range_get_lower: range_get_lower,
	range_is_inclusive_upper: range_is_inclusive_upper,
	range_is_inclusive_lower: range_is_inclusive_lower,
	overlaps: overlaps,
	multirange_unpack: multirange_unpack,
	strictly_below: strictly_below,
	bounded_above: bounded_above,
	bounded_below: bounded_below,
	adjacent: adjacent,
	to_str: to_str,
	to_bytes: to_bytes,
	to_json: to_json,
	to_datetime: to_datetime,
	to_duration: to_duration,
	to_bigint: to_bigint,
	to_decimal: to_decimal,
	to_int64: to_int64,
	to_int32: to_int32,
	to_int16: to_int16,
	to_float64: to_float64,
	to_float32: to_float32,
	to_uuid: to_uuid,
	sequence_reset: sequence_reset,
	sequence_next: sequence_next,
	enc: _module__enc
};
export default __defaultExports;
