// GENERATED by @edgedb/generate v0.5.3

import * as $ from './reflection';
declare const spec: $.introspect.Types;

declare const complexParamKinds: Set<$.TypeKind>;

export { spec, complexParamKinds };
