// GENERATED by @edgedb/generate v0.5.3

import * as $ from './reflection.mjs';
import * as _ from './imports.mjs';

const overloadDefs = {
	Infix: {
		'=': [
			{
				kind: 'Infix',
				args: [
					{ typeId: 'a64cb492-91a2-5ee0-890a-6caeb3e32aa5', optional: false, setoftype: false, variadic: false },
					{ typeId: 'a64cb492-91a2-5ee0-890a-6caeb3e32aa5', optional: false, setoftype: false, variadic: false }
				],
				returnTypeId: '00000000-0000-0000-0000-000000000109'
			},
			{
				kind: 'Infix',
				args: [
					{ typeId: '00000000-0000-0000-0000-000000000002', optional: false, setoftype: false, variadic: false },
					{ typeId: '00000000-0000-0000-0000-000000000002', optional: false, setoftype: false, variadic: false }
				],
				returnTypeId: '00000000-0000-0000-0000-000000000109'
			},
			{
				kind: 'Infix',
				args: [
					{ typeId: '00000000-0000-0000-0000-000000000109', optional: false, setoftype: false, variadic: false },
					{ typeId: '00000000-0000-0000-0000-000000000109', optional: false, setoftype: false, variadic: false }
				],
				returnTypeId: '00000000-0000-0000-0000-000000000109'
			},
			{
				kind: 'Infix',
				args: [
					{ typeId: '48896eaf-b8af-5f80-9073-0884475d6ee5', optional: false, setoftype: false, variadic: false },
					{ typeId: '48896eaf-b8af-5f80-9073-0884475d6ee5', optional: false, setoftype: false, variadic: false }
				],
				returnTypeId: '00000000-0000-0000-0000-000000000109'
			},
			{
				kind: 'Infix',
				args: [
					{ typeId: '00000000-0000-0000-0000-0000000001ff', optional: false, setoftype: false, variadic: false },
					{ typeId: '00000000-0000-0000-0000-0000000001ff', optional: false, setoftype: false, variadic: false }
				],
				returnTypeId: '00000000-0000-0000-0000-000000000109'
			},
			{
				kind: 'Infix',
				args: [
					{ typeId: '00000000-0000-0000-0000-000000000110', optional: false, setoftype: false, variadic: false },
					{ typeId: '00000000-0000-0000-0000-000000000110', optional: false, setoftype: false, variadic: false }
				],
				returnTypeId: '00000000-0000-0000-0000-000000000109'
			},
			{
				kind: 'Infix',
				args: [
					{ typeId: 'a6f5468c-c2a6-5852-8f73-57484b1c6831', optional: false, setoftype: false, variadic: false },
					{ typeId: 'a6f5468c-c2a6-5852-8f73-57484b1c6831', optional: false, setoftype: false, variadic: false }
				],
				returnTypeId: '00000000-0000-0000-0000-000000000109'
			},
			{
				kind: 'Infix',
				args: [
					{ typeId: '00000000-0000-0000-0000-000000000102', optional: false, setoftype: false, variadic: false },
					{ typeId: '00000000-0000-0000-0000-000000000102', optional: false, setoftype: false, variadic: false }
				],
				returnTypeId: '00000000-0000-0000-0000-000000000109'
			},
			{
				kind: 'Infix',
				args: [
					{ typeId: '00000000-0000-0000-0000-00000000010a', optional: false, setoftype: false, variadic: false },
					{ typeId: '00000000-0000-0000-0000-00000000010a', optional: false, setoftype: false, variadic: false }
				],
				returnTypeId: '00000000-0000-0000-0000-000000000109'
			},
			{
				kind: 'Infix',
				args: [
					{ typeId: '00000000-0000-0000-0000-00000000010e', optional: false, setoftype: false, variadic: false },
					{ typeId: '00000000-0000-0000-0000-00000000010e', optional: false, setoftype: false, variadic: false }
				],
				returnTypeId: '00000000-0000-0000-0000-000000000109'
			},
			{
				kind: 'Infix',
				args: [
					{ typeId: '00000000-0000-0000-0000-00000000010f', optional: false, setoftype: false, variadic: false },
					{ typeId: '00000000-0000-0000-0000-00000000010f', optional: false, setoftype: false, variadic: false }
				],
				returnTypeId: '00000000-0000-0000-0000-000000000109'
			},
			{
				kind: 'Infix',
				args: [
					{ typeId: '00000000-0000-0000-0000-000000000101', optional: false, setoftype: false, variadic: false },
					{ typeId: '00000000-0000-0000-0000-000000000101', optional: false, setoftype: false, variadic: false }
				],
				returnTypeId: '00000000-0000-0000-0000-000000000109'
			},
			{
				kind: 'Infix',
				args: [
					{ typeId: '00000000-0000-0000-0000-000000000100', optional: false, setoftype: false, variadic: false },
					{ typeId: '00000000-0000-0000-0000-000000000100', optional: false, setoftype: false, variadic: false }
				],
				returnTypeId: '00000000-0000-0000-0000-000000000109'
			},
			{
				kind: 'Infix',
				args: [
					{ typeId: '49748e47-8d91-5269-9a34-2e8ca194e0f2', optional: false, setoftype: false, variadic: false },
					{ typeId: '49748e47-8d91-5269-9a34-2e8ca194e0f2', optional: false, setoftype: false, variadic: false }
				],
				returnTypeId: '00000000-0000-0000-0000-000000000109'
			},
			{
				kind: 'Infix',
				args: [
					{ typeId: 'c3231f27-c8a1-5a0c-9830-c71206020eac', optional: false, setoftype: false, variadic: false },
					{ typeId: 'c3231f27-c8a1-5a0c-9830-c71206020eac', optional: false, setoftype: false, variadic: false }
				],
				returnTypeId: '00000000-0000-0000-0000-000000000109'
			},
			{
				kind: 'Infix',
				args: [
					{ typeId: '0d14e49f-d9f9-51f0-b8f4-c432982cbac2', optional: false, setoftype: false, variadic: false },
					{ typeId: '0d14e49f-d9f9-51f0-b8f4-c432982cbac2', optional: false, setoftype: false, variadic: false }
				],
				returnTypeId: '00000000-0000-0000-0000-000000000109'
			},
			{
				kind: 'Infix',
				args: [
					{ typeId: '00000000-0000-0000-0000-000000000130', optional: false, setoftype: false, variadic: false },
					{ typeId: '00000000-0000-0000-0000-000000000130', optional: false, setoftype: false, variadic: false }
				],
				returnTypeId: '00000000-0000-0000-0000-000000000109'
			},
			{
				kind: 'Infix',
				args: [
					{ typeId: '00000000-0000-0000-0000-00000000010c', optional: false, setoftype: false, variadic: false },
					{ typeId: '00000000-0000-0000-0000-00000000010c', optional: false, setoftype: false, variadic: false }
				],
				returnTypeId: '00000000-0000-0000-0000-000000000109'
			},
			{
				kind: 'Infix',
				args: [
					{ typeId: '00000000-0000-0000-0000-00000000010d', optional: false, setoftype: false, variadic: false },
					{ typeId: '00000000-0000-0000-0000-00000000010d', optional: false, setoftype: false, variadic: false }
				],
				returnTypeId: '00000000-0000-0000-0000-000000000109'
			},
			{
				kind: 'Infix',
				args: [
					{ typeId: '00000000-0000-0000-0000-000000000108', optional: false, setoftype: false, variadic: false },
					{ typeId: '15315dad-c4ad-5335-97d6-4612e66ffb71', optional: false, setoftype: false, variadic: false }
				],
				returnTypeId: '00000000-0000-0000-0000-000000000109'
			},
			{
				kind: 'Infix',
				args: [
					{ typeId: '00000000-0000-0000-0000-000000000108', optional: false, setoftype: false, variadic: false },
					{ typeId: '00000000-0000-0000-0000-000000000108', optional: false, setoftype: false, variadic: false }
				],
				returnTypeId: '00000000-0000-0000-0000-000000000109'
			},
			{
				kind: 'Infix',
				args: [
					{ typeId: '00000000-0000-0000-0000-00000000010b', optional: false, setoftype: false, variadic: false },
					{ typeId: '00000000-0000-0000-0000-00000000010b', optional: false, setoftype: false, variadic: false }
				],
				returnTypeId: '00000000-0000-0000-0000-000000000109'
			},
			{
				kind: 'Infix',
				args: [
					{ typeId: '00000000-0000-0000-0000-000000000111', optional: false, setoftype: false, variadic: false },
					{ typeId: '00000000-0000-0000-0000-000000000111', optional: false, setoftype: false, variadic: false }
				],
				returnTypeId: '00000000-0000-0000-0000-000000000109'
			}
		],
		'?=': [
			{
				kind: 'Infix',
				args: [
					{ typeId: 'a64cb492-91a2-5ee0-890a-6caeb3e32aa5', optional: true, setoftype: false, variadic: false },
					{ typeId: 'a64cb492-91a2-5ee0-890a-6caeb3e32aa5', optional: true, setoftype: false, variadic: false }
				],
				returnTypeId: '00000000-0000-0000-0000-000000000109'
			},
			{
				kind: 'Infix',
				args: [
					{ typeId: '00000000-0000-0000-0000-000000000002', optional: true, setoftype: false, variadic: false },
					{ typeId: '00000000-0000-0000-0000-000000000002', optional: true, setoftype: false, variadic: false }
				],
				returnTypeId: '00000000-0000-0000-0000-000000000109'
			},
			{
				kind: 'Infix',
				args: [
					{ typeId: '00000000-0000-0000-0000-000000000109', optional: true, setoftype: false, variadic: false },
					{ typeId: '00000000-0000-0000-0000-000000000109', optional: true, setoftype: false, variadic: false }
				],
				returnTypeId: '00000000-0000-0000-0000-000000000109'
			},
			{
				kind: 'Infix',
				args: [
					{ typeId: '48896eaf-b8af-5f80-9073-0884475d6ee5', optional: true, setoftype: false, variadic: false },
					{ typeId: '48896eaf-b8af-5f80-9073-0884475d6ee5', optional: true, setoftype: false, variadic: false }
				],
				returnTypeId: '00000000-0000-0000-0000-000000000109'
			},
			{
				kind: 'Infix',
				args: [
					{ typeId: '00000000-0000-0000-0000-0000000001ff', optional: true, setoftype: false, variadic: false },
					{ typeId: '00000000-0000-0000-0000-0000000001ff', optional: true, setoftype: false, variadic: false }
				],
				returnTypeId: '00000000-0000-0000-0000-000000000109'
			},
			{
				kind: 'Infix',
				args: [
					{ typeId: '00000000-0000-0000-0000-000000000110', optional: true, setoftype: false, variadic: false },
					{ typeId: '00000000-0000-0000-0000-000000000110', optional: true, setoftype: false, variadic: false }
				],
				returnTypeId: '00000000-0000-0000-0000-000000000109'
			},
			{
				kind: 'Infix',
				args: [
					{ typeId: 'a6f5468c-c2a6-5852-8f73-57484b1c6831', optional: true, setoftype: false, variadic: false },
					{ typeId: 'a6f5468c-c2a6-5852-8f73-57484b1c6831', optional: true, setoftype: false, variadic: false }
				],
				returnTypeId: '00000000-0000-0000-0000-000000000109'
			},
			{
				kind: 'Infix',
				args: [
					{ typeId: '00000000-0000-0000-0000-000000000102', optional: true, setoftype: false, variadic: false },
					{ typeId: '00000000-0000-0000-0000-000000000102', optional: true, setoftype: false, variadic: false }
				],
				returnTypeId: '00000000-0000-0000-0000-000000000109'
			},
			{
				kind: 'Infix',
				args: [
					{ typeId: '00000000-0000-0000-0000-00000000010a', optional: true, setoftype: false, variadic: false },
					{ typeId: '00000000-0000-0000-0000-00000000010a', optional: true, setoftype: false, variadic: false }
				],
				returnTypeId: '00000000-0000-0000-0000-000000000109'
			},
			{
				kind: 'Infix',
				args: [
					{ typeId: '00000000-0000-0000-0000-00000000010e', optional: true, setoftype: false, variadic: false },
					{ typeId: '00000000-0000-0000-0000-00000000010e', optional: true, setoftype: false, variadic: false }
				],
				returnTypeId: '00000000-0000-0000-0000-000000000109'
			},
			{
				kind: 'Infix',
				args: [
					{ typeId: '00000000-0000-0000-0000-00000000010f', optional: true, setoftype: false, variadic: false },
					{ typeId: '00000000-0000-0000-0000-00000000010f', optional: true, setoftype: false, variadic: false }
				],
				returnTypeId: '00000000-0000-0000-0000-000000000109'
			},
			{
				kind: 'Infix',
				args: [
					{ typeId: '00000000-0000-0000-0000-000000000101', optional: true, setoftype: false, variadic: false },
					{ typeId: '00000000-0000-0000-0000-000000000101', optional: true, setoftype: false, variadic: false }
				],
				returnTypeId: '00000000-0000-0000-0000-000000000109'
			},
			{
				kind: 'Infix',
				args: [
					{ typeId: '00000000-0000-0000-0000-000000000100', optional: true, setoftype: false, variadic: false },
					{ typeId: '00000000-0000-0000-0000-000000000100', optional: true, setoftype: false, variadic: false }
				],
				returnTypeId: '00000000-0000-0000-0000-000000000109'
			},
			{
				kind: 'Infix',
				args: [
					{ typeId: '49748e47-8d91-5269-9a34-2e8ca194e0f2', optional: true, setoftype: false, variadic: false },
					{ typeId: '49748e47-8d91-5269-9a34-2e8ca194e0f2', optional: true, setoftype: false, variadic: false }
				],
				returnTypeId: '00000000-0000-0000-0000-000000000109'
			},
			{
				kind: 'Infix',
				args: [
					{ typeId: 'c3231f27-c8a1-5a0c-9830-c71206020eac', optional: true, setoftype: false, variadic: false },
					{ typeId: 'c3231f27-c8a1-5a0c-9830-c71206020eac', optional: true, setoftype: false, variadic: false }
				],
				returnTypeId: '00000000-0000-0000-0000-000000000109'
			},
			{
				kind: 'Infix',
				args: [
					{ typeId: '0d14e49f-d9f9-51f0-b8f4-c432982cbac2', optional: true, setoftype: false, variadic: false },
					{ typeId: '0d14e49f-d9f9-51f0-b8f4-c432982cbac2', optional: true, setoftype: false, variadic: false }
				],
				returnTypeId: '00000000-0000-0000-0000-000000000109'
			},
			{
				kind: 'Infix',
				args: [
					{ typeId: '00000000-0000-0000-0000-000000000130', optional: true, setoftype: false, variadic: false },
					{ typeId: '00000000-0000-0000-0000-000000000130', optional: true, setoftype: false, variadic: false }
				],
				returnTypeId: '00000000-0000-0000-0000-000000000109'
			},
			{
				kind: 'Infix',
				args: [
					{ typeId: '00000000-0000-0000-0000-00000000010c', optional: true, setoftype: false, variadic: false },
					{ typeId: '00000000-0000-0000-0000-00000000010c', optional: true, setoftype: false, variadic: false }
				],
				returnTypeId: '00000000-0000-0000-0000-000000000109'
			},
			{
				kind: 'Infix',
				args: [
					{ typeId: '00000000-0000-0000-0000-00000000010d', optional: true, setoftype: false, variadic: false },
					{ typeId: '00000000-0000-0000-0000-00000000010d', optional: true, setoftype: false, variadic: false }
				],
				returnTypeId: '00000000-0000-0000-0000-000000000109'
			},
			{
				kind: 'Infix',
				args: [
					{ typeId: '00000000-0000-0000-0000-000000000108', optional: true, setoftype: false, variadic: false },
					{ typeId: '15315dad-c4ad-5335-97d6-4612e66ffb71', optional: true, setoftype: false, variadic: false }
				],
				returnTypeId: '00000000-0000-0000-0000-000000000109'
			},
			{
				kind: 'Infix',
				args: [
					{ typeId: '00000000-0000-0000-0000-000000000108', optional: true, setoftype: false, variadic: false },
					{ typeId: '00000000-0000-0000-0000-000000000108', optional: true, setoftype: false, variadic: false }
				],
				returnTypeId: '00000000-0000-0000-0000-000000000109'
			},
			{
				kind: 'Infix',
				args: [
					{ typeId: '00000000-0000-0000-0000-00000000010b', optional: true, setoftype: false, variadic: false },
					{ typeId: '00000000-0000-0000-0000-00000000010b', optional: true, setoftype: false, variadic: false }
				],
				returnTypeId: '00000000-0000-0000-0000-000000000109'
			},
			{
				kind: 'Infix',
				args: [
					{ typeId: '00000000-0000-0000-0000-000000000111', optional: true, setoftype: false, variadic: false },
					{ typeId: '00000000-0000-0000-0000-000000000111', optional: true, setoftype: false, variadic: false }
				],
				returnTypeId: '00000000-0000-0000-0000-000000000109'
			}
		],
		'!=': [
			{
				kind: 'Infix',
				args: [
					{ typeId: 'a64cb492-91a2-5ee0-890a-6caeb3e32aa5', optional: false, setoftype: false, variadic: false },
					{ typeId: 'a64cb492-91a2-5ee0-890a-6caeb3e32aa5', optional: false, setoftype: false, variadic: false }
				],
				returnTypeId: '00000000-0000-0000-0000-000000000109'
			},
			{
				kind: 'Infix',
				args: [
					{ typeId: '00000000-0000-0000-0000-000000000002', optional: false, setoftype: false, variadic: false },
					{ typeId: '00000000-0000-0000-0000-000000000002', optional: false, setoftype: false, variadic: false }
				],
				returnTypeId: '00000000-0000-0000-0000-000000000109'
			},
			{
				kind: 'Infix',
				args: [
					{ typeId: '00000000-0000-0000-0000-000000000109', optional: false, setoftype: false, variadic: false },
					{ typeId: '00000000-0000-0000-0000-000000000109', optional: false, setoftype: false, variadic: false }
				],
				returnTypeId: '00000000-0000-0000-0000-000000000109'
			},
			{
				kind: 'Infix',
				args: [
					{ typeId: '48896eaf-b8af-5f80-9073-0884475d6ee5', optional: false, setoftype: false, variadic: false },
					{ typeId: '48896eaf-b8af-5f80-9073-0884475d6ee5', optional: false, setoftype: false, variadic: false }
				],
				returnTypeId: '00000000-0000-0000-0000-000000000109'
			},
			{
				kind: 'Infix',
				args: [
					{ typeId: '00000000-0000-0000-0000-0000000001ff', optional: false, setoftype: false, variadic: false },
					{ typeId: '00000000-0000-0000-0000-0000000001ff', optional: false, setoftype: false, variadic: false }
				],
				returnTypeId: '00000000-0000-0000-0000-000000000109'
			},
			{
				kind: 'Infix',
				args: [
					{ typeId: '00000000-0000-0000-0000-000000000110', optional: false, setoftype: false, variadic: false },
					{ typeId: '00000000-0000-0000-0000-000000000110', optional: false, setoftype: false, variadic: false }
				],
				returnTypeId: '00000000-0000-0000-0000-000000000109'
			},
			{
				kind: 'Infix',
				args: [
					{ typeId: 'a6f5468c-c2a6-5852-8f73-57484b1c6831', optional: false, setoftype: false, variadic: false },
					{ typeId: 'a6f5468c-c2a6-5852-8f73-57484b1c6831', optional: false, setoftype: false, variadic: false }
				],
				returnTypeId: '00000000-0000-0000-0000-000000000109'
			},
			{
				kind: 'Infix',
				args: [
					{ typeId: '00000000-0000-0000-0000-000000000102', optional: false, setoftype: false, variadic: false },
					{ typeId: '00000000-0000-0000-0000-000000000102', optional: false, setoftype: false, variadic: false }
				],
				returnTypeId: '00000000-0000-0000-0000-000000000109'
			},
			{
				kind: 'Infix',
				args: [
					{ typeId: '00000000-0000-0000-0000-00000000010a', optional: false, setoftype: false, variadic: false },
					{ typeId: '00000000-0000-0000-0000-00000000010a', optional: false, setoftype: false, variadic: false }
				],
				returnTypeId: '00000000-0000-0000-0000-000000000109'
			},
			{
				kind: 'Infix',
				args: [
					{ typeId: '00000000-0000-0000-0000-00000000010e', optional: false, setoftype: false, variadic: false },
					{ typeId: '00000000-0000-0000-0000-00000000010e', optional: false, setoftype: false, variadic: false }
				],
				returnTypeId: '00000000-0000-0000-0000-000000000109'
			},
			{
				kind: 'Infix',
				args: [
					{ typeId: '00000000-0000-0000-0000-00000000010f', optional: false, setoftype: false, variadic: false },
					{ typeId: '00000000-0000-0000-0000-00000000010f', optional: false, setoftype: false, variadic: false }
				],
				returnTypeId: '00000000-0000-0000-0000-000000000109'
			},
			{
				kind: 'Infix',
				args: [
					{ typeId: '00000000-0000-0000-0000-000000000101', optional: false, setoftype: false, variadic: false },
					{ typeId: '00000000-0000-0000-0000-000000000101', optional: false, setoftype: false, variadic: false }
				],
				returnTypeId: '00000000-0000-0000-0000-000000000109'
			},
			{
				kind: 'Infix',
				args: [
					{ typeId: '00000000-0000-0000-0000-000000000100', optional: false, setoftype: false, variadic: false },
					{ typeId: '00000000-0000-0000-0000-000000000100', optional: false, setoftype: false, variadic: false }
				],
				returnTypeId: '00000000-0000-0000-0000-000000000109'
			},
			{
				kind: 'Infix',
				args: [
					{ typeId: '49748e47-8d91-5269-9a34-2e8ca194e0f2', optional: false, setoftype: false, variadic: false },
					{ typeId: '49748e47-8d91-5269-9a34-2e8ca194e0f2', optional: false, setoftype: false, variadic: false }
				],
				returnTypeId: '00000000-0000-0000-0000-000000000109'
			},
			{
				kind: 'Infix',
				args: [
					{ typeId: 'c3231f27-c8a1-5a0c-9830-c71206020eac', optional: false, setoftype: false, variadic: false },
					{ typeId: 'c3231f27-c8a1-5a0c-9830-c71206020eac', optional: false, setoftype: false, variadic: false }
				],
				returnTypeId: '00000000-0000-0000-0000-000000000109'
			},
			{
				kind: 'Infix',
				args: [
					{ typeId: '0d14e49f-d9f9-51f0-b8f4-c432982cbac2', optional: false, setoftype: false, variadic: false },
					{ typeId: '0d14e49f-d9f9-51f0-b8f4-c432982cbac2', optional: false, setoftype: false, variadic: false }
				],
				returnTypeId: '00000000-0000-0000-0000-000000000109'
			},
			{
				kind: 'Infix',
				args: [
					{ typeId: '00000000-0000-0000-0000-000000000130', optional: false, setoftype: false, variadic: false },
					{ typeId: '00000000-0000-0000-0000-000000000130', optional: false, setoftype: false, variadic: false }
				],
				returnTypeId: '00000000-0000-0000-0000-000000000109'
			},
			{
				kind: 'Infix',
				args: [
					{ typeId: '00000000-0000-0000-0000-00000000010c', optional: false, setoftype: false, variadic: false },
					{ typeId: '00000000-0000-0000-0000-00000000010c', optional: false, setoftype: false, variadic: false }
				],
				returnTypeId: '00000000-0000-0000-0000-000000000109'
			},
			{
				kind: 'Infix',
				args: [
					{ typeId: '00000000-0000-0000-0000-00000000010d', optional: false, setoftype: false, variadic: false },
					{ typeId: '00000000-0000-0000-0000-00000000010d', optional: false, setoftype: false, variadic: false }
				],
				returnTypeId: '00000000-0000-0000-0000-000000000109'
			},
			{
				kind: 'Infix',
				args: [
					{ typeId: '00000000-0000-0000-0000-000000000108', optional: false, setoftype: false, variadic: false },
					{ typeId: '15315dad-c4ad-5335-97d6-4612e66ffb71', optional: false, setoftype: false, variadic: false }
				],
				returnTypeId: '00000000-0000-0000-0000-000000000109'
			},
			{
				kind: 'Infix',
				args: [
					{ typeId: '00000000-0000-0000-0000-000000000108', optional: false, setoftype: false, variadic: false },
					{ typeId: '00000000-0000-0000-0000-000000000108', optional: false, setoftype: false, variadic: false }
				],
				returnTypeId: '00000000-0000-0000-0000-000000000109'
			},
			{
				kind: 'Infix',
				args: [
					{ typeId: '00000000-0000-0000-0000-00000000010b', optional: false, setoftype: false, variadic: false },
					{ typeId: '00000000-0000-0000-0000-00000000010b', optional: false, setoftype: false, variadic: false }
				],
				returnTypeId: '00000000-0000-0000-0000-000000000109'
			},
			{
				kind: 'Infix',
				args: [
					{ typeId: '00000000-0000-0000-0000-000000000111', optional: false, setoftype: false, variadic: false },
					{ typeId: '00000000-0000-0000-0000-000000000111', optional: false, setoftype: false, variadic: false }
				],
				returnTypeId: '00000000-0000-0000-0000-000000000109'
			}
		],
		'?!=': [
			{
				kind: 'Infix',
				args: [
					{ typeId: 'a64cb492-91a2-5ee0-890a-6caeb3e32aa5', optional: true, setoftype: false, variadic: false },
					{ typeId: 'a64cb492-91a2-5ee0-890a-6caeb3e32aa5', optional: true, setoftype: false, variadic: false }
				],
				returnTypeId: '00000000-0000-0000-0000-000000000109'
			},
			{
				kind: 'Infix',
				args: [
					{ typeId: '00000000-0000-0000-0000-000000000002', optional: true, setoftype: false, variadic: false },
					{ typeId: '00000000-0000-0000-0000-000000000002', optional: true, setoftype: false, variadic: false }
				],
				returnTypeId: '00000000-0000-0000-0000-000000000109'
			},
			{
				kind: 'Infix',
				args: [
					{ typeId: '00000000-0000-0000-0000-000000000109', optional: true, setoftype: false, variadic: false },
					{ typeId: '00000000-0000-0000-0000-000000000109', optional: true, setoftype: false, variadic: false }
				],
				returnTypeId: '00000000-0000-0000-0000-000000000109'
			},
			{
				kind: 'Infix',
				args: [
					{ typeId: '48896eaf-b8af-5f80-9073-0884475d6ee5', optional: true, setoftype: false, variadic: false },
					{ typeId: '48896eaf-b8af-5f80-9073-0884475d6ee5', optional: true, setoftype: false, variadic: false }
				],
				returnTypeId: '00000000-0000-0000-0000-000000000109'
			},
			{
				kind: 'Infix',
				args: [
					{ typeId: '00000000-0000-0000-0000-0000000001ff', optional: true, setoftype: false, variadic: false },
					{ typeId: '00000000-0000-0000-0000-0000000001ff', optional: true, setoftype: false, variadic: false }
				],
				returnTypeId: '00000000-0000-0000-0000-000000000109'
			},
			{
				kind: 'Infix',
				args: [
					{ typeId: '00000000-0000-0000-0000-000000000110', optional: true, setoftype: false, variadic: false },
					{ typeId: '00000000-0000-0000-0000-000000000110', optional: true, setoftype: false, variadic: false }
				],
				returnTypeId: '00000000-0000-0000-0000-000000000109'
			},
			{
				kind: 'Infix',
				args: [
					{ typeId: '00000000-0000-0000-0000-000000000102', optional: true, setoftype: false, variadic: false },
					{ typeId: '00000000-0000-0000-0000-000000000102', optional: true, setoftype: false, variadic: false }
				],
				returnTypeId: '00000000-0000-0000-0000-000000000109'
			},
			{
				kind: 'Infix',
				args: [
					{ typeId: 'a6f5468c-c2a6-5852-8f73-57484b1c6831', optional: true, setoftype: false, variadic: false },
					{ typeId: 'a6f5468c-c2a6-5852-8f73-57484b1c6831', optional: true, setoftype: false, variadic: false }
				],
				returnTypeId: '00000000-0000-0000-0000-000000000109'
			},
			{
				kind: 'Infix',
				args: [
					{ typeId: '00000000-0000-0000-0000-00000000010a', optional: true, setoftype: false, variadic: false },
					{ typeId: '00000000-0000-0000-0000-00000000010a', optional: true, setoftype: false, variadic: false }
				],
				returnTypeId: '00000000-0000-0000-0000-000000000109'
			},
			{
				kind: 'Infix',
				args: [
					{ typeId: '00000000-0000-0000-0000-00000000010e', optional: true, setoftype: false, variadic: false },
					{ typeId: '00000000-0000-0000-0000-00000000010e', optional: true, setoftype: false, variadic: false }
				],
				returnTypeId: '00000000-0000-0000-0000-000000000109'
			},
			{
				kind: 'Infix',
				args: [
					{ typeId: '00000000-0000-0000-0000-00000000010f', optional: true, setoftype: false, variadic: false },
					{ typeId: '00000000-0000-0000-0000-00000000010f', optional: true, setoftype: false, variadic: false }
				],
				returnTypeId: '00000000-0000-0000-0000-000000000109'
			},
			{
				kind: 'Infix',
				args: [
					{ typeId: '00000000-0000-0000-0000-000000000101', optional: true, setoftype: false, variadic: false },
					{ typeId: '00000000-0000-0000-0000-000000000101', optional: true, setoftype: false, variadic: false }
				],
				returnTypeId: '00000000-0000-0000-0000-000000000109'
			},
			{
				kind: 'Infix',
				args: [
					{ typeId: '00000000-0000-0000-0000-000000000100', optional: true, setoftype: false, variadic: false },
					{ typeId: '00000000-0000-0000-0000-000000000100', optional: true, setoftype: false, variadic: false }
				],
				returnTypeId: '00000000-0000-0000-0000-000000000109'
			},
			{
				kind: 'Infix',
				args: [
					{ typeId: '49748e47-8d91-5269-9a34-2e8ca194e0f2', optional: true, setoftype: false, variadic: false },
					{ typeId: '49748e47-8d91-5269-9a34-2e8ca194e0f2', optional: true, setoftype: false, variadic: false }
				],
				returnTypeId: '00000000-0000-0000-0000-000000000109'
			},
			{
				kind: 'Infix',
				args: [
					{ typeId: 'c3231f27-c8a1-5a0c-9830-c71206020eac', optional: true, setoftype: false, variadic: false },
					{ typeId: 'c3231f27-c8a1-5a0c-9830-c71206020eac', optional: true, setoftype: false, variadic: false }
				],
				returnTypeId: '00000000-0000-0000-0000-000000000109'
			},
			{
				kind: 'Infix',
				args: [
					{ typeId: '0d14e49f-d9f9-51f0-b8f4-c432982cbac2', optional: true, setoftype: false, variadic: false },
					{ typeId: '0d14e49f-d9f9-51f0-b8f4-c432982cbac2', optional: true, setoftype: false, variadic: false }
				],
				returnTypeId: '00000000-0000-0000-0000-000000000109'
			},
			{
				kind: 'Infix',
				args: [
					{ typeId: '00000000-0000-0000-0000-000000000130', optional: true, setoftype: false, variadic: false },
					{ typeId: '00000000-0000-0000-0000-000000000130', optional: true, setoftype: false, variadic: false }
				],
				returnTypeId: '00000000-0000-0000-0000-000000000109'
			},
			{
				kind: 'Infix',
				args: [
					{ typeId: '00000000-0000-0000-0000-00000000010c', optional: true, setoftype: false, variadic: false },
					{ typeId: '00000000-0000-0000-0000-00000000010c', optional: true, setoftype: false, variadic: false }
				],
				returnTypeId: '00000000-0000-0000-0000-000000000109'
			},
			{
				kind: 'Infix',
				args: [
					{ typeId: '00000000-0000-0000-0000-00000000010d', optional: true, setoftype: false, variadic: false },
					{ typeId: '00000000-0000-0000-0000-00000000010d', optional: true, setoftype: false, variadic: false }
				],
				returnTypeId: '00000000-0000-0000-0000-000000000109'
			},
			{
				kind: 'Infix',
				args: [
					{ typeId: '00000000-0000-0000-0000-000000000108', optional: true, setoftype: false, variadic: false },
					{ typeId: '15315dad-c4ad-5335-97d6-4612e66ffb71', optional: true, setoftype: false, variadic: false }
				],
				returnTypeId: '00000000-0000-0000-0000-000000000109'
			},
			{
				kind: 'Infix',
				args: [
					{ typeId: '00000000-0000-0000-0000-000000000108', optional: true, setoftype: false, variadic: false },
					{ typeId: '00000000-0000-0000-0000-000000000108', optional: true, setoftype: false, variadic: false }
				],
				returnTypeId: '00000000-0000-0000-0000-000000000109'
			},
			{
				kind: 'Infix',
				args: [
					{ typeId: '00000000-0000-0000-0000-00000000010b', optional: true, setoftype: false, variadic: false },
					{ typeId: '00000000-0000-0000-0000-00000000010b', optional: true, setoftype: false, variadic: false }
				],
				returnTypeId: '00000000-0000-0000-0000-000000000109'
			},
			{
				kind: 'Infix',
				args: [
					{ typeId: '00000000-0000-0000-0000-000000000111', optional: true, setoftype: false, variadic: false },
					{ typeId: '00000000-0000-0000-0000-000000000111', optional: true, setoftype: false, variadic: false }
				],
				returnTypeId: '00000000-0000-0000-0000-000000000109'
			}
		],
		'>=': [
			{
				kind: 'Infix',
				args: [
					{ typeId: 'a64cb492-91a2-5ee0-890a-6caeb3e32aa5', optional: false, setoftype: false, variadic: false },
					{ typeId: 'a64cb492-91a2-5ee0-890a-6caeb3e32aa5', optional: false, setoftype: false, variadic: false }
				],
				returnTypeId: '00000000-0000-0000-0000-000000000109'
			},
			{
				kind: 'Infix',
				args: [
					{ typeId: '00000000-0000-0000-0000-000000000002', optional: false, setoftype: false, variadic: false },
					{ typeId: '00000000-0000-0000-0000-000000000002', optional: false, setoftype: false, variadic: false }
				],
				returnTypeId: '00000000-0000-0000-0000-000000000109'
			},
			{
				kind: 'Infix',
				args: [
					{ typeId: '00000000-0000-0000-0000-000000000109', optional: false, setoftype: false, variadic: false },
					{ typeId: '00000000-0000-0000-0000-000000000109', optional: false, setoftype: false, variadic: false }
				],
				returnTypeId: '00000000-0000-0000-0000-000000000109'
			},
			{
				kind: 'Infix',
				args: [
					{ typeId: '48896eaf-b8af-5f80-9073-0884475d6ee5', optional: false, setoftype: false, variadic: false },
					{ typeId: '48896eaf-b8af-5f80-9073-0884475d6ee5', optional: false, setoftype: false, variadic: false }
				],
				returnTypeId: '00000000-0000-0000-0000-000000000109'
			},
			{
				kind: 'Infix',
				args: [
					{ typeId: '00000000-0000-0000-0000-0000000001ff', optional: false, setoftype: false, variadic: false },
					{ typeId: '00000000-0000-0000-0000-0000000001ff', optional: false, setoftype: false, variadic: false }
				],
				returnTypeId: '00000000-0000-0000-0000-000000000109'
			},
			{
				kind: 'Infix',
				args: [
					{ typeId: '00000000-0000-0000-0000-000000000110', optional: false, setoftype: false, variadic: false },
					{ typeId: '00000000-0000-0000-0000-000000000110', optional: false, setoftype: false, variadic: false }
				],
				returnTypeId: '00000000-0000-0000-0000-000000000109'
			},
			{
				kind: 'Infix',
				args: [
					{ typeId: 'a6f5468c-c2a6-5852-8f73-57484b1c6831', optional: false, setoftype: false, variadic: false },
					{ typeId: 'a6f5468c-c2a6-5852-8f73-57484b1c6831', optional: false, setoftype: false, variadic: false }
				],
				returnTypeId: '00000000-0000-0000-0000-000000000109'
			},
			{
				kind: 'Infix',
				args: [
					{ typeId: '00000000-0000-0000-0000-000000000102', optional: false, setoftype: false, variadic: false },
					{ typeId: '00000000-0000-0000-0000-000000000102', optional: false, setoftype: false, variadic: false }
				],
				returnTypeId: '00000000-0000-0000-0000-000000000109'
			},
			{
				kind: 'Infix',
				args: [
					{ typeId: '00000000-0000-0000-0000-00000000010a', optional: false, setoftype: false, variadic: false },
					{ typeId: '00000000-0000-0000-0000-00000000010a', optional: false, setoftype: false, variadic: false }
				],
				returnTypeId: '00000000-0000-0000-0000-000000000109'
			},
			{
				kind: 'Infix',
				args: [
					{ typeId: '00000000-0000-0000-0000-00000000010e', optional: false, setoftype: false, variadic: false },
					{ typeId: '00000000-0000-0000-0000-00000000010e', optional: false, setoftype: false, variadic: false }
				],
				returnTypeId: '00000000-0000-0000-0000-000000000109'
			},
			{
				kind: 'Infix',
				args: [
					{ typeId: '00000000-0000-0000-0000-00000000010f', optional: false, setoftype: false, variadic: false },
					{ typeId: '00000000-0000-0000-0000-00000000010f', optional: false, setoftype: false, variadic: false }
				],
				returnTypeId: '00000000-0000-0000-0000-000000000109'
			},
			{
				kind: 'Infix',
				args: [
					{ typeId: '00000000-0000-0000-0000-000000000101', optional: false, setoftype: false, variadic: false },
					{ typeId: '00000000-0000-0000-0000-000000000101', optional: false, setoftype: false, variadic: false }
				],
				returnTypeId: '00000000-0000-0000-0000-000000000109'
			},
			{
				kind: 'Infix',
				args: [
					{ typeId: '00000000-0000-0000-0000-000000000100', optional: false, setoftype: false, variadic: false },
					{ typeId: '00000000-0000-0000-0000-000000000100', optional: false, setoftype: false, variadic: false }
				],
				returnTypeId: '00000000-0000-0000-0000-000000000109'
			},
			{
				kind: 'Infix',
				args: [
					{ typeId: '49748e47-8d91-5269-9a34-2e8ca194e0f2', optional: false, setoftype: false, variadic: false },
					{ typeId: '49748e47-8d91-5269-9a34-2e8ca194e0f2', optional: false, setoftype: false, variadic: false }
				],
				returnTypeId: '00000000-0000-0000-0000-000000000109'
			},
			{
				kind: 'Infix',
				args: [
					{ typeId: 'c3231f27-c8a1-5a0c-9830-c71206020eac', optional: false, setoftype: false, variadic: false },
					{ typeId: 'c3231f27-c8a1-5a0c-9830-c71206020eac', optional: false, setoftype: false, variadic: false }
				],
				returnTypeId: '00000000-0000-0000-0000-000000000109'
			},
			{
				kind: 'Infix',
				args: [
					{ typeId: '0d14e49f-d9f9-51f0-b8f4-c432982cbac2', optional: false, setoftype: false, variadic: false },
					{ typeId: '0d14e49f-d9f9-51f0-b8f4-c432982cbac2', optional: false, setoftype: false, variadic: false }
				],
				returnTypeId: '00000000-0000-0000-0000-000000000109'
			},
			{
				kind: 'Infix',
				args: [
					{ typeId: '00000000-0000-0000-0000-000000000130', optional: false, setoftype: false, variadic: false },
					{ typeId: '00000000-0000-0000-0000-000000000130', optional: false, setoftype: false, variadic: false }
				],
				returnTypeId: '00000000-0000-0000-0000-000000000109'
			},
			{
				kind: 'Infix',
				args: [
					{ typeId: '00000000-0000-0000-0000-00000000010c', optional: false, setoftype: false, variadic: false },
					{ typeId: '00000000-0000-0000-0000-00000000010c', optional: false, setoftype: false, variadic: false }
				],
				returnTypeId: '00000000-0000-0000-0000-000000000109'
			},
			{
				kind: 'Infix',
				args: [
					{ typeId: '00000000-0000-0000-0000-00000000010d', optional: false, setoftype: false, variadic: false },
					{ typeId: '00000000-0000-0000-0000-00000000010d', optional: false, setoftype: false, variadic: false }
				],
				returnTypeId: '00000000-0000-0000-0000-000000000109'
			},
			{
				kind: 'Infix',
				args: [
					{ typeId: '15315dad-c4ad-5335-97d6-4612e66ffb71', optional: false, setoftype: false, variadic: false },
					{ typeId: '00000000-0000-0000-0000-000000000108', optional: false, setoftype: false, variadic: false }
				],
				returnTypeId: '00000000-0000-0000-0000-000000000109'
			},
			{
				kind: 'Infix',
				args: [
					{ typeId: '00000000-0000-0000-0000-000000000108', optional: false, setoftype: false, variadic: false },
					{ typeId: '00000000-0000-0000-0000-000000000108', optional: false, setoftype: false, variadic: false }
				],
				returnTypeId: '00000000-0000-0000-0000-000000000109'
			},
			{
				kind: 'Infix',
				args: [
					{ typeId: '00000000-0000-0000-0000-00000000010b', optional: false, setoftype: false, variadic: false },
					{ typeId: '00000000-0000-0000-0000-00000000010b', optional: false, setoftype: false, variadic: false }
				],
				returnTypeId: '00000000-0000-0000-0000-000000000109'
			},
			{
				kind: 'Infix',
				args: [
					{ typeId: '00000000-0000-0000-0000-000000000111', optional: false, setoftype: false, variadic: false },
					{ typeId: '00000000-0000-0000-0000-000000000111', optional: false, setoftype: false, variadic: false }
				],
				returnTypeId: '00000000-0000-0000-0000-000000000109'
			}
		],
		'>': [
			{
				kind: 'Infix',
				args: [
					{ typeId: 'a64cb492-91a2-5ee0-890a-6caeb3e32aa5', optional: false, setoftype: false, variadic: false },
					{ typeId: 'a64cb492-91a2-5ee0-890a-6caeb3e32aa5', optional: false, setoftype: false, variadic: false }
				],
				returnTypeId: '00000000-0000-0000-0000-000000000109'
			},
			{
				kind: 'Infix',
				args: [
					{ typeId: '00000000-0000-0000-0000-000000000002', optional: false, setoftype: false, variadic: false },
					{ typeId: '00000000-0000-0000-0000-000000000002', optional: false, setoftype: false, variadic: false }
				],
				returnTypeId: '00000000-0000-0000-0000-000000000109'
			},
			{
				kind: 'Infix',
				args: [
					{ typeId: '00000000-0000-0000-0000-000000000109', optional: false, setoftype: false, variadic: false },
					{ typeId: '00000000-0000-0000-0000-000000000109', optional: false, setoftype: false, variadic: false }
				],
				returnTypeId: '00000000-0000-0000-0000-000000000109'
			},
			{
				kind: 'Infix',
				args: [
					{ typeId: '48896eaf-b8af-5f80-9073-0884475d6ee5', optional: false, setoftype: false, variadic: false },
					{ typeId: '48896eaf-b8af-5f80-9073-0884475d6ee5', optional: false, setoftype: false, variadic: false }
				],
				returnTypeId: '00000000-0000-0000-0000-000000000109'
			},
			{
				kind: 'Infix',
				args: [
					{ typeId: '00000000-0000-0000-0000-0000000001ff', optional: false, setoftype: false, variadic: false },
					{ typeId: '00000000-0000-0000-0000-0000000001ff', optional: false, setoftype: false, variadic: false }
				],
				returnTypeId: '00000000-0000-0000-0000-000000000109'
			},
			{
				kind: 'Infix',
				args: [
					{ typeId: '00000000-0000-0000-0000-000000000110', optional: false, setoftype: false, variadic: false },
					{ typeId: '00000000-0000-0000-0000-000000000110', optional: false, setoftype: false, variadic: false }
				],
				returnTypeId: '00000000-0000-0000-0000-000000000109'
			},
			{
				kind: 'Infix',
				args: [
					{ typeId: 'a6f5468c-c2a6-5852-8f73-57484b1c6831', optional: false, setoftype: false, variadic: false },
					{ typeId: 'a6f5468c-c2a6-5852-8f73-57484b1c6831', optional: false, setoftype: false, variadic: false }
				],
				returnTypeId: '00000000-0000-0000-0000-000000000109'
			},
			{
				kind: 'Infix',
				args: [
					{ typeId: '00000000-0000-0000-0000-000000000102', optional: false, setoftype: false, variadic: false },
					{ typeId: '00000000-0000-0000-0000-000000000102', optional: false, setoftype: false, variadic: false }
				],
				returnTypeId: '00000000-0000-0000-0000-000000000109'
			},
			{
				kind: 'Infix',
				args: [
					{ typeId: '00000000-0000-0000-0000-00000000010a', optional: false, setoftype: false, variadic: false },
					{ typeId: '00000000-0000-0000-0000-00000000010a', optional: false, setoftype: false, variadic: false }
				],
				returnTypeId: '00000000-0000-0000-0000-000000000109'
			},
			{
				kind: 'Infix',
				args: [
					{ typeId: '00000000-0000-0000-0000-00000000010e', optional: false, setoftype: false, variadic: false },
					{ typeId: '00000000-0000-0000-0000-00000000010e', optional: false, setoftype: false, variadic: false }
				],
				returnTypeId: '00000000-0000-0000-0000-000000000109'
			},
			{
				kind: 'Infix',
				args: [
					{ typeId: '00000000-0000-0000-0000-00000000010f', optional: false, setoftype: false, variadic: false },
					{ typeId: '00000000-0000-0000-0000-00000000010f', optional: false, setoftype: false, variadic: false }
				],
				returnTypeId: '00000000-0000-0000-0000-000000000109'
			},
			{
				kind: 'Infix',
				args: [
					{ typeId: '00000000-0000-0000-0000-000000000101', optional: false, setoftype: false, variadic: false },
					{ typeId: '00000000-0000-0000-0000-000000000101', optional: false, setoftype: false, variadic: false }
				],
				returnTypeId: '00000000-0000-0000-0000-000000000109'
			},
			{
				kind: 'Infix',
				args: [
					{ typeId: '00000000-0000-0000-0000-000000000100', optional: false, setoftype: false, variadic: false },
					{ typeId: '00000000-0000-0000-0000-000000000100', optional: false, setoftype: false, variadic: false }
				],
				returnTypeId: '00000000-0000-0000-0000-000000000109'
			},
			{
				kind: 'Infix',
				args: [
					{ typeId: '49748e47-8d91-5269-9a34-2e8ca194e0f2', optional: false, setoftype: false, variadic: false },
					{ typeId: '49748e47-8d91-5269-9a34-2e8ca194e0f2', optional: false, setoftype: false, variadic: false }
				],
				returnTypeId: '00000000-0000-0000-0000-000000000109'
			},
			{
				kind: 'Infix',
				args: [
					{ typeId: 'c3231f27-c8a1-5a0c-9830-c71206020eac', optional: false, setoftype: false, variadic: false },
					{ typeId: 'c3231f27-c8a1-5a0c-9830-c71206020eac', optional: false, setoftype: false, variadic: false }
				],
				returnTypeId: '00000000-0000-0000-0000-000000000109'
			},
			{
				kind: 'Infix',
				args: [
					{ typeId: '0d14e49f-d9f9-51f0-b8f4-c432982cbac2', optional: false, setoftype: false, variadic: false },
					{ typeId: '0d14e49f-d9f9-51f0-b8f4-c432982cbac2', optional: false, setoftype: false, variadic: false }
				],
				returnTypeId: '00000000-0000-0000-0000-000000000109'
			},
			{
				kind: 'Infix',
				args: [
					{ typeId: '00000000-0000-0000-0000-000000000130', optional: false, setoftype: false, variadic: false },
					{ typeId: '00000000-0000-0000-0000-000000000130', optional: false, setoftype: false, variadic: false }
				],
				returnTypeId: '00000000-0000-0000-0000-000000000109'
			},
			{
				kind: 'Infix',
				args: [
					{ typeId: '00000000-0000-0000-0000-00000000010c', optional: false, setoftype: false, variadic: false },
					{ typeId: '00000000-0000-0000-0000-00000000010c', optional: false, setoftype: false, variadic: false }
				],
				returnTypeId: '00000000-0000-0000-0000-000000000109'
			},
			{
				kind: 'Infix',
				args: [
					{ typeId: '00000000-0000-0000-0000-00000000010d', optional: false, setoftype: false, variadic: false },
					{ typeId: '00000000-0000-0000-0000-00000000010d', optional: false, setoftype: false, variadic: false }
				],
				returnTypeId: '00000000-0000-0000-0000-000000000109'
			},
			{
				kind: 'Infix',
				args: [
					{ typeId: '15315dad-c4ad-5335-97d6-4612e66ffb71', optional: false, setoftype: false, variadic: false },
					{ typeId: '00000000-0000-0000-0000-000000000108', optional: false, setoftype: false, variadic: false }
				],
				returnTypeId: '00000000-0000-0000-0000-000000000109'
			},
			{
				kind: 'Infix',
				args: [
					{ typeId: '00000000-0000-0000-0000-000000000108', optional: false, setoftype: false, variadic: false },
					{ typeId: '00000000-0000-0000-0000-000000000108', optional: false, setoftype: false, variadic: false }
				],
				returnTypeId: '00000000-0000-0000-0000-000000000109'
			},
			{
				kind: 'Infix',
				args: [
					{ typeId: '00000000-0000-0000-0000-00000000010b', optional: false, setoftype: false, variadic: false },
					{ typeId: '00000000-0000-0000-0000-00000000010b', optional: false, setoftype: false, variadic: false }
				],
				returnTypeId: '00000000-0000-0000-0000-000000000109'
			},
			{
				kind: 'Infix',
				args: [
					{ typeId: '00000000-0000-0000-0000-000000000111', optional: false, setoftype: false, variadic: false },
					{ typeId: '00000000-0000-0000-0000-000000000111', optional: false, setoftype: false, variadic: false }
				],
				returnTypeId: '00000000-0000-0000-0000-000000000109'
			}
		],
		'<=': [
			{
				kind: 'Infix',
				args: [
					{ typeId: 'a64cb492-91a2-5ee0-890a-6caeb3e32aa5', optional: false, setoftype: false, variadic: false },
					{ typeId: 'a64cb492-91a2-5ee0-890a-6caeb3e32aa5', optional: false, setoftype: false, variadic: false }
				],
				returnTypeId: '00000000-0000-0000-0000-000000000109'
			},
			{
				kind: 'Infix',
				args: [
					{ typeId: '00000000-0000-0000-0000-000000000002', optional: false, setoftype: false, variadic: false },
					{ typeId: '00000000-0000-0000-0000-000000000002', optional: false, setoftype: false, variadic: false }
				],
				returnTypeId: '00000000-0000-0000-0000-000000000109'
			},
			{
				kind: 'Infix',
				args: [
					{ typeId: '00000000-0000-0000-0000-000000000109', optional: false, setoftype: false, variadic: false },
					{ typeId: '00000000-0000-0000-0000-000000000109', optional: false, setoftype: false, variadic: false }
				],
				returnTypeId: '00000000-0000-0000-0000-000000000109'
			},
			{
				kind: 'Infix',
				args: [
					{ typeId: '48896eaf-b8af-5f80-9073-0884475d6ee5', optional: false, setoftype: false, variadic: false },
					{ typeId: '48896eaf-b8af-5f80-9073-0884475d6ee5', optional: false, setoftype: false, variadic: false }
				],
				returnTypeId: '00000000-0000-0000-0000-000000000109'
			},
			{
				kind: 'Infix',
				args: [
					{ typeId: '00000000-0000-0000-0000-0000000001ff', optional: false, setoftype: false, variadic: false },
					{ typeId: '00000000-0000-0000-0000-0000000001ff', optional: false, setoftype: false, variadic: false }
				],
				returnTypeId: '00000000-0000-0000-0000-000000000109'
			},
			{
				kind: 'Infix',
				args: [
					{ typeId: '00000000-0000-0000-0000-000000000110', optional: false, setoftype: false, variadic: false },
					{ typeId: '00000000-0000-0000-0000-000000000110', optional: false, setoftype: false, variadic: false }
				],
				returnTypeId: '00000000-0000-0000-0000-000000000109'
			},
			{
				kind: 'Infix',
				args: [
					{ typeId: 'a6f5468c-c2a6-5852-8f73-57484b1c6831', optional: false, setoftype: false, variadic: false },
					{ typeId: 'a6f5468c-c2a6-5852-8f73-57484b1c6831', optional: false, setoftype: false, variadic: false }
				],
				returnTypeId: '00000000-0000-0000-0000-000000000109'
			},
			{
				kind: 'Infix',
				args: [
					{ typeId: '00000000-0000-0000-0000-000000000102', optional: false, setoftype: false, variadic: false },
					{ typeId: '00000000-0000-0000-0000-000000000102', optional: false, setoftype: false, variadic: false }
				],
				returnTypeId: '00000000-0000-0000-0000-000000000109'
			},
			{
				kind: 'Infix',
				args: [
					{ typeId: '00000000-0000-0000-0000-00000000010a', optional: false, setoftype: false, variadic: false },
					{ typeId: '00000000-0000-0000-0000-00000000010a', optional: false, setoftype: false, variadic: false }
				],
				returnTypeId: '00000000-0000-0000-0000-000000000109'
			},
			{
				kind: 'Infix',
				args: [
					{ typeId: '00000000-0000-0000-0000-00000000010e', optional: false, setoftype: false, variadic: false },
					{ typeId: '00000000-0000-0000-0000-00000000010e', optional: false, setoftype: false, variadic: false }
				],
				returnTypeId: '00000000-0000-0000-0000-000000000109'
			},
			{
				kind: 'Infix',
				args: [
					{ typeId: '00000000-0000-0000-0000-00000000010f', optional: false, setoftype: false, variadic: false },
					{ typeId: '00000000-0000-0000-0000-00000000010f', optional: false, setoftype: false, variadic: false }
				],
				returnTypeId: '00000000-0000-0000-0000-000000000109'
			},
			{
				kind: 'Infix',
				args: [
					{ typeId: 'c3231f27-c8a1-5a0c-9830-c71206020eac', optional: false, setoftype: false, variadic: false },
					{ typeId: 'c3231f27-c8a1-5a0c-9830-c71206020eac', optional: false, setoftype: false, variadic: false }
				],
				returnTypeId: '00000000-0000-0000-0000-000000000109'
			},
			{
				kind: 'Infix',
				args: [
					{ typeId: '00000000-0000-0000-0000-000000000101', optional: false, setoftype: false, variadic: false },
					{ typeId: '00000000-0000-0000-0000-000000000101', optional: false, setoftype: false, variadic: false }
				],
				returnTypeId: '00000000-0000-0000-0000-000000000109'
			},
			{
				kind: 'Infix',
				args: [
					{ typeId: '00000000-0000-0000-0000-000000000100', optional: false, setoftype: false, variadic: false },
					{ typeId: '00000000-0000-0000-0000-000000000100', optional: false, setoftype: false, variadic: false }
				],
				returnTypeId: '00000000-0000-0000-0000-000000000109'
			},
			{
				kind: 'Infix',
				args: [
					{ typeId: '49748e47-8d91-5269-9a34-2e8ca194e0f2', optional: false, setoftype: false, variadic: false },
					{ typeId: '49748e47-8d91-5269-9a34-2e8ca194e0f2', optional: false, setoftype: false, variadic: false }
				],
				returnTypeId: '00000000-0000-0000-0000-000000000109'
			},
			{
				kind: 'Infix',
				args: [
					{ typeId: '0d14e49f-d9f9-51f0-b8f4-c432982cbac2', optional: false, setoftype: false, variadic: false },
					{ typeId: '0d14e49f-d9f9-51f0-b8f4-c432982cbac2', optional: false, setoftype: false, variadic: false }
				],
				returnTypeId: '00000000-0000-0000-0000-000000000109'
			},
			{
				kind: 'Infix',
				args: [
					{ typeId: '00000000-0000-0000-0000-000000000130', optional: false, setoftype: false, variadic: false },
					{ typeId: '00000000-0000-0000-0000-000000000130', optional: false, setoftype: false, variadic: false }
				],
				returnTypeId: '00000000-0000-0000-0000-000000000109'
			},
			{
				kind: 'Infix',
				args: [
					{ typeId: '00000000-0000-0000-0000-00000000010c', optional: false, setoftype: false, variadic: false },
					{ typeId: '00000000-0000-0000-0000-00000000010c', optional: false, setoftype: false, variadic: false }
				],
				returnTypeId: '00000000-0000-0000-0000-000000000109'
			},
			{
				kind: 'Infix',
				args: [
					{ typeId: '00000000-0000-0000-0000-00000000010d', optional: false, setoftype: false, variadic: false },
					{ typeId: '00000000-0000-0000-0000-00000000010d', optional: false, setoftype: false, variadic: false }
				],
				returnTypeId: '00000000-0000-0000-0000-000000000109'
			},
			{
				kind: 'Infix',
				args: [
					{ typeId: '15315dad-c4ad-5335-97d6-4612e66ffb71', optional: false, setoftype: false, variadic: false },
					{ typeId: '00000000-0000-0000-0000-000000000108', optional: false, setoftype: false, variadic: false }
				],
				returnTypeId: '00000000-0000-0000-0000-000000000109'
			},
			{
				kind: 'Infix',
				args: [
					{ typeId: '00000000-0000-0000-0000-000000000108', optional: false, setoftype: false, variadic: false },
					{ typeId: '00000000-0000-0000-0000-000000000108', optional: false, setoftype: false, variadic: false }
				],
				returnTypeId: '00000000-0000-0000-0000-000000000109'
			},
			{
				kind: 'Infix',
				args: [
					{ typeId: '00000000-0000-0000-0000-00000000010b', optional: false, setoftype: false, variadic: false },
					{ typeId: '00000000-0000-0000-0000-00000000010b', optional: false, setoftype: false, variadic: false }
				],
				returnTypeId: '00000000-0000-0000-0000-000000000109'
			},
			{
				kind: 'Infix',
				args: [
					{ typeId: '00000000-0000-0000-0000-000000000111', optional: false, setoftype: false, variadic: false },
					{ typeId: '00000000-0000-0000-0000-000000000111', optional: false, setoftype: false, variadic: false }
				],
				returnTypeId: '00000000-0000-0000-0000-000000000109'
			}
		],
		'<': [
			{
				kind: 'Infix',
				args: [
					{ typeId: 'a64cb492-91a2-5ee0-890a-6caeb3e32aa5', optional: false, setoftype: false, variadic: false },
					{ typeId: 'a64cb492-91a2-5ee0-890a-6caeb3e32aa5', optional: false, setoftype: false, variadic: false }
				],
				returnTypeId: '00000000-0000-0000-0000-000000000109'
			},
			{
				kind: 'Infix',
				args: [
					{ typeId: '00000000-0000-0000-0000-000000000002', optional: false, setoftype: false, variadic: false },
					{ typeId: '00000000-0000-0000-0000-000000000002', optional: false, setoftype: false, variadic: false }
				],
				returnTypeId: '00000000-0000-0000-0000-000000000109'
			},
			{
				kind: 'Infix',
				args: [
					{ typeId: '00000000-0000-0000-0000-000000000109', optional: false, setoftype: false, variadic: false },
					{ typeId: '00000000-0000-0000-0000-000000000109', optional: false, setoftype: false, variadic: false }
				],
				returnTypeId: '00000000-0000-0000-0000-000000000109'
			},
			{
				kind: 'Infix',
				args: [
					{ typeId: '48896eaf-b8af-5f80-9073-0884475d6ee5', optional: false, setoftype: false, variadic: false },
					{ typeId: '48896eaf-b8af-5f80-9073-0884475d6ee5', optional: false, setoftype: false, variadic: false }
				],
				returnTypeId: '00000000-0000-0000-0000-000000000109'
			},
			{
				kind: 'Infix',
				args: [
					{ typeId: '00000000-0000-0000-0000-0000000001ff', optional: false, setoftype: false, variadic: false },
					{ typeId: '00000000-0000-0000-0000-0000000001ff', optional: false, setoftype: false, variadic: false }
				],
				returnTypeId: '00000000-0000-0000-0000-000000000109'
			},
			{
				kind: 'Infix',
				args: [
					{ typeId: '00000000-0000-0000-0000-000000000110', optional: false, setoftype: false, variadic: false },
					{ typeId: '00000000-0000-0000-0000-000000000110', optional: false, setoftype: false, variadic: false }
				],
				returnTypeId: '00000000-0000-0000-0000-000000000109'
			},
			{
				kind: 'Infix',
				args: [
					{ typeId: 'a6f5468c-c2a6-5852-8f73-57484b1c6831', optional: false, setoftype: false, variadic: false },
					{ typeId: 'a6f5468c-c2a6-5852-8f73-57484b1c6831', optional: false, setoftype: false, variadic: false }
				],
				returnTypeId: '00000000-0000-0000-0000-000000000109'
			},
			{
				kind: 'Infix',
				args: [
					{ typeId: '00000000-0000-0000-0000-000000000102', optional: false, setoftype: false, variadic: false },
					{ typeId: '00000000-0000-0000-0000-000000000102', optional: false, setoftype: false, variadic: false }
				],
				returnTypeId: '00000000-0000-0000-0000-000000000109'
			},
			{
				kind: 'Infix',
				args: [
					{ typeId: '00000000-0000-0000-0000-00000000010a', optional: false, setoftype: false, variadic: false },
					{ typeId: '00000000-0000-0000-0000-00000000010a', optional: false, setoftype: false, variadic: false }
				],
				returnTypeId: '00000000-0000-0000-0000-000000000109'
			},
			{
				kind: 'Infix',
				args: [
					{ typeId: '00000000-0000-0000-0000-00000000010e', optional: false, setoftype: false, variadic: false },
					{ typeId: '00000000-0000-0000-0000-00000000010e', optional: false, setoftype: false, variadic: false }
				],
				returnTypeId: '00000000-0000-0000-0000-000000000109'
			},
			{
				kind: 'Infix',
				args: [
					{ typeId: '00000000-0000-0000-0000-00000000010f', optional: false, setoftype: false, variadic: false },
					{ typeId: '00000000-0000-0000-0000-00000000010f', optional: false, setoftype: false, variadic: false }
				],
				returnTypeId: '00000000-0000-0000-0000-000000000109'
			},
			{
				kind: 'Infix',
				args: [
					{ typeId: 'c3231f27-c8a1-5a0c-9830-c71206020eac', optional: false, setoftype: false, variadic: false },
					{ typeId: 'c3231f27-c8a1-5a0c-9830-c71206020eac', optional: false, setoftype: false, variadic: false }
				],
				returnTypeId: '00000000-0000-0000-0000-000000000109'
			},
			{
				kind: 'Infix',
				args: [
					{ typeId: '00000000-0000-0000-0000-000000000101', optional: false, setoftype: false, variadic: false },
					{ typeId: '00000000-0000-0000-0000-000000000101', optional: false, setoftype: false, variadic: false }
				],
				returnTypeId: '00000000-0000-0000-0000-000000000109'
			},
			{
				kind: 'Infix',
				args: [
					{ typeId: '00000000-0000-0000-0000-000000000100', optional: false, setoftype: false, variadic: false },
					{ typeId: '00000000-0000-0000-0000-000000000100', optional: false, setoftype: false, variadic: false }
				],
				returnTypeId: '00000000-0000-0000-0000-000000000109'
			},
			{
				kind: 'Infix',
				args: [
					{ typeId: '49748e47-8d91-5269-9a34-2e8ca194e0f2', optional: false, setoftype: false, variadic: false },
					{ typeId: '49748e47-8d91-5269-9a34-2e8ca194e0f2', optional: false, setoftype: false, variadic: false }
				],
				returnTypeId: '00000000-0000-0000-0000-000000000109'
			},
			{
				kind: 'Infix',
				args: [
					{ typeId: '0d14e49f-d9f9-51f0-b8f4-c432982cbac2', optional: false, setoftype: false, variadic: false },
					{ typeId: '0d14e49f-d9f9-51f0-b8f4-c432982cbac2', optional: false, setoftype: false, variadic: false }
				],
				returnTypeId: '00000000-0000-0000-0000-000000000109'
			},
			{
				kind: 'Infix',
				args: [
					{ typeId: '00000000-0000-0000-0000-000000000130', optional: false, setoftype: false, variadic: false },
					{ typeId: '00000000-0000-0000-0000-000000000130', optional: false, setoftype: false, variadic: false }
				],
				returnTypeId: '00000000-0000-0000-0000-000000000109'
			},
			{
				kind: 'Infix',
				args: [
					{ typeId: '00000000-0000-0000-0000-00000000010c', optional: false, setoftype: false, variadic: false },
					{ typeId: '00000000-0000-0000-0000-00000000010c', optional: false, setoftype: false, variadic: false }
				],
				returnTypeId: '00000000-0000-0000-0000-000000000109'
			},
			{
				kind: 'Infix',
				args: [
					{ typeId: '00000000-0000-0000-0000-00000000010d', optional: false, setoftype: false, variadic: false },
					{ typeId: '00000000-0000-0000-0000-00000000010d', optional: false, setoftype: false, variadic: false }
				],
				returnTypeId: '00000000-0000-0000-0000-000000000109'
			},
			{
				kind: 'Infix',
				args: [
					{ typeId: '15315dad-c4ad-5335-97d6-4612e66ffb71', optional: false, setoftype: false, variadic: false },
					{ typeId: '00000000-0000-0000-0000-000000000108', optional: false, setoftype: false, variadic: false }
				],
				returnTypeId: '00000000-0000-0000-0000-000000000109'
			},
			{
				kind: 'Infix',
				args: [
					{ typeId: '00000000-0000-0000-0000-000000000108', optional: false, setoftype: false, variadic: false },
					{ typeId: '00000000-0000-0000-0000-000000000108', optional: false, setoftype: false, variadic: false }
				],
				returnTypeId: '00000000-0000-0000-0000-000000000109'
			},
			{
				kind: 'Infix',
				args: [
					{ typeId: '00000000-0000-0000-0000-00000000010b', optional: false, setoftype: false, variadic: false },
					{ typeId: '00000000-0000-0000-0000-00000000010b', optional: false, setoftype: false, variadic: false }
				],
				returnTypeId: '00000000-0000-0000-0000-000000000109'
			},
			{
				kind: 'Infix',
				args: [
					{ typeId: '00000000-0000-0000-0000-000000000111', optional: false, setoftype: false, variadic: false },
					{ typeId: '00000000-0000-0000-0000-000000000111', optional: false, setoftype: false, variadic: false }
				],
				returnTypeId: '00000000-0000-0000-0000-000000000109'
			}
		],
		or: [
			{
				kind: 'Infix',
				args: [
					{ typeId: '00000000-0000-0000-0000-000000000109', optional: false, setoftype: false, variadic: false },
					{ typeId: '00000000-0000-0000-0000-000000000109', optional: false, setoftype: false, variadic: false }
				],
				returnTypeId: '00000000-0000-0000-0000-000000000109'
			}
		],
		and: [
			{
				kind: 'Infix',
				args: [
					{ typeId: '00000000-0000-0000-0000-000000000109', optional: false, setoftype: false, variadic: false },
					{ typeId: '00000000-0000-0000-0000-000000000109', optional: false, setoftype: false, variadic: false }
				],
				returnTypeId: '00000000-0000-0000-0000-000000000109'
			}
		],
		'+': [
			{
				kind: 'Infix',
				args: [
					{ typeId: '00000000-0000-0000-0000-0000000001ff', optional: false, setoftype: false, variadic: false },
					{ typeId: '00000000-0000-0000-0000-0000000001ff', optional: false, setoftype: false, variadic: false }
				],
				returnTypeId: '00000000-0000-0000-0000-0000000001ff'
			},
			{
				kind: 'Infix',
				args: [
					{ typeId: '00000000-0000-0000-0000-000000000110', optional: false, setoftype: false, variadic: false },
					{ typeId: '00000000-0000-0000-0000-000000000110', optional: false, setoftype: false, variadic: false }
				],
				returnTypeId: '00000000-0000-0000-0000-000000000110'
			},
			{
				kind: 'Infix',
				args: [
					{ typeId: '00000000-0000-0000-0000-00000000010a', optional: false, setoftype: false, variadic: false },
					{ typeId: '00000000-0000-0000-0000-00000000010e', optional: false, setoftype: false, variadic: false }
				],
				returnTypeId: '00000000-0000-0000-0000-00000000010a'
			},
			{
				kind: 'Infix',
				args: [
					{ typeId: '00000000-0000-0000-0000-00000000010e', optional: false, setoftype: false, variadic: false },
					{ typeId: '00000000-0000-0000-0000-00000000010e', optional: false, setoftype: false, variadic: false }
				],
				returnTypeId: '00000000-0000-0000-0000-00000000010e'
			},
			{
				kind: 'Infix',
				args: [
					{ typeId: '49748e47-8d91-5269-9a34-2e8ca194e0f2', optional: false, setoftype: false, variadic: false },
					{ typeId: '49748e47-8d91-5269-9a34-2e8ca194e0f2', optional: false, setoftype: false, variadic: false }
				],
				returnTypeId: '49748e47-8d91-5269-9a34-2e8ca194e0f2'
			},
			{
				kind: 'Infix',
				args: [
					{ typeId: 'c3231f27-c8a1-5a0c-9830-c71206020eac', optional: false, setoftype: false, variadic: false },
					{ typeId: 'c3231f27-c8a1-5a0c-9830-c71206020eac', optional: false, setoftype: false, variadic: false }
				],
				returnTypeId: 'c3231f27-c8a1-5a0c-9830-c71206020eac'
			},
			{
				kind: 'Infix',
				args: [
					{ typeId: '00000000-0000-0000-0000-00000000010c', optional: false, setoftype: false, variadic: false },
					{ typeId: '00000000-0000-0000-0000-00000000010e', optional: false, setoftype: false, variadic: false }
				],
				returnTypeId: '00000000-0000-0000-0000-00000000010b'
			},
			{
				kind: 'Infix',
				args: [
					{ typeId: '00000000-0000-0000-0000-00000000010c', optional: false, setoftype: false, variadic: false },
					{ typeId: '00000000-0000-0000-0000-000000000112', optional: false, setoftype: false, variadic: false }
				],
				returnTypeId: '00000000-0000-0000-0000-00000000010c'
			},
			{
				kind: 'Infix',
				args: [
					{ typeId: '00000000-0000-0000-0000-00000000010d', optional: false, setoftype: false, variadic: false },
					{ typeId: '00000000-0000-0000-0000-00000000010e', optional: false, setoftype: false, variadic: false }
				],
				returnTypeId: '00000000-0000-0000-0000-00000000010d'
			},
			{
				kind: 'Infix',
				args: [
					{ typeId: '00000000-0000-0000-0000-000000000112', optional: false, setoftype: false, variadic: false },
					{ typeId: '00000000-0000-0000-0000-000000000112', optional: false, setoftype: false, variadic: false }
				],
				returnTypeId: '00000000-0000-0000-0000-000000000112'
			},
			{
				kind: 'Infix',
				args: [
					{ typeId: '00000000-0000-0000-0000-00000000010a', optional: false, setoftype: false, variadic: false },
					{ typeId: '00000000-0000-0000-0000-000000000111', optional: false, setoftype: false, variadic: false }
				],
				returnTypeId: '00000000-0000-0000-0000-00000000010a'
			},
			{
				kind: 'Infix',
				args: [
					{ typeId: '00000000-0000-0000-0000-00000000010c', optional: false, setoftype: false, variadic: false },
					{ typeId: '00000000-0000-0000-0000-000000000111', optional: false, setoftype: false, variadic: false }
				],
				returnTypeId: '00000000-0000-0000-0000-00000000010b'
			},
			{
				kind: 'Infix',
				args: [
					{ typeId: '00000000-0000-0000-0000-00000000010d', optional: false, setoftype: false, variadic: false },
					{ typeId: '00000000-0000-0000-0000-000000000111', optional: false, setoftype: false, variadic: false }
				],
				returnTypeId: '00000000-0000-0000-0000-00000000010d'
			},
			{
				kind: 'Infix',
				args: [
					{ typeId: '00000000-0000-0000-0000-00000000010e', optional: false, setoftype: false, variadic: false },
					{ typeId: '00000000-0000-0000-0000-000000000111', optional: false, setoftype: false, variadic: false }
				],
				returnTypeId: '00000000-0000-0000-0000-000000000111'
			},
			{
				kind: 'Infix',
				args: [
					{ typeId: '00000000-0000-0000-0000-00000000010b', optional: false, setoftype: false, variadic: false },
					{ typeId: '00000000-0000-0000-0000-00000000010e', optional: false, setoftype: false, variadic: false }
				],
				returnTypeId: '00000000-0000-0000-0000-00000000010b'
			},
			{
				kind: 'Infix',
				args: [
					{ typeId: '00000000-0000-0000-0000-000000000108', optional: false, setoftype: false, variadic: false },
					{ typeId: '00000000-0000-0000-0000-000000000108', optional: false, setoftype: false, variadic: false }
				],
				returnTypeId: '00000000-0000-0000-0000-000000000108'
			},
			{
				kind: 'Infix',
				args: [
					{ typeId: '00000000-0000-0000-0000-00000000010b', optional: false, setoftype: false, variadic: false },
					{ typeId: '00000000-0000-0000-0000-000000000111', optional: false, setoftype: false, variadic: false }
				],
				returnTypeId: '00000000-0000-0000-0000-00000000010b'
			},
			{
				kind: 'Infix',
				args: [
					{ typeId: '00000000-0000-0000-0000-000000000111', optional: false, setoftype: false, variadic: false },
					{ typeId: '00000000-0000-0000-0000-000000000111', optional: false, setoftype: false, variadic: false }
				],
				returnTypeId: '00000000-0000-0000-0000-000000000111'
			}
		],
		'-': [
			{
				kind: 'Infix',
				args: [
					{ typeId: '00000000-0000-0000-0000-0000000001ff', optional: false, setoftype: false, variadic: false },
					{ typeId: '00000000-0000-0000-0000-0000000001ff', optional: false, setoftype: false, variadic: false }
				],
				returnTypeId: '00000000-0000-0000-0000-0000000001ff'
			},
			{
				kind: 'Infix',
				args: [
					{ typeId: '00000000-0000-0000-0000-000000000110', optional: false, setoftype: false, variadic: false },
					{ typeId: '00000000-0000-0000-0000-000000000110', optional: false, setoftype: false, variadic: false }
				],
				returnTypeId: '00000000-0000-0000-0000-000000000110'
			},
			{
				kind: 'Infix',
				args: [
					{ typeId: '00000000-0000-0000-0000-00000000010a', optional: false, setoftype: false, variadic: false },
					{ typeId: '00000000-0000-0000-0000-00000000010e', optional: false, setoftype: false, variadic: false }
				],
				returnTypeId: '00000000-0000-0000-0000-00000000010a'
			},
			{
				kind: 'Infix',
				args: [
					{ typeId: '00000000-0000-0000-0000-00000000010a', optional: false, setoftype: false, variadic: false },
					{ typeId: '00000000-0000-0000-0000-00000000010a', optional: false, setoftype: false, variadic: false }
				],
				returnTypeId: '00000000-0000-0000-0000-00000000010e'
			},
			{
				kind: 'Infix',
				args: [
					{ typeId: '00000000-0000-0000-0000-00000000010e', optional: false, setoftype: false, variadic: false },
					{ typeId: '00000000-0000-0000-0000-00000000010e', optional: false, setoftype: false, variadic: false }
				],
				returnTypeId: '00000000-0000-0000-0000-00000000010e'
			},
			{
				kind: 'Infix',
				args: [
					{ typeId: '49748e47-8d91-5269-9a34-2e8ca194e0f2', optional: false, setoftype: false, variadic: false },
					{ typeId: '49748e47-8d91-5269-9a34-2e8ca194e0f2', optional: false, setoftype: false, variadic: false }
				],
				returnTypeId: '49748e47-8d91-5269-9a34-2e8ca194e0f2'
			},
			{
				kind: 'Infix',
				args: [
					{ typeId: 'c3231f27-c8a1-5a0c-9830-c71206020eac', optional: false, setoftype: false, variadic: false },
					{ typeId: 'c3231f27-c8a1-5a0c-9830-c71206020eac', optional: false, setoftype: false, variadic: false }
				],
				returnTypeId: 'c3231f27-c8a1-5a0c-9830-c71206020eac'
			},
			{
				kind: 'Infix',
				args: [
					{ typeId: '00000000-0000-0000-0000-00000000010c', optional: false, setoftype: false, variadic: false },
					{ typeId: '00000000-0000-0000-0000-00000000010e', optional: false, setoftype: false, variadic: false }
				],
				returnTypeId: '00000000-0000-0000-0000-00000000010b'
			},
			{
				kind: 'Infix',
				args: [
					{ typeId: '00000000-0000-0000-0000-00000000010c', optional: false, setoftype: false, variadic: false },
					{ typeId: '00000000-0000-0000-0000-000000000112', optional: false, setoftype: false, variadic: false }
				],
				returnTypeId: '00000000-0000-0000-0000-00000000010c'
			},
			{
				kind: 'Infix',
				args: [
					{ typeId: '00000000-0000-0000-0000-00000000010c', optional: false, setoftype: false, variadic: false },
					{ typeId: '00000000-0000-0000-0000-00000000010c', optional: false, setoftype: false, variadic: false }
				],
				returnTypeId: '00000000-0000-0000-0000-000000000112'
			},
			{
				kind: 'Infix',
				args: [
					{ typeId: '00000000-0000-0000-0000-00000000010d', optional: false, setoftype: false, variadic: false },
					{ typeId: '00000000-0000-0000-0000-00000000010e', optional: false, setoftype: false, variadic: false }
				],
				returnTypeId: '00000000-0000-0000-0000-00000000010d'
			},
			{
				kind: 'Infix',
				args: [
					{ typeId: '00000000-0000-0000-0000-00000000010d', optional: false, setoftype: false, variadic: false },
					{ typeId: '00000000-0000-0000-0000-00000000010d', optional: false, setoftype: false, variadic: false }
				],
				returnTypeId: '00000000-0000-0000-0000-000000000111'
			},
			{
				kind: 'Infix',
				args: [
					{ typeId: '00000000-0000-0000-0000-000000000112', optional: false, setoftype: false, variadic: false },
					{ typeId: '00000000-0000-0000-0000-000000000112', optional: false, setoftype: false, variadic: false }
				],
				returnTypeId: '00000000-0000-0000-0000-000000000112'
			},
			{
				kind: 'Infix',
				args: [
					{ typeId: '00000000-0000-0000-0000-00000000010a', optional: false, setoftype: false, variadic: false },
					{ typeId: '00000000-0000-0000-0000-000000000111', optional: false, setoftype: false, variadic: false }
				],
				returnTypeId: '00000000-0000-0000-0000-00000000010a'
			},
			{
				kind: 'Infix',
				args: [
					{ typeId: '00000000-0000-0000-0000-00000000010c', optional: false, setoftype: false, variadic: false },
					{ typeId: '00000000-0000-0000-0000-000000000111', optional: false, setoftype: false, variadic: false }
				],
				returnTypeId: '00000000-0000-0000-0000-00000000010b'
			},
			{
				kind: 'Infix',
				args: [
					{ typeId: '00000000-0000-0000-0000-00000000010d', optional: false, setoftype: false, variadic: false },
					{ typeId: '00000000-0000-0000-0000-000000000111', optional: false, setoftype: false, variadic: false }
				],
				returnTypeId: '00000000-0000-0000-0000-00000000010d'
			},
			{
				kind: 'Infix',
				args: [
					{ typeId: '00000000-0000-0000-0000-00000000010e', optional: false, setoftype: false, variadic: false },
					{ typeId: '00000000-0000-0000-0000-000000000111', optional: false, setoftype: false, variadic: false }
				],
				returnTypeId: '00000000-0000-0000-0000-000000000111'
			},
			{
				kind: 'Infix',
				args: [
					{ typeId: '00000000-0000-0000-0000-00000000010b', optional: false, setoftype: false, variadic: false },
					{ typeId: '00000000-0000-0000-0000-00000000010e', optional: false, setoftype: false, variadic: false }
				],
				returnTypeId: '00000000-0000-0000-0000-00000000010b'
			},
			{
				kind: 'Infix',
				args: [
					{ typeId: '00000000-0000-0000-0000-000000000108', optional: false, setoftype: false, variadic: false },
					{ typeId: '00000000-0000-0000-0000-000000000108', optional: false, setoftype: false, variadic: false }
				],
				returnTypeId: '00000000-0000-0000-0000-000000000108'
			},
			{
				kind: 'Infix',
				args: [
					{ typeId: '00000000-0000-0000-0000-00000000010b', optional: false, setoftype: false, variadic: false },
					{ typeId: '00000000-0000-0000-0000-000000000111', optional: false, setoftype: false, variadic: false }
				],
				returnTypeId: '00000000-0000-0000-0000-00000000010b'
			},
			{
				kind: 'Infix',
				args: [
					{ typeId: '00000000-0000-0000-0000-00000000010b', optional: false, setoftype: false, variadic: false },
					{ typeId: '00000000-0000-0000-0000-00000000010b', optional: false, setoftype: false, variadic: false }
				],
				returnTypeId: '00000000-0000-0000-0000-000000000111'
			},
			{
				kind: 'Infix',
				args: [
					{ typeId: '00000000-0000-0000-0000-000000000111', optional: false, setoftype: false, variadic: false },
					{ typeId: '00000000-0000-0000-0000-000000000111', optional: false, setoftype: false, variadic: false }
				],
				returnTypeId: '00000000-0000-0000-0000-000000000111'
			}
		],
		'*': [
			{
				kind: 'Infix',
				args: [
					{ typeId: '00000000-0000-0000-0000-0000000001ff', optional: false, setoftype: false, variadic: false },
					{ typeId: '00000000-0000-0000-0000-0000000001ff', optional: false, setoftype: false, variadic: false }
				],
				returnTypeId: '00000000-0000-0000-0000-0000000001ff'
			},
			{
				kind: 'Infix',
				args: [
					{ typeId: '00000000-0000-0000-0000-000000000110', optional: false, setoftype: false, variadic: false },
					{ typeId: '00000000-0000-0000-0000-000000000110', optional: false, setoftype: false, variadic: false }
				],
				returnTypeId: '00000000-0000-0000-0000-000000000110'
			},
			{
				kind: 'Infix',
				args: [
					{ typeId: '49748e47-8d91-5269-9a34-2e8ca194e0f2', optional: false, setoftype: false, variadic: false },
					{ typeId: '49748e47-8d91-5269-9a34-2e8ca194e0f2', optional: false, setoftype: false, variadic: false }
				],
				returnTypeId: '49748e47-8d91-5269-9a34-2e8ca194e0f2'
			},
			{
				kind: 'Infix',
				args: [
					{ typeId: 'c3231f27-c8a1-5a0c-9830-c71206020eac', optional: false, setoftype: false, variadic: false },
					{ typeId: 'c3231f27-c8a1-5a0c-9830-c71206020eac', optional: false, setoftype: false, variadic: false }
				],
				returnTypeId: 'c3231f27-c8a1-5a0c-9830-c71206020eac'
			},
			{
				kind: 'Infix',
				args: [
					{ typeId: '00000000-0000-0000-0000-000000000108', optional: false, setoftype: false, variadic: false },
					{ typeId: '00000000-0000-0000-0000-000000000108', optional: false, setoftype: false, variadic: false }
				],
				returnTypeId: '00000000-0000-0000-0000-000000000108'
			}
		],
		'/': [
			{
				kind: 'Infix',
				args: [
					{ typeId: '00000000-0000-0000-0000-0000000001ff', optional: false, setoftype: false, variadic: false },
					{ typeId: '00000000-0000-0000-0000-0000000001ff', optional: false, setoftype: false, variadic: false }
				],
				returnTypeId: '00000000-0000-0000-0000-0000000001ff'
			},
			{
				kind: 'Infix',
				args: [
					{ typeId: '00000000-0000-0000-0000-000000000108', optional: false, setoftype: false, variadic: false },
					{ typeId: '00000000-0000-0000-0000-000000000108', optional: false, setoftype: false, variadic: false }
				],
				returnTypeId: '00000000-0000-0000-0000-000000000108'
			}
		],
		'//': [
			{
				kind: 'Infix',
				args: [
					{ typeId: '00000000-0000-0000-0000-0000000001ff', optional: false, setoftype: false, variadic: false },
					{ typeId: '00000000-0000-0000-0000-0000000001ff', optional: false, setoftype: false, variadic: false }
				],
				returnTypeId: '00000000-0000-0000-0000-0000000001ff'
			},
			{
				kind: 'Infix',
				args: [
					{ typeId: '00000000-0000-0000-0000-000000000110', optional: false, setoftype: false, variadic: false },
					{ typeId: '00000000-0000-0000-0000-000000000110', optional: false, setoftype: false, variadic: false }
				],
				returnTypeId: '00000000-0000-0000-0000-000000000110'
			},
			{
				kind: 'Infix',
				args: [
					{ typeId: '00000000-0000-0000-0000-000000000108', optional: false, setoftype: false, variadic: false },
					{ typeId: '00000000-0000-0000-0000-000000000108', optional: false, setoftype: false, variadic: false }
				],
				returnTypeId: '00000000-0000-0000-0000-000000000108'
			}
		],
		'%': [
			{
				kind: 'Infix',
				args: [
					{ typeId: '00000000-0000-0000-0000-0000000001ff', optional: false, setoftype: false, variadic: false },
					{ typeId: '00000000-0000-0000-0000-0000000001ff', optional: false, setoftype: false, variadic: false }
				],
				returnTypeId: '00000000-0000-0000-0000-0000000001ff'
			},
			{
				kind: 'Infix',
				args: [
					{ typeId: '00000000-0000-0000-0000-000000000110', optional: false, setoftype: false, variadic: false },
					{ typeId: '00000000-0000-0000-0000-000000000110', optional: false, setoftype: false, variadic: false }
				],
				returnTypeId: '00000000-0000-0000-0000-000000000110'
			},
			{
				kind: 'Infix',
				args: [
					{ typeId: '00000000-0000-0000-0000-000000000108', optional: false, setoftype: false, variadic: false },
					{ typeId: '00000000-0000-0000-0000-000000000108', optional: false, setoftype: false, variadic: false }
				],
				returnTypeId: '00000000-0000-0000-0000-000000000108'
			}
		],
		'^': [
			{
				kind: 'Infix',
				args: [
					{ typeId: '00000000-0000-0000-0000-0000000001ff', optional: false, setoftype: false, variadic: false },
					{ typeId: '00000000-0000-0000-0000-0000000001ff', optional: false, setoftype: false, variadic: false }
				],
				returnTypeId: '00000000-0000-0000-0000-0000000001ff'
			},
			{
				kind: 'Infix',
				args: [
					{ typeId: '00000000-0000-0000-0000-000000000110', optional: false, setoftype: false, variadic: false },
					{ typeId: '00000000-0000-0000-0000-000000000110', optional: false, setoftype: false, variadic: false }
				],
				returnTypeId: '00000000-0000-0000-0000-000000000108'
			},
			{
				kind: 'Infix',
				args: [
					{ typeId: '00000000-0000-0000-0000-000000000108', optional: false, setoftype: false, variadic: false },
					{ typeId: '00000000-0000-0000-0000-000000000108', optional: false, setoftype: false, variadic: false }
				],
				returnTypeId: '00000000-0000-0000-0000-000000000108'
			}
		],
		in: [
			{
				kind: 'Infix',
				args: [
					{ typeId: '00000000-0000-0000-0000-000000000001', optional: false, setoftype: false, variadic: false },
					{ typeId: '00000000-0000-0000-0000-000000000001', optional: false, setoftype: true, variadic: false }
				],
				returnTypeId: '00000000-0000-0000-0000-000000000109'
			}
		],
		'not in': [
			{
				kind: 'Infix',
				args: [
					{ typeId: '00000000-0000-0000-0000-000000000001', optional: false, setoftype: false, variadic: false },
					{ typeId: '00000000-0000-0000-0000-000000000001', optional: false, setoftype: true, variadic: false }
				],
				returnTypeId: '00000000-0000-0000-0000-000000000109'
			}
		],
		union: [
			{
				kind: 'Infix',
				args: [
					{ typeId: '00000000-0000-0000-0000-000000000001', optional: false, setoftype: true, variadic: false },
					{ typeId: '00000000-0000-0000-0000-000000000001', optional: false, setoftype: true, variadic: false }
				],
				returnTypeId: '00000000-0000-0000-0000-000000000001',
				returnTypemod: 'SetOfType'
			}
		],
		except: [
			{
				kind: 'Infix',
				args: [
					{ typeId: '00000000-0000-0000-0000-000000000001', optional: false, setoftype: true, variadic: false },
					{ typeId: '00000000-0000-0000-0000-000000000001', optional: false, setoftype: true, variadic: false }
				],
				returnTypeId: '00000000-0000-0000-0000-000000000001',
				returnTypemod: 'SetOfType'
			}
		],
		intersect: [
			{
				kind: 'Infix',
				args: [
					{ typeId: '00000000-0000-0000-0000-000000000001', optional: false, setoftype: true, variadic: false },
					{ typeId: '00000000-0000-0000-0000-000000000001', optional: false, setoftype: true, variadic: false }
				],
				returnTypeId: '00000000-0000-0000-0000-000000000001',
				returnTypemod: 'SetOfType'
			}
		],
		'??': [
			{
				kind: 'Infix',
				args: [
					{ typeId: '00000000-0000-0000-0000-000000000001', optional: true, setoftype: false, variadic: false },
					{ typeId: '00000000-0000-0000-0000-000000000001', optional: false, setoftype: true, variadic: false }
				],
				returnTypeId: '00000000-0000-0000-0000-000000000001',
				returnTypemod: 'SetOfType'
			}
		],
		'++': [
			{
				kind: 'Infix',
				args: [
					{ typeId: 'a6f5468c-c2a6-5852-8f73-57484b1c6831', optional: false, setoftype: false, variadic: false },
					{ typeId: 'a6f5468c-c2a6-5852-8f73-57484b1c6831', optional: false, setoftype: false, variadic: false }
				],
				returnTypeId: 'a6f5468c-c2a6-5852-8f73-57484b1c6831'
			},
			{
				kind: 'Infix',
				args: [
					{ typeId: '00000000-0000-0000-0000-000000000102', optional: false, setoftype: false, variadic: false },
					{ typeId: '00000000-0000-0000-0000-000000000102', optional: false, setoftype: false, variadic: false }
				],
				returnTypeId: '00000000-0000-0000-0000-000000000102'
			},
			{
				kind: 'Infix',
				args: [
					{ typeId: '00000000-0000-0000-0000-000000000101', optional: false, setoftype: false, variadic: false },
					{ typeId: '00000000-0000-0000-0000-000000000101', optional: false, setoftype: false, variadic: false }
				],
				returnTypeId: '00000000-0000-0000-0000-000000000101'
			},
			{
				kind: 'Infix',
				args: [
					{ typeId: '00000000-0000-0000-0000-00000000010f', optional: false, setoftype: false, variadic: false },
					{ typeId: '00000000-0000-0000-0000-00000000010f', optional: false, setoftype: false, variadic: false }
				],
				returnTypeId: '00000000-0000-0000-0000-00000000010f'
			}
		],
		like: [
			{
				kind: 'Infix',
				args: [
					{ typeId: '00000000-0000-0000-0000-000000000101', optional: false, setoftype: false, variadic: false },
					{ typeId: '00000000-0000-0000-0000-000000000101', optional: false, setoftype: false, variadic: false }
				],
				returnTypeId: '00000000-0000-0000-0000-000000000109'
			}
		],
		ilike: [
			{
				kind: 'Infix',
				args: [
					{ typeId: '00000000-0000-0000-0000-000000000101', optional: false, setoftype: false, variadic: false },
					{ typeId: '00000000-0000-0000-0000-000000000101', optional: false, setoftype: false, variadic: false }
				],
				returnTypeId: '00000000-0000-0000-0000-000000000109'
			}
		],
		'not like': [
			{
				kind: 'Infix',
				args: [
					{ typeId: '00000000-0000-0000-0000-000000000101', optional: false, setoftype: false, variadic: false },
					{ typeId: '00000000-0000-0000-0000-000000000101', optional: false, setoftype: false, variadic: false }
				],
				returnTypeId: '00000000-0000-0000-0000-000000000109'
			}
		],
		'not ilike': [
			{
				kind: 'Infix',
				args: [
					{ typeId: '00000000-0000-0000-0000-000000000101', optional: false, setoftype: false, variadic: false },
					{ typeId: '00000000-0000-0000-0000-000000000101', optional: false, setoftype: false, variadic: false }
				],
				returnTypeId: '00000000-0000-0000-0000-000000000109'
			}
		]
	},
	Postfix: {},
	Prefix: {
		not: [
			{
				kind: 'Prefix',
				args: [{ typeId: '00000000-0000-0000-0000-000000000109', optional: false, setoftype: false, variadic: false }],
				returnTypeId: '00000000-0000-0000-0000-000000000109'
			}
		],
		'+': [
			{
				kind: 'Prefix',
				args: [{ typeId: '00000000-0000-0000-0000-0000000001ff', optional: false, setoftype: false, variadic: false }],
				returnTypeId: '00000000-0000-0000-0000-0000000001ff'
			},
			{
				kind: 'Prefix',
				args: [{ typeId: '00000000-0000-0000-0000-000000000110', optional: false, setoftype: false, variadic: false }],
				returnTypeId: '00000000-0000-0000-0000-000000000110'
			},
			{
				kind: 'Prefix',
				args: [{ typeId: '00000000-0000-0000-0000-000000000108', optional: false, setoftype: false, variadic: false }],
				returnTypeId: '00000000-0000-0000-0000-000000000108'
			}
		],
		'-': [
			{
				kind: 'Prefix',
				args: [{ typeId: '00000000-0000-0000-0000-0000000001ff', optional: false, setoftype: false, variadic: false }],
				returnTypeId: '00000000-0000-0000-0000-0000000001ff'
			},
			{
				kind: 'Prefix',
				args: [{ typeId: '00000000-0000-0000-0000-000000000110', optional: false, setoftype: false, variadic: false }],
				returnTypeId: '00000000-0000-0000-0000-000000000110'
			},
			{
				kind: 'Prefix',
				args: [{ typeId: '00000000-0000-0000-0000-00000000010e', optional: false, setoftype: false, variadic: false }],
				returnTypeId: '00000000-0000-0000-0000-00000000010e'
			},
			{
				kind: 'Prefix',
				args: [{ typeId: '00000000-0000-0000-0000-000000000108', optional: false, setoftype: false, variadic: false }],
				returnTypeId: '00000000-0000-0000-0000-000000000108'
			},
			{
				kind: 'Prefix',
				args: [{ typeId: '00000000-0000-0000-0000-000000000111', optional: false, setoftype: false, variadic: false }],
				returnTypeId: '00000000-0000-0000-0000-000000000111'
			}
		],
		exists: [
			{
				kind: 'Prefix',
				args: [{ typeId: '00000000-0000-0000-0000-000000000001', optional: false, setoftype: true, variadic: false }],
				returnTypeId: '00000000-0000-0000-0000-000000000109'
			}
		],
		distinct: [
			{
				kind: 'Prefix',
				args: [{ typeId: '00000000-0000-0000-0000-000000000001', optional: false, setoftype: true, variadic: false }],
				returnTypeId: '00000000-0000-0000-0000-000000000001',
				returnTypemod: 'SetOfType'
			}
		]
	},
	Ternary: {
		if_else: [
			{
				kind: 'Ternary',
				args: [
					{ typeId: '00000000-0000-0000-0000-000000000001', optional: false, setoftype: true, variadic: false },
					{ typeId: '00000000-0000-0000-0000-000000000109', optional: false, setoftype: false, variadic: false },
					{ typeId: '00000000-0000-0000-0000-000000000001', optional: false, setoftype: true, variadic: false }
				],
				returnTypeId: '00000000-0000-0000-0000-000000000001',
				returnTypemod: 'SetOfType'
			}
		]
	}
};

function op(...args) {
	let op = '';
	let params = [];
	let defs = null;
	if (args.length === 2) {
		if (typeof args[0] === 'string' && overloadDefs.Prefix[args[0]]) {
			op = args[0];
			params = [args[1]];
			defs = overloadDefs.Prefix[op];
		} else if (typeof args[1] === 'string' && overloadDefs.Postfix[args[1]]) {
			op = args[1];
			params = [args[0]];
			defs = overloadDefs.Postfix[op];
		}
	} else if (args.length === 3) {
		if (typeof args[1] === 'string') {
			op = args[1];
			params = [args[0], args[2]];
			defs = overloadDefs.Infix[op];
		}
	} else if (args.length === 5) {
		if (typeof args[1] === 'string' && typeof args[3] === 'string') {
			// Python-style if-else
			op = `${args[1]}_${args[3]}`;
			params = [args[0], args[2], args[4]];
			defs = overloadDefs.Ternary[op];
		}
	} else if (args.length === 6) {
		// Functional-style if-then-else
		if (typeof args[0] === 'string' && typeof args[2] === 'string' && typeof args[4] === 'string') {
			op = `${args[0]}_${args[4]}`;
			params = [args[3], args[1], args[5]];
			defs = overloadDefs.Ternary[op];
		}
	}

	if (!defs) {
		throw new Error(`No operator exists with signature: ${args.map((arg) => `${arg}`).join(', ')}`);
	}

	const { kind, returnType, cardinality, args: resolvedArgs } = _.syntax.$resolveOverload(op, params, _.spec, defs);

	return _.syntax.$expressionify({
		__kind__: $.ExpressionKind.Operator,
		__element__: returnType,
		__cardinality__: cardinality,
		__name__: op,
		__opkind__: kind,
		__args__: resolvedArgs
	});
}

export { op };
