// GENERATED by @edgedb/generate v0.5.3

import type * as edgedb from 'edgedb';
export declare const runnableExpressionKinds: Set<edgedb.$.ExpressionKind>;
export declare function $queryFunc(this: any, cxn: edgedb.Executor, args: any): Promise<unknown>;
export declare function $queryFuncJSON(this: any, cxn: edgedb.Executor, args: any): Promise<string>;
